### ISSUE TITLE
Ability to push modification on all clients at the same time

### ISSUE THREAD

**Issue by ThomasCrvsr** [MicrosoftDX/Vorlonjs#101]
Firstly : great work on this cool project :)

Secondly : It's just an idea of enhancement but I don't know if it's possible at the moment. When you make changes, I thought it would be great to push those changes simultaneously on several selected devices (to spot differences in behaviour or in styles for examples).

**Comment by meulta** [comment]
Thanks ! :)

Great idea !

**Comment by ThomasCrvsr** [comment]
I gave a thought about this while testing vorlon and I didn't find an intuitive way to integrate it in the UI. I'd be glad to work on this, but I'd rather see with you about detailing the feature :)

As I understood, for the moment devices aren't group by application, are they ? If not, I think it might be great in a first time to be able to do that.

**Comment by deltakosh** [comment]
Hey Thomas, you can reach me on davca@microsoft.com. I'm closing the issue for now. Let's discuss over email as we already have plan for multicasting

**Comment by ThomasCrvsr** [comment]
Great ! I'll try to send you an email today :)
