### ISSUE TITLE
use vorlon programmatically

### ISSUE THREAD

**Issue by peutetre** [MicrosoftDX/Vorlonjs#102]
It would be nice to be able to use vorlon programmatically, right now, importing `vorlon` starts the server.

Would love something like:
```
var vorlon = require('vorlon');
vorlon.start(options);
vorlon.stop();
```

**Comment by deltakosh** [comment]
That's definitely a great idea! Let's add it to our backlog:)

**Comment by kim3er** [comment]
+1

**Comment by killroy42** [comment]
+1

**Comment by eternalsky** [comment]
+1 it's great if vorlon can work with gulp

**Comment by deltakosh** [comment]
This is now available on dev branch.
Here is a sample:
https://github.com/MicrosoftDX/Vorlonjs/blob/dev/Plugins/samples/nodejs/app.js
