### ISSUE TITLE
DOM Explorer: refresh button's state inidcator broken

### ISSUE THREAD

**Issue by csuwildcat** [MicrosoftDX/Vorlonjs#103]
@deltakosh: In reviewing the latest changes in preparation for the addition of a global dirty check event, it appears someone broke the state indicator on the refresh button of DOM Explorer. The button no longer shows a color change when the DOM of the remote page has been modified.

**Comment by meulta** [comment]
Will check.

**Comment by deltakosh** [comment]
Gleborgne is on point for This one

**Comment by csuwildcat** [comment]
@meulta @gleborgne just FYI, I'm in the process of enabling a global dirty notification/event at the Core/Plugin level that all authors can listen for. This will keep everyone from doing their own basic state notifications and harming perf. Once completed, I will rewire the refresh button to listen via the new mechanism.

**Comment by deltakosh** [comment]
Ok sounds great. So We let you handle this @csuwildcat

**Comment by csuwildcat** [comment]
No problem! :)

**Comment by deltakosh** [comment]
Fixed by #106 so far
