### ISSUE TITLE
Add npm package to use it in plugins.

### ISSUE THREAD

**Issue by HectorCodefilo** [MicrosoftDX/Vorlonjs#105]
I have been thinking about work in a screentshot plugin (it could be insteresting for bug tracking) and i would like to add some npm package that use phantomjs to take a screenshot of the web client. Could it be possible?

**Comment by deltakosh** [comment]
Hello, this is not the goal. We want vorlon to run on client devices and use client browser

**Comment by cubitouch** [comment]
Something like that would be interesting coupled with Console plugin : http://stackoverflow.com/questions/4912092/using-html5-canvas-javascript-to-take-screenshots
Never used it, do not know if it is stable enough these days.

**Comment by deltakosh** [comment]
Yes but does it work on EVERY device/browsers/fridges?

**Comment by cubitouch** [comment]
I believe it do not.
According to [this](http://caniuse.com/#feat=nav-timing) my Network plugin is not interesting either ?

**Comment by deltakosh** [comment]
There is a slight difference before working just with Chrome and this :)

**Comment by deltakosh** [comment]
My mental limit is: does it work for Ie9 :)

**Comment by cubitouch** [comment]
Yes, I understand :)
David Rousset presented it this way too at the Paris' Build Tour.

**Comment by deltakosh** [comment]
Thank you so much for your kind comprehension

**Comment by cubitouch** [comment]
Seems a little more than just Chrome anyway : https://github.com/niklasvh/html2canvas#browser-compatibility

**Comment by deltakosh** [comment]
Interesting...would love to see it working with real sites

**Comment by HectorCodefilo** [comment]
I have been trying html2canvas for some test. It is not captures a perfect screenshot of client, for example, when you try to shot a page with an iframe it can not paint that element (CORS). (Look at twitter plugin when you click on "Test on this page" in http://html2canvas.hertzen.com/examples.html). However it is easy to use. You can take a shot (on callback you will get a canvas element) and then use .toDataURL() js function (https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL#Browser_compatibility), that will return a base64 image which we can send to VorlonJs Dashboard. It could be interesting, isn't it?

**Comment by cubitouch** [comment]
http://html2canvas.hertzen.com/screenshots.html

Yahoo website give a nice rendering, but some details (like the printed script tag and texts that are not properly aligned) is a little painful... But the weather widget seems to be working :D
The Javascript is disabled in this example page, it may explain some of these.

**Comment by deltakosh** [comment]
Yep but in this case why do we need a screenshot which is not accurate? To debug you want the real screenshot. An approximate one has no value or am I missing something?

**Comment by cubitouch** [comment]
I agree. Maybe it can help locate the user, on a single page app ?

**Comment by deltakosh** [comment]
That's a really precise need;)

**Comment by HectorCodefilo** [comment]
I do not undertand what do you mean with locate the user on a single page app. (By the way, should i close this issue ?)

**Comment by deltakosh** [comment]
Yes please

**Comment by cubitouch** [comment]
@deltakosh: Yes :)
@HectorCodefilo: It can allow to have a look at the kind of page the user is on (if the "windows.location" is not sufficient enough : single page app, step form, ...)
