### ISSUE TITLE
Switch dashboard tab/panels element to component

### ISSUE THREAD

**Issue by csuwildcat** [MicrosoftDX/Vorlonjs#108]
I have this component finished, and it will radically simplify all the code surrounding creating of tabs and handling switching between content panels. I will swap out the existing stuff when the files in question settle down from the code churn.

Here's a link to the new component: https://github.com/x-tag/tabbox

**Comment by deltakosh** [comment]
Please sync with @gleborgne

**Comment by deltakosh** [comment]
Up?

**Comment by csuwildcat** [comment]
@gleborgne do you feel the project is in a state where I could swap out the code for tab/panel structure/behavior and not run into significant merge conflicts?

**Comment by gleborgne** [comment]
I just refactored object explorer so it's probably the right time. We won't be very active in the next couple of weeks

**Comment by csuwildcat** [comment]
@gleborgne as I am jumping in the project to swap out the legacy tab/panel code and have noticed a few of the component styles are being clobbered for various reasons. For instance: it looks like when the onload treeView spinner was added to DOM Explorer, someone set the other elements to `display: none;`, and when load finishes, they set them to `display: block;`. The issue here is that the custom element `x-controlbar` is a `display: flex;` element, and it is coded as such for specific reasons. Without a display layout of flex, it will fundamentally operate differently than it was coded to.

Another example: someone apparently wanted the search input in DOM Explorer to align on the right side of the x-controlbar. To do this, they set it to absolute and used positioning to forcibly put it there. This is incorrect. Flexbox ways to set the alignment of flex children. In this case, all that was necessary was setting the input to `margin-left: auto;`, instead of clobbering it with absolute positioning and 4 other properties. (I should note: you cannot absolutely position flex children, it will fundamentally break the flexible layout model in CSS, and will lead to unexpected render in some browsers)

Whether we are using components or not, we need to be careful not to override the base styles of element types and classes in ways that have negative side effects. I realize we're moving fast, and folks are doing great work in narrow time frames, but we all need to be more deliberate and attentive to the implementation details.

**Comment by csuwildcat** [comment]
@gleborgne I was able to restore the styles and implement the new ones in a bit cleaner ways. If I may offer one tip for the future: when you want to do something like hide/show of elements based on some condition in CSS (use of a class like `.active`), instead of setting overrides to initial states to `display: none;` then additional overrides for their active state, like `display: block;`, just set the negative case, like this: `#fooElement:not(.active) > x-controlbar { display: none; }`. This strategy is better because you don't have to know the initial display state of the elements you are targeting, and reset them for the active display state. In our real world example above, this allows the `x-controlbar` to be set to display none when you need it to hide, and then automatically restores the element to the proper flex style when the active class is applied - all by simply letting CSS fall back to the elements original display setting.

Hopefully this helps, if you want you can take a look when I check in the code ;)

**Comment by gleborgne** [comment]
I will definitely have a look once available 😊

**Comment by csuwildcat** [comment]
@gleborgne I'm still working on getting the new tabbox in (though it seems like a flexbox revamp of the layout may be an easier start), but I did commit modifications to the DOM Explorer that help maintain the flex layout and simplify the styles to take advantage of the way flex works. I have a pull here: https://github.com/MicrosoftDX/Vorlonjs/pull/151

The line with the alternate approach to hide/show that I suggest we use in similar cases in the future to not overwrite base class/component styles is highlighted here: https://github.com/csuwildcat/Vorlonjs/commit/0b359d484df358a1456b074ea7b1e10ef16de5cc#diff-ea9cd05361cbd6ee5280712a015f5a98R265

**Comment by gleborgne** [comment]
Thanks, I Will check

**Comment by deltakosh** [comment]
Hey @csuwildcat some news here?

**Comment by csuwildcat** [comment]
I attempted to do this a while back and I got about 2 days into it before
finding myself in the weeds. The tabbox component itself is simple, but
there was a ton of code and styles bound to the exact, current DOM
implementation, so I started to question the value of it. I can give it
another shot if you think it's important to make the switch.

**Comment by deltakosh** [comment]
I get your point. Let's close it then :)
