### ISSUE TITLE
Allow DomExplorer to dispatch node selection messages to all plugins.

### ISSUE THREAD

**Issue by PaGury** [MicrosoftDX/Vorlonjs#112]
Actually, DomExplorer dispatch a message to InteractiveConsole with the node identifier, the InteractiveConsole print "document.getElementById(NodeIdentifier)".

I suggest to allow DomExplorer to broadcast a message to all plugins with the most accurate selector for the selected node (not only nodes with IDs).

Is someone working on it ? I can do it.

Thanks !

**Comment by deltakosh** [comment]
That's a good idea! Can you just wait for the new DOMexplorer to be done? We are doing a lot of changes:)

**Comment by PaGury** [comment]
For sure ! I'm waiting for your "go" !

**Comment by csuwildcat** [comment]
@PaGury we did something similar to broadcast a dirty check event to all plugins, and I'm thinking there should be a generic means to raise these system-wide events. Perhaps you can do so when you implement this feature?

**Comment by deltakosh** [comment]
Hey DomExplorer is done. How do you want to find the most accurate selector?

**Comment by PaGury** [comment]
Nice ! 

Traversing the parents and retrieving an "nth-child()" selector would do the trick no ?
For optimizations purposes, we could delete parts of the selector above any node with ID.

example : 
The 3rd div has an ID : "my-div".

div:nth-child(1) > div:nth-child(3) > div:nth-child(2) > span:nth-child(3)
After optimizations : 
#my-div > span:nth-child(3)

What do you think about that ?

**Comment by PaGury** [comment]
Something like this would be great : http://jsfiddle.net/pserkujg/

**Comment by deltakosh** [comment]
Sounds like a good plan:) let's go then!

**Comment by meulta** [comment]
We will see in the future with broadcasting implementation
