### ISSUE TITLE
console.dir()

### ISSUE THREAD

**Issue by torreslucas13** [MicrosoftDX/Vorlonjs#113]
Hi, 

I'm tryng to use `console.dir(document.body)`, but its not working.
Some instruction?

**Comment by deltakosh** [comment]
Adding @gleborgne

**Comment by deltakosh** [comment]
We are still working on it:)

**Comment by torreslucas13** [comment]
Thx

**Comment by gleborgne** [comment]
What browser did you use ?

**Comment by torreslucas13** [comment]
Google Chrome

**Comment by deltakosh** [comment]
Fixed by #116
