### ISSUE TITLE
feature request : TS compiler plugin

### ISSUE THREAD

**Issue by jbousquie** [MicrosoftDX/Vorlonjs#114]
Avant tout, chapeau, c'est un super outil :-)

Je suis une fégnasse ce soir, donc désolé, ce sera en français (Môssieur).

Voici l'idée : 
Actuellement je code avec mon éditeur (ST ou VSCode) sur le poste sur lequel tourne Vorlon.js et je débugge le JS avec Vorlon.

Quand je code pour BabylonJS, j'écris du TS. 
Je passe ensuite à un terminal (suis sous linux) pour lancer un script gulp de compilation TS qui va générer ma nouvelle version du fichier JS. 
Je reloade enfin la page Web référençant le JS généré pour ré-entrer dans le cycle debug js sous vorlon.

Comme Vorlon, c'est du node, tout comme le compilateur TS, tout comme Gulp et que, dans ce cas précis (cycle dév/compil/débug) tout se déroule sur la même machine, je pensais qu'il était peut-être possible que la console web vorlon intègre au travers d'un plugin la possibilité de lancer la compil TS (sur mon filesystem local : depuis un emplacement défini par moi dans la console, pas d'upload de fichier TS vers le serveur vorlon, sinon ce serait encore plus pénible), le compte-rendu de la compil dans la console (on reste dans du débug) et que je n'ai alors plus que le reload classique de la page web  à faire pour charger/débugger le JS généré
<fin de la phrase de 2 km>

ouali oualou

je ne sais pas si je suis bien clair ...

**Comment by meulta** [comment]
I am switching back in english for everyone to understand :)

If I understand it correctly, you would like to be able to launch a TS compilation on your server ?
Would gulp-watch not do that for you automatically ?

**Comment by jbousquie** [comment]
yep : the server here is the development platform where the developer codes also.
I know Vorlon is great to debug many devices at once.

But what is debuging without the development platform besides ? Usually the guy who uses vorlon is the guy who codes too. I mean he switches from the debug too (vorlon) to the dev too (editor) again and again in the debug/code process.

So I wondered if the full debug process and its rendering in the dashboard could be plugged into vorlon so it would be an _integrated_ (to the point of view of the user) debug process ?

Imagine, we just then have only two tools to handle for the live code/debug process : 
* the editor, well, where we write the code, js or ts
* the vorlon dashboard where we compile/debug/inspect (all in one)

I mean integrating all the debug process (including compilation debug) into a unique tool would be so great for the final user :-)
I know it's not that easy for many languages... but I guess Node based compilers, like the TS compiler, could maybe easily be integrated in Vorlon. Don't really know actually, just a dream ;-)

**Comment by deltakosh** [comment]
I'm afraid this is beyond Vorlon.js gaol which is lightweight remote debugging :) But I clearly get your point

**Comment by jbousquie** [comment]
ok :-)

that was just a dream

**Comment by deltakosh** [comment]
But I still like you:D

**Comment by jbousquie** [comment]
mordelol
