### ISSUE TITLE
Suggestion: Use of relative paths

### ISSUE THREAD

**Issue by mauron85** [MicrosoftDX/Vorlonjs#115]
Currently all paths are absolute, which prevents usage of reverse proxies.

Rationale: I would like to "hide" vorlon server behind nginx proxy, but absolute paths are no go.

**Comment by meulta** [comment]
pulling @pierlag on this one

**Comment by meulta** [comment]
Hello, 

To help @pierlag correct the issue, can you give use more info about which path you are talking about? 

Thanks

**Comment by mauron85** [comment]
Dashboard part:
`xhr.open("GET", "/api/createsession");`
`window.location.assign("/dashboard/" + sessionId);`
` xhr.open("GET", "/api/getclients/" + DashboardManager.SessionId);`
in 
https://github.com/MicrosoftDX/Vorlonjs/blob/master/Server/public/vorlon.dashboardManager.ts

and so on ...

Server part:

`res.redirect('/login');`
in
https://github.com/MicrosoftDX/Vorlonjs/blob/master/Server/Scripts/vorlon.webServer.ts

**Comment by mauron85** [comment]
Basically my point is to make vorlon work under some basePath.

Eg: http://localhost/vorlon/

instead of:

http://localhost:port

**Comment by meulta** [comment]
Okay thanks for the details.
If I understand it correclty you want to be able to configure the base url you want for the API used by the Dashboard?

**Comment by mauron85** [comment]
Yes, that's correct.

**Comment by meulta** [comment]
Working on this, should be out early next week ;)

**Comment by mauron85** [comment]
Glad to hear that. :+1. Many projects are ignoring that (blame you strider-cd :-). I can test it if you want. Just write me name of your dev branch.

**Comment by meulta** [comment]
Yes ! We are about to release 0.0.15 and just after that I will give you a version to test :)

**Comment by deltakosh** [comment]
Hey guys! some news on this front?

**Comment by meulta** [comment]
got a bit delayed, next task for me after authentication ;)

**Comment by meulta** [comment]
@alexfrih is working on it right now :)

**Comment by meulta** [comment]
Any updates  @alexfrih ?

**Comment by alexfrih** [comment]
I think i'm ready for some tests with @meulta and @mauron85 !

**Comment by mauron85** [comment]
@alexfrih just let know where I can access code (branch name, commit number ...).

**Comment by alexfrih** [comment]
Ok so you can clone this repository : 

https://github.com/MicrosoftDX/Vorlonjs/tree/urlprefixes

After, in /Server/config.json at this line : 

`"baseURL": "",`

put your subdirectory name or leave it blank (it's depend) :

`"baseURL": "/subdirectory",`

and my conf for nginx :

```
server {
        listen       80;
        server_name  YOURSERVERNAME;                                                                                                                                                      

        root /path/to/Vorlonjs/Server/public;

        location ~* ^.+.(jpg|jpeg|gif|css|png|ico|xml)$ {
        		 expires          1d;
        }

        location /YOURSUBDIRECTORY/ {
                 proxy_pass       http://localhost:1337;
                 proxy_set_header Host      $host;
                 proxy_set_header X-Real-IP $remote_addr;
        }

        location /socket.io/ {
                 proxy_pass http://localhost:1337;
                 proxy_http_version 1.1;
                 proxy_set_header Upgrade $http_upgrade;
                 proxy_set_header Connection "upgrade";
                 proxy_set_header Host $host;
        }
}
```

And then send me your feedback !

**Comment by meulta** [comment]
The vorlon.js part is merged into the dev branch, @mauron85  can you validate that it is fixing your issue ?
@alexfrih can you update the doc in the VorlonjsWeb github repo ?

**Comment by mauron85** [comment]
I've just compiled and tested development-0.0.16 branch and it works great on localhost.

But I still have issue on server, where resources are not found.

Here is the link:
http://dev.mapilary.com/vorlonjs/

My nginx conf for that particular domain:
```
server {
    listen              80;
    listen              [::]:80;
    server_name         dev.mapilary.com;
    root                /var/www/dev.mapilary.com;

    include errorpages.conf;
    include maintenance.conf;

    location ~* \.(?:jp?g|png|gif|ico|woff|eot|svg|ttf|otf|js|css)$ {
        access_log off;
        expires -1;
    }

    location ^~ /api-docs {
        rewrite ^/api-docs(.*)$ /docs/api$1 permanent;
    }

    location ~* \.(?:html|appcache)$ {
        expires -1;
        add_header Cache-Control "must-revalidate, proxy-revalidate";
        #add_header Vary Accept-Encoding;
    }

    location /socket.io/ {
             proxy_pass http://localhost:1337;
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "upgrade";
             proxy_set_header Host $host;
    }

    location /vorlonjs/ {
         proxy_pass       http://localhost:1337;
         proxy_set_header Host      $host;
         proxy_set_header X-Real-IP $remote_addr;
    }
}
```

Server/config.json
```
    "baseURL": "/vorlonjs",
    "useSSL": false,
    "SSLkey": "cert/server.key",
    "SSLcert": "cert/server.crt",
    "includeSocketIO": true,
    "activateAuth": false,
    "username": "",
    "password": "",
    "plugins": [
        { "id": "CONSOLE", "name": "Interactive Console", "panel": "bottom", "foldername": "interactiveConsole", "enabled": true },
        { "id": "DOM", "name": "Dom Explorer", "panel": "top", "foldername": "domExplorer", "enabled": true },
        { "id": "MODERNIZR", "name": "Modernizr", "panel": "bottom", "foldername": "modernizrReport", "enabled": true },
        { "id": "OBJEXPLORER", "name": "Obj. Explorer", "panel": "top", "foldername": "objectExplorer", "enabled": true },
        { "id": "XHRPANEL", "name": "XHR", "panel": "top", "foldername": "xhrPanel", "enabled": true },
        { "id": "NGINSPECTOR", "name": "Ng. Inspector", "panel": "top", "foldername": "ngInspector", "enabled": false },
        { "id": "NETWORK", "name": "Network Monitor", "panel": "top", "foldername": "networkMonitor", "enabled": true },
        { "id": "RESOURCES", "name": "Resources Explorer", "panel": "top", "foldername": "resourcesExplorer", "enabled": true },
        { "id": "DEVICE", "name": "My Device", "panel": "top", "foldername": "device", "enabled": true },
        { "id": "UNITTEST", "name": "Unit Test", "panel": "top", "foldername": "unitTestRunner", "enabled": true }
    ]
}
```

**Comment by mauron85** [comment]
Also it would be great if socket.io baseUrl /socket.io/ could be configurable too.

**Comment by mauron85** [comment]
Also very small issue, on welcome page path to client script should reflect baseURL.

Now it always state:
TO GET STARTED, YOU MUST ADD A REFERENCE TO CLIENT SCRIPT IN THE PAGE OF YOUR WEBSITE, LIKE THIS :
<script src="http://localhost:1337/vorlon.js"></script>

**Comment by alexfrih** [comment]
Okay i'm on it. 
But your website is offline i need to check something on it can you put it online again please ? Thank you!

**Comment by alexfrih** [comment]
To make it work on your domain :
```
root                /var/www/dev.mapilary.com;
```
by
```
root                /var/www/dev.mapilary.com/Server/public;
```
For the second issue i will talk about it with my team because i need to have more details.
And for the last one thank you for the report. I will fix this today.

**Comment by mauron85** [comment]
@alexfrih site is up again.

> To make it work on your domain ...

Yes, that will do the trick, but IMHO instead of this, VorlonJs should use relative paths to static resources.

**Comment by alexfrih** [comment]
I have updated my nginx.conf
```
server {

        server_name  vorlon;

        location ~ ^/(fonts/|images/|javascripts/|stylesheets/|vorlon/|vorlon.dashboardManager.js|robots.txt|humans.txt|favicon.ico) {
                 root /Users/alexandre/Projects/Vorlonjs/Server/public;
                 access_log off;
                 expires 24h;
        }

        location /test {
                 proxy_set_header Upgrade $http_upgrade;
                 proxy_set_header Connection "upgrade";
                 proxy_http_version 1.1;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                 proxy_set_header Host      $host;
                 proxy_pass http://localhost:1337;
        }

        location /socket.io {
                 proxy_set_header Upgrade $http_upgrade;
                 proxy_set_header Connection "upgrade";
                 proxy_http_version 1.1;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                 proxy_set_header Host      $host;
                 proxy_pass http://localhost:1337;
        }
```
You should be ok with this conf. I close this issue, open again if you need it !
Thanks.

**Comment by mauron85** [comment]
Cannot reopen issue, as I'm not contributor.
But, guys will you accept my PR? I have changed vorlonjs to serve static resource from baseUrl. Think it's better then to rely on nginx. 

Here is the commit:
https://github.com/mauron85/Vorlonjs/commit/2b1b357d5df1d1daa9dc157b8a08178217d30aca


Here is my nginx conf:
```
server {
    listen              80;
    listen              [::]:80;
    server_name         dev.mapilary.com;
    root                /var/www/dev.mapilary.com;

    include errorpages.conf;
    include maintenance.conf;

    location ~* \.(?:jp?g|png|gif|ico|woff|eot|svg|ttf|otf|js|css)$ {
        access_log off;
        expires -1;
    }

    location ^~ /api-docs {
        rewrite ^/api-docs(.*)$ /docs/api$1 permanent;
    }

    location ~* \.(?:html|appcache)$ {
        expires -1;
        add_header Cache-Control "must-revalidate, proxy-revalidate";
        #add_header Vary Accept-Encoding;
    }

    location /socket.io/ {
             proxy_pass http://localhost:1337;
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "upgrade";
             proxy_set_header Host $host;
    }

    location ^~ /vorlonjs/ {
         proxy_pass       http://localhost:1337;
         proxy_set_header Host      $host;
         proxy_set_header X-Real-IP $remote_addr;
    }
}
```

And here is working vorlonjs demo:
http://dev.mapilary.com/vorlonjs/
