### ISSUE TITLE
Add Layout View to the DOM Explorer plugin

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#117]
Using `window.getComputedStyle()` (http://caniuse.com/#feat=getcomputedstyle) we could generate a Layout View of the computed styles of the inspected node :)

![image](https://cloud.githubusercontent.com/assets/7486151/8161052/6821db4a-1374-11e5-8f15-a7eedcb41295.png)

**Comment by deltakosh** [comment]
We are working on it :)
