### ISSUE TITLE
Console plugin with better errors handling

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#119]
Would be great to have a better errors handling using data from [window.error](https://developer.mozilla.org/fr/docs/Web/API/GlobalEventHandlers/onerror).
Coupled with a "Source" plugin to inspect source code files it would be very nice.

Already working on it ? :)

**Comment by meulta** [comment]
Hey,
What would you like to have exactly ? Can you be more precise? :)

Thanks

**Comment by cubitouch** [comment]
This function can be used to retrieve the URL and line number related to the error (not sure if we can do the same for console.log). It would allow us to see at what line and in which file the error occurs, and even open the file itself to see the source code that produced it. :)

This HTML source code:
`<script>
test
</script>`

Produce this in Firebug:
![image](https://cloud.githubusercontent.com/assets/7486151/8209074/4f33d898-150b-11e5-9701-26da790d3a65.png)

This source code, using window.onerror:
`<script>
window.onerror = function(a,b,c) {
	console.log(a);
	console.log(b);
	console.log(c);
};
test
</script>`

Produce this trace:
![image](https://cloud.githubusercontent.com/assets/7486151/8209112/7b2da30c-150b-11e5-83a2-cb5d205f3724.png)

**Comment by gleborgne** [comment]
that's definitely a good idea ! I will add it to console plugin

**Comment by deltakosh** [comment]
Done:)

**Comment by cubitouch** [comment]
I think this could be reopened in order to add line numbers and resource file name ?

**Comment by gleborgne** [comment]
I will re-check but we are logging the stack in the dashboard, it shows line numbers

**Comment by cubitouch** [comment]
You mean "file" line number or "console" line number?
I cannot find [here](https://github.com/MicrosoftDX/Vorlonjs/blob/master/Plugins/Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.dashboard.ts) where the line numbers could be rendered...
Same in the client side TS file, I cannot see where the line number is gathered.

**Comment by gleborgne** [comment]
The magic is client side here
window.addEventListener('error', () => { 
240                 var err = arguments[0]; 
241                  
242                 if (err.error) { 
243                     //this.addEntry({ messages: [err.error.message], type: "exception" }); 
244                     this.addEntry({ messages: [err.error.stack], type: "exception" }); 
245                 } 
246             });

**Comment by cubitouch** [comment]
My bad, I didn't saw it "in" the entry line :)

Do you think this is possible to put filename and line number right aligned, and have this information for console.log/error/...() also? Possibly using [this](http://stackoverflow.com/questions/9559725/extending-console-log-without-affecting-log-line) technique?

Something like this:
![image](https://cloud.githubusercontent.com/assets/7486151/8353709/2837dd5c-1b41-11e5-8796-ae09f1ca06c4.png)

**Comment by gleborgne** [comment]
Everything is possible. It's more about focusing energy where it provides most value

**Comment by cubitouch** [comment]
No problem, I will have a try later, probably after the Resource Inspector plugin release (then it will surely provides value) :)

Is it possible to reopen this issue then so it can be prioritized? (using Milestones?)

**Comment by deltakosh** [comment]
Actually I would prefer creating a new one :)

**Comment by cubitouch** [comment]
Done https://github.com/MicrosoftDX/Vorlonjs/issues/146

**Comment by deltakosh** [comment]
Thanks!
