### ISSUE TITLE
Split code for plugins

### ISSUE THREAD

**Issue by gleborgne** [MicrosoftDX/Vorlonjs#121]
some plugins like dom explorer and console start being quite heavy on the dashboard side. It should be better splitting plugins into 2 parts (client and dashboard)

**Comment by csuwildcat** [comment]
This is also a great idea for simplifying scope checks. In several places there are code blocks that rely on checking the "_side" property of objects to ascertain whether or not they are operating in the client or server env. Commingling the two leads to a rather confusing hurdle for first time plugin developers. Separating the scope would reduce code complexity and make developing plugins much easier - good call @gleborgne!

**Comment by deltakosh** [comment]
Done!
