### ISSUE TITLE
Wappalyzer plugin

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#122]
Would be nice to have a [Wappalyzer](https://github.com/AliasIO/Wappalyzer) plugin :)

It would display something like this in its tab:
![image](https://cloud.githubusercontent.com/assets/7486151/8230555/a9e8812e-15c1-11e5-9fa1-a663cb952a0c.png)

Not sure if we can gather as much data as the Chrome/Firefox extension, as it use HTTP headers for some guess, but client side libraries would be easy...

**Comment by meulta** [comment]
This is an interesting idea ! :)

**Comment by cubitouch** [comment]
I'm having a look at this plugin. It would involve a directory containing about 750 PNG icons.
How should I add and "register" (so that the server serve them) these resources into the plugins directory (if possible using a `git clone` so we can update if the Wappalizer repo' do)?

**Comment by deltakosh** [comment]
lol 750png? That's a lot! No way to pull them directly from the web?

**Comment by cubitouch** [comment]
Maybe from [here](https://github.com/AliasIO/Wappalyzer/tree/master/src/icons) in raw mode? :)

**Comment by deltakosh** [comment]
Yep

**Comment by cubitouch** [comment]
Will try that then :)

**Comment by cubitouch** [comment]
https://github.com/MicrosoftDX/Vorlonjs/pull/144
