### ISSUE TITLE
Custom directives break NGInspector

### ISSUE THREAD

**Issue by marauderz** [MicrosoftDX/Vorlonjs#128]
When a custom directive is in use (labeltest in this case)
 ```
<div>
        <div ng-cloak ng-repeat="svc in svclist">
            <div>Some Service</div>            
            <div><b><labeltest label="{{svc.nickname}}"></labeltest></b></div></div>
        </div>
    </div>
```
ngInspector can only see the values in the first ng-repeat node. clicking on the other nodes clears the view on the right.

![ngcap](https://cloud.githubusercontent.com/assets/6801023/8254258/7a2747e6-16c9-11e5-9069-b847ea564877.PNG)

**Comment by meulta** [comment]
pulling @PaGury

**Comment by sebastieno** [comment]
Could you send us the labeltest directive code (or even betten a small app) ? Thx for your feedback.

**Comment by marauderz** [comment]
Here you go
```
angular.module("vorlontestlabel",[])
.directive("labeltest",
function () {
    return {
        controller:function($scope,$http)
        {
            $scope.labeltext = "test label";
        },
        templateUrl: '/template/labeltemp.html',
        scope: {label:"@label"},
        restrict:"E"
    }
})
```
Here's the template for the directive
```
<div>{{label}}</div>
```
Controller for the actual page
```
  angular.module("vorlontest", ["vorlontestlabel"])
        .controller("vorlontest", ["$scope","$http",
            function($scope,$http) {                               
                $scope.getservices=function()
                {
                    $http.get("/services.js").success(function(data)
                    {
                        $scope.svclist = data;
                    })
                }
            }
        ])
```
The page itself
```
<body ng-app="vorlontest" ng-controller="vorlontest">    
    <div>
        <button class="button small" ng-click="getservices()">Get Services</button>
    </div>
    <div>
        <div ng-cloak ng-repeat="svc in svclist">
            <div>Some Service</div>            
            <div><b><labeltest label="{{svc.nickname}}"></labeltest></b></div></div>
        </div>
    </div>
</body>
```
The test data being loaded
```
[
    {
        "nickname": "Service 1",
        "name":"Plan 1",
        "serviceno": "0121111111",
        "accno": "123456-1"
    },
    {
        "nickname": "Service 2",
        "name": "Plan 2",
        "serviceno": "0122222222",
        "accno": "123456-2"
    },
    {
        "nickname": "Service 3",
        "name": "Plan 3",
        "serviceno": "0123333333",
        "accno": "123456-3"
    }
]
```

**Comment by sebastieno** [comment]
Thanks for sharing your code. We are trying to reproduce the error.

**Comment by meulta** [comment]
Hey @sebastieno 

Did you manage to reproduce this? :)

**Comment by sebastieno** [comment]
Actually, I did not manage to reproduce this bug.

Here what I see on the dashboard when I execute your app (the scopes details are correctly displayed) :

![nginspector](https://cloud.githubusercontent.com/assets/2248640/8277969/c3d06d64-18c7-11e5-9fba-e6e9d80ced1d.png)

The only modification I did on your code is the *getservices* implementation (I just replace your HTTP request by a call to the $timeout service to emulate it)
```javascript
$scope.getservices=function()
{
	$timeout(function() {
		$scope.svclist = [{
        		"nickname": "Service 1",
        		"name":"Plan 1",
        		"serviceno": "0121111111",
        		"accno": "123456-1"
   		 },
    		{
       			"nickname": "Service 2",
        		"name": "Plan 2",
        		"serviceno": "0122222222",
        		"accno": "123456-2"
   		},
    		{
        		"nickname": "Service 3",
        		"name": "Plan 3",
        		"serviceno": "0123333333",
        		"accno": "123456-3"
    		}];
	}, 1000);
}
```
I tested with AngularJS 1.4.1 and AngularJS 1.3.15 on Chrome. @PaGury, on your side, is that ok or did you reproduce the bug ?

Do you have more details (AngularJS version, your browser, etc.) to help me reproduce it ? Thanks again for your help.

**Comment by marauderz** [comment]
Angular Version is 1.4.0 rc1
Happens in both Chrome and IE11

The interesting thing is that are you displaying the data in a Custom Directive? Since my inspector has the blue thingies and yours don't.

![ngcap2](https://cloud.githubusercontent.com/assets/6801023/8279249/61422df2-1905-11e5-971a-d7a77f048516.PNG)

Also, as I mentioned, clicking on the first ng-repeat gets the values displayed, therefore the items marked 6 or 7 has details shown on the right. But everything else doesn't.

Let me try and make a more standalone demo, along with using the latest version of angular and see wheter I still get the problem.

**Comment by marauderz** [comment]
Ok, here's the bare minimal website which I just tested and exhibits the problem. Using Angular 1.4.1 from the CDN.
https://drive.google.com/file/d/0BxjkEc8OKoUIcHlMU0J0MWVIMWc/view?usp=sharing

**Comment by sebastieno** [comment]
Ok, you' sample reproduce the bug. I will investigate :)

**Comment by meulta** [comment]
Should be fixed, thanks @sebastieno :)

**Comment by marauderz** [comment]
Yes it is fixed.. hey.. plugin configuration moved to another file! :P
