### ISSUE TITLE
HTML5 Audio/Video plugin

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#131]
It would allow to track user actions on a `audio` and `video` tags using the different [events](https://developer.mozilla.org/fr/docs/Web/Guide/Events/Media_events), possibily using a timeline related to the media the user is playing.

The must would be to replay exactly what the user "http" requested (to reproduce a streaming server issue or something).

http://caniuse.com/#feat=video
http://caniuse.com/#feat=audio

**Comment by meulta** [comment]
Hello,

I am not sure I get what you would like to have here. Do you want to have a timeline giving you which event has been raised?

Thanks

**Comment by cubitouch** [comment]
Hello,

Yes, exactly. :)

The user start playing the media, pause after 1 minute, get back to 20 secondes before, jump to 2 minutes later. The idea is to display this timeline according to the media timeline (see where the user jumped in the media, the playing phases, etc.)

It would be interreting to be able to understand/reproduce a case in which the streaming server or the client would experience troubles, or for statistics for a streaming service (not sure if the last one is out of this Project scope).

**Comment by meulta** [comment]
And which debug information should this give to the dev using the dashboard? :)

**Comment by cubitouch** [comment]
Good point. For example, the delay between `seeking`and `seeked` events.
In fact, I was thinking about just observe the load/play/seek/error states and the waterfall these follow.

**Comment by deltakosh** [comment]
This one is a good candidate for 3rd party plugins
