### ISSUE TITLE
My solution for loggin & retrospective analysis (back from KiwiParty)

### ISSUE THREAD

**Issue by xtuc** [MicrosoftDX/Vorlonjs#132]
I spoke with @meulta about this idea and would like to know what you think about it.

You have considered a Redis server for this work but I don't think it's good. I propose to use ElasticSearch to store logs and Kibana 4 to query them. You could this way developpe a light production version of Vorlon. The user can make statistics on specific website.
ElasticSearch works with multiple indexes. Each Vorlon plugin and the dashboard itself could be such an index. When you receive a message from client, you just need to put the data you want to store into the ElasticSearch server. Kibana is optional because you can use a multitude of alternatives.

The goal is for example to store all XHR requests and make various statistics like the average response time. ElasticSearch is usable via APIs: features like average and simple monitoring can be visible on the dashboard.

I thought the project was in NodeJS but forgot that i'm speaking with Microsoft. I need to know what you think about this idea, before I learn typeScript and begin to work on this project.

Best regards, Sven SAULEAU

**Comment by meulta** [comment]
Hello Sven,

Thank you for taking the time to fill this issue :)

@pierlag is the one in charge of this logging/history feature. 
He will have a look and we will discuss this in the team to be sure which approach we want to choose.

**Comment by pierlag** [comment]
Sorry, we decided with the team that this feature is not in the scope of vorlon as a first step. We want a minimum of external dependency. Thanks
