### ISSUE TITLE
SSL certificates directory not properly detected ?

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#133]
When I try to start the VorlonJS server (I just cloned it), I run into this exception:

![image](https://cloud.githubusercontent.com/assets/7486151/8271789/c7ebe7d2-1829-11e5-88ce-e2788244bc84.png)

When I copy the "cert" directory into the "VorlonJS" directory this seems to work.
Is that normal? Shouldn't it be using the "Server/cert" directory by default?

**Comment by meulta** [comment]
pulling @pierlag
