### ISSUE TITLE
nginspector

### ISSUE THREAD

**Issue by gleborgne** [MicrosoftDX/Vorlonjs#138]
NgInspector assume client has Angular, and throw errors if it's not present.

Plugin should probably detect if angular is there and notify Dashboard accordingly

**Comment by meulta** [comment]
I am pretty sure this was the case originaly.

@sebastieno ? :)

**Comment by meulta** [comment]
Nevermind I fixed it ;)
Commit incoming

**Comment by sebastieno** [comment]
Thanks @meulta (I was so busy today that I could not fix this bug) !
I will try to make a PR Thursday with a message indicating that Angular is not present.
