### ISSUE TITLE
Unit test plugin

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#142]
Would be interresting to be able to run a unit test (or a scenario) from dashboard to a connected client using something like [QUnit](http://qunitjs.com/).

This subject can be very vast as web test libraries are very various... what do you think about that ?

**Comment by deltakosh** [comment]
This is definitely one of the idea we had in mind since the beginning. Having a plugin where on the dashboard side you can write code that could then be executed by the client side to to unit testing

**Comment by cubitouch** [comment]
I am thinking about something like this:
* Include the QUnit JS file on the client
* Drag-n-Drop unit test JS file on the Dashboard
* Transmit this code to the Client from the Dashboard
* Execute it on the Client
* Retrieve results on the Client using callbacks and send it back to the server
* Display a results table on the Dashboard

What do you think about that?
I thought about a directory to store a list of unit tests but I'm not sure how to properly architecture this...

**Comment by deltakosh** [comment]
I love this! I'm not for the directory but more for either filepicking/drag'n'dropping/manual typing

**Comment by killroy42** [comment]
Additionally, this seems to be a great way to connect multiple, physical test devices at once and send tests to all of them at the same time to verify various target devices/platforms at once, without complex/unreliable visualization.

**Comment by cubitouch** [comment]
Agreed I would be helpful, but since plugins are "client" related (IMHO) I am not sure that this will be in the first step.

I have heard that the Core Team are planning for [having a Redis](https://github.com/MicrosoftDX/Vorlonjs/issues/132) working with the Server to allow Data Analysis across clients.

**Comment by killroy42** [comment]
Or an API to connect the vorlon server to my own. Or run the vorlon server as a node module in-process with my server..

**Comment by cubitouch** [comment]
This PR have been open about that: https://github.com/MicrosoftDX/Vorlonjs/issues/102
