### ISSUE TITLE
Reload resources

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#143]
Hello,

It would be nice to be able to force the client to reload resources : Images, Javascripts, CSS

Should it be a new plugin or a new feature of an existent one? DOM Explorer?

**Comment by deltakosh** [comment]
Totally agree! I think it could just be a button in the DOM Explorer

**Comment by csuwildcat** [comment]
Just an idea: this could be a part of a new "Resource Inspector" plugin, given all the other kinds of resource-oriented features and views developers often use when developing an app/site.

**Comment by cubitouch** [comment]
I agree. I talked about it in that issue, closed but could be improved, to open a resource from an error line number: https://github.com/MicrosoftDX/Vorlonjs/issues/119

**Comment by deltakosh** [comment]
We have an intern in our team working with @meulta that will work on this.

Agree for this being part of the resource Inspector. that's a great idea

**Comment by deltakosh** [comment]
@colbin8r some progress here?
