### ISSUE TITLE
Resources Inspector plugin

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#145]
Create a plugin that can display/render/search into resources: JS files, CSS files, Images, ...
https://github.com/MicrosoftDX/Vorlonjs/issues/143#issuecomment-115054486

I think this plugin need to be "callable" from another plugin (Console or Network for example: click on a console entry would open the script/html file at the line that generated the entry, or click on the network call entry would open the associated resource, if relevant).

The only way I have found so far to get "not embeded" resources (like JS and CSS) is to send an XHR to retrieve its content. But it would also populate the Network and XHR plugins. Does someone have a better idea? Should the Network and XHR plugins try to ignore these XHR calls?

**Comment by deltakosh** [comment]
For me it is not a plugin but more a service provided by the platform (inside Core)

**Comment by gleborgne** [comment]
making xhr from dashboard to fetch resources will not work in many sites due to CORS policies. If you want to do that, fetching resources must be done from the node.js part

**Comment by colbin8r** [comment]
Does it make sense to integrate this functionality into the existing Resources Explorer plugin? Many of the popular web debugging tools have these two sets of functionality grouped together (i.e. cookies are grouped alongside JS and image assets in a Resource Explorer).

**Comment by deltakosh** [comment]
Agree Colbin8r. Let's do this way then. We will then publish a protocol for other plugins to invoke a specific file within resource epxlorer

**Comment by cubitouch** [comment]
Yes, right, I tought it was a different tab in the Chrome's dev tools.

@gleborgne: I wasn't talking about "dashboard side" but more about "client side" (as I was wondering about populating the Network and XHR plugins, which are based on client side data). Would you recommend a particular technique to do so? I'm not sure what you are refereing as "node.js part".

**Comment by gleborgne** [comment]
The network plugin is proxying xmlhttprequest. We could add a method in client base class that bypass the proxy. Issuing request from client would work. My mistake...
Vorlon has a server side node.js part. It's not just serving files, it's also using socket.io to pass messages between clients and dashboard. The node.js server can do more than that if we need to.

**Comment by cubitouch** [comment]
I think you talk about the XHR Panel (not Network Monitor) plugin. The Network Monitor plugin is based upon `window.performance` object. I do not have here any proxy I can filter to avoid having these XHR calls logged.

I will think about a method to filter these results. Maybe not rendering XHR calls which are already logged under the XHR plugin?

**Comment by colbin8r** [comment]
I'm having a difficult time finding ways to create a list of resources on the page. Here are the ideas that I've come up with:

1. Use `window.performance` to get a simple list. Contains no MIME information though.
2. Scrape/parse the DOM for `<script>`, `<style>`, and `<img>` tags as well as parse CSS for background assets. Difficult to do.

Then of course there is the problem of how to get the actual content of the asset as discussed above.

Finally, I don't see a solution to incorporate reloading assets (#143) dynamically. How would this work for `<img>`s or CSS images?

**Comment by cubitouch** [comment]
Interresting idea to use `window.performance` to gather a list of external assets.

For reloading CSS/JS/Images I think we can dynamically add a suffix to the url like `?reload=123456789`. I have no idea at the moment about CSS images...

**Comment by colbin8r** [comment]
Perhaps the issue of reloading CSS images will have to be a later feature.

There are many ways to do cachebusting like you mentioned. However, even if we can re-fetch the updated JavaScript, it may not execute in the correct scope which may lead to unexpected errors. This may simply be a limitation that we can't get around unless we use a reload style similar to livereload.

**Comment by deltakosh** [comment]
Hey guys some news here?
