### ISSUE TITLE
object explorer enhancements

### ISSUE THREAD

**Issue by gleborgne** [MicrosoftDX/Vorlonjs#148]
Just logging here to get feedback about features I thought of in object explorer :
- add settings for choosing display preferences (show/hide prototype chain, show/hide properties starting with "_")
- add watches to properties
- add hooks to properties and functions (that adds logs, stacktrace, ...)

What do you think ?

**Comment by deltakosh** [comment]
Love all of these ideas :)

**Comment by deltakosh** [comment]
GOOOOOOOOOOOO!

**Comment by deltakosh** [comment]
Up?

**Comment by gleborgne** [comment]
Still on track but you could postpone if you want to publish a new version soon

**Comment by gleborgne** [comment]
not really, depends on how much spare time I could save

**Comment by deltakosh** [comment]
Ok so to be safe, I'm moving it to 0.1.0

**Comment by meulta** [comment]
Moved
