### ISSUE TITLE
Monitoring start-up logging

### ISSUE THREAD

**Issue by killroy42** [MicrosoftDX/Vorlonjs#150]
Is there currently a way for the dashboard to show immediately once a client connects? I'd like to monitor logging that happens during the start up phase of my app, but I cannot monitor anything until I manually select the client in the Vorlon server dashboard. This also counts for page refreshing. It would be good if the server keeps a particular view open and survives client refreshes and page changes.

**Comment by meulta** [comment]
Right now, refreshing or changing page is the same.
We keep a client id to reconnect the same but all info is dropped.

What scenario do you want to fill here? :)

**Comment by meulta** [comment]
Anymore information here @killroy42 ? 
Thanks

**Comment by killroy42** [comment]
For me, once I click a link and the browser navigates to a new page, the vorlon console display stops, and I have to re-select the client from the menu on the left.

**Comment by meulta** [comment]
Hello,

fixed here : https://github.com/MicrosoftDX/Vorlonjs/commit/ae2a9e7febe17996dbe105ec26ae37d9ca4aea34

Right now it is reloading the dashboard on the browser level. I will open a new issue to do that without reload.
