### ISSUE TITLE
NGInspector : Error if ng-app and ng-controller not applied to same element

### ISSUE THREAD

**Issue by marauderz** [MicrosoftDX/Vorlonjs#152]
ngInspector is ok with code as such
```
<body ng-app="vorlontest" ng-controller="vorlontest">
    <div>
         <!-- The same code from my previous label issue -->
    </div>
</body>
```
But if the ng-app and ng-controller attributes are in different elements
```
<body ng-app="vorlontest" >
    <div ng-controller="vorlontest">
         <!-- The same code from my previous label issue -->
    </div>
</body>
```
Then on init an error occurs
```
SCRIPT5007: Unable to get property '1' of undefined or null reference
File: vorlon.js, Line: 1147, Column: 25
```
It's specifically pointing to this line >>>>
```
else if (angular.element(childNode).data("$ngControllerController")) {
 var constructor = angular.element(childNode).data("$ngControllerController").constructor;
 // Workaround for IE, name property of constructor return undefined :/
   // Get the name from the constructor function as string
    >>>>>var name = constructor.toString().match(/function (\w+)\(/)[1];
```
Error occurs in Chrome and IE10, most recent commit of Git  aac3788555142215afde4a7861bf5d9bde7a9ecd

**Comment by sebastieno** [comment]
Thanks @marauderz for the issue details. We work on it.

**Comment by meulta** [comment]
Any news on that @sebastieno  ? :)

**Comment by sebastieno** [comment]
Sorry for the delay (holidays without computer :P).
@PaGury, did you PR the fix ?

**Comment by meulta** [comment]
Hey, no worries.
I think he did not :)

**Comment by meulta** [comment]
@PaGury @sebastieno any news? 
Thanks guys

**Comment by meulta** [comment]
Fix is on its way by @PaGury :)

**Comment by deltakosh** [comment]
Hello, is it ok on your side @PaGury ?

**Comment by sebastieno** [comment]
Sorry for the delay. I just created a PR with @PaGury fix.
