### ISSUE TITLE
Server-side recording

### ISSUE THREAD

**Issue by killroy42** [MicrosoftDX/Vorlonjs#153]
Is there a simple (plugin-drive?) way to record logs from clients on the server? I would like to use it for a test team and be able to analyse data after a client failure.

**Comment by meulta** [comment]
Hello,

If by log you mean everything going in the console : the Interactive Console can get you the data live from a client.

Right now there is no correct way to record information and analyze it afterwards. We are working on this for the future release though ! :)

**Comment by deltakosh** [comment]
Hello this is out of the scope of Vorlon.js so far but this is a great idea. Closing for now.
