### ISSUE TITLE
Vorlonjs does not supported by IE8

### ISSUE THREAD

**Issue by hbbbs** [MicrosoftDX/Vorlonjs#158]
Help, please!
run in IE8, show error : Missing identifier

**Comment by hbbbs** [comment]
ie8

**Comment by cubitouch** [comment]
I'm not sure IE8 is or will be supported as some plugins use HTML5 new features.
@deltakosh: It would be great to have an official compatibility table (for users as much as for developers).

Could you be more specific about your exception anyway? Which line of which file is raising that error? Is it "dashboard" or "client" side?

**Comment by hbbbs** [comment]
Thanks for your reply.

Error  in vorlon.max.js ,Line 218 ："FluentDOM.for" , Missing identifier

	FluentDOM.for = function (element) {
	    var res = new FluentDOM(null);
	    res.element = element;
	    return res;
	};

**Comment by deltakosh** [comment]
pinging @gleborgne as he introduced this part. we will try to aupport ie8 even though ie9 is our lower bar

**Comment by gleborgne** [comment]
this code is on the dashboard side. Do you confirm you got this error in the dashboard ? meanwhile, there is many HTML5 in the dashboard, the dashboard will not work in IE8 anyway.

**Comment by deltakosh** [comment]
RIght I thought it was on the client side. Dashboard side is meant to be run on modern browsers only

**Comment by hbbbs** [comment]
Error in vorlon.max.js

**Comment by deltakosh** [comment]
But not on the Dashboard right??

**Comment by hbbbs** [comment]
not on  Dashboard , on IE console

**Comment by cubitouch** [comment]
I think he mean: On the IE console on the web page you are debugging, or on the IE console on the Vorlon dashboard?

**Comment by hbbbs** [comment]
On the IE console on the web page you are debugging

**Comment by hbbbs** [comment]
The page on the Chrome, Dashboard can  find  the page.
The page on the IE8, Dashboard can not find it, because the page has the error, IE console can find the error upon

**Comment by hbbbs** [comment]
on the client side

**Comment by meulta** [comment]
Hello hbbbs,

We will need to have more information about this to be able to understand the problem.
It would be really helpful if you could send us a sample which reproduce the problem

Can you do that? 

Thanks a lot

**Comment by hbbbs** [comment]
I'm glad to do it.

This is  my test page.
```html
<!DOCTYPE html>
<html>
<head>
  <title>Test</title>
</head>
<body>

  <p>Test</p>

  <script src="http://localhost:1337/vorlon.max.js"></script>
  
</body>
</html>
```
![image](https://cloud.githubusercontent.com/assets/4979976/8501909/b1f9c0fe-21dc-11e5-9a75-8bf4c58d0192.png)

![image](https://cloud.githubusercontent.com/assets/4979976/8501921/cd532a98-21dc-11e5-85c1-1008db9b4f31.png)

![image](https://cloud.githubusercontent.com/assets/4979976/8501943/039f8d08-21dd-11e5-994a-c7617c923f32.png)

**Comment by hbbbs** [comment]
I guess the reason may be the keyword conflict。

"FluentDOM.for = function (element){....}"

"for" is javascript reserved word.

**Comment by hbbbs** [comment]
I change "FluentDOM.for" to "FluentDOM.for_new", that error does not appear。

But we have the new problem:
IE8 gives me this error: Object doesn't support this action on line 331. 


![image](https://cloud.githubusercontent.com/assets/4979976/8502530/db5251bc-21e3-11e5-81b4-fff737e9defe.png)

"Object.defineProperty",the built-in IE8 method only works when applied to DOM objects。
I import es5-shim ,but it still does not work.

**Comment by meulta** [comment]
I am going to have a look

**Comment by meulta** [comment]
Sorry for the delay, we are in a vacation period here ;)
Do you by any chance have more info to share?

**Comment by hbbbs** [comment]
：） 
in a vacation.. envy you...

**Comment by sompylasar** [comment]
In ES3, the keywords cannot be used as property names, except if they are in brackets and quotes: `obj.for` will give an error, `obj['for']` won't.

**Comment by meulta** [comment]
Thx @sompylasar
