### ISSUE TITLE
Vorlon.JS not working on Android 2.3 and 4.0

### ISSUE THREAD

**Issue by Carlos487** [MicrosoftDX/Vorlonjs#163]
First I want to thank this team for this awesome tool.

This case was tested with a Cordova Application.

But, sadly it isn't working on Android 2.3 Gingerbread. I tested on a Galaxy Ace and when I was checking the adb logcat (android debug bridge), it shows the following error

```
D/CordovaLog(12916): http://my_vorlon_server_ip:1337/vorlon.js: Line 3 : Uncaught SyntaxError: Unexpected token for
```

In the Android 4.0.3 emulator, the client briefly appears on the vorlon.js console but the app crashed while it was opening, with this error on logcat.

```
D/dalvikvm( 1454): GC_CONCURRENT freed 34K, 1% free 19084K/19271K, paused 0ms+1ms
F/libc    ( 1454): Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1)
I/DEBUG   ( 1451): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   ( 1451): Build fingerprint: 'generic_x86/sdk_x86/generic_x86:4.0.4/IMM76D/eng.juntian.20120418.185032:eng/test-keys'
```

I also tested on a Android 4.1 and 5.1 phone, but in this case it worked correctly.

I know they are an old platform but in this case Vorlon.JS will shine because on them you cannot have any kind of remote debugging.

**Comment by meulta** [comment]
Hey,

Thanks for your feedback :)

I am pretty sure it cannot work on Android 2.1. For 4.0.3, I will see if wee can have a look.

**Comment by Carlos487** [comment]
Thanks @meulta but only for curiosity, what is the technical limitation that prevents vorlon.js to be used on Android 2.3 Gingerbread or older browsers?

**Comment by meulta** [comment]
Not sure why, it need to support socket.io for instance :)

**Comment by meulta** [comment]
@colbin8r  any news? :)

**Comment by deltakosh** [comment]
@csuwildcat can you have a look at this one?

**Comment by csuwildcat** [comment]
Yep, I'll take a look.

**Comment by csuwildcat** [comment]
@deltakosh @Carlos487 ran the test page on emulators for Android 4.3 and 5 today, both had socket errors for certain operations, but I can't be sure that it's not the emulator and some proxy or setup they have in place, because many things still work. I realize those aren't the versions you were having trouble with, but they were the ones available on the free emulator.

I'm now going to install Android Studio and try to run it there to test these versions and the ones you mentioned. I supposed the best case would be to have a real device running the versions you cited - I can look into getting some off of eBay.

I'll report back when I have more info.

**Comment by deltakosh** [comment]
Thanks!

**Comment by csuwildcat** [comment]
@deltakosh @Carlos487 OK, I have a shell Android project running that I'm now testing with. I have confirmed there is no issue on the default build of Android that runs in Android Studio, but that's not the versions specified here. I am going to try to run the versions you cited, and I will report back when I get them setup and tested.

**Comment by csuwildcat** [comment]
@deltakosh @Carlos487 I got emulators up and running for both Android 4 and Android 2.3. Here's the result:

- Android 4: Vorlon test page loaded enough to be registered in the dashboard, but crashed browser when load was just about complete. I was able to repeat this without fail.

- Android 2.3: Vorlon test page would not load fully, and never registers as an instance on the dashboard. The browser just spins forever, but no crash.

No errors were thrown on the dashboard side that indicated anything specific. The only error registered was by Logcat: `1402-1402/msft.vorlontest E/libEGL﹕ call to OpenGL ES API with no current context (logged once per thread)`.

**Comment by gleborgne** [comment]
deltakosh has powered Vorlon with Babylon.js overnight ? 😊

**Comment by csuwildcat** [comment]
@gleborgne I was thinking maybe one of the plugins was testing for the presence of something? Maybe Modernizer?

**Comment by csuwildcat** [comment]
@deltakosh @gleborgne wow, I think it might actually be the Modernizer plugin. I pulled it out of the config so it doesn't load that plugin, then ran the page in the Android 4 emulator, and it no longer crashes the browser. The page loading indicator still never stops to show its done, but that may just be the traffic back and forth between the page and the dashboard.

@Carlos487 can you test Android 4 without the Modernizer plugin active and let me know if that changes things?

**Comment by Carlos487** [comment]
@csuwildcat Ok I would try that, but can you give me some pointers on how to deactivate the modernizr plugin. Also I would like to ask if any of the fallbacks that socket.io provides could be used to make it work with Android 2.3 devices, at least at a basic level.

**Comment by meulta** [comment]
Hello @carlos487,

You can deactivate it using the config.json file locate in the Server folder.

If you install via npm, this should be in the vorlon folder in nodes_modules.

**Comment by Carlos487** [comment]
Thanks @meulta, @csuwildcat  I have tried disabling the modernizer plugin, and using vorlon.js with my cordova/application. Indeed it doesn´t crash when starting in Android 4.0.3, the device is shown is the side bar, but when trying to inspect the device, some messages were shown on the Vorlon console and the application crashes after 20-30 seconds, specially when the DOM explorer was used.

    E/CordovaWebViewImpl( 1858): CordovaWebView: TIMEOUT ERROR!

And the messages in console were:

First

> dirty check using html string at http://my_server_ip:1337/vorlon.js/default:3

Second

> No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.

After adding the content security and the whitelist configurations the second message dissapeared, but the first remain and the behavior was the same.

Maybe I would try packaging the Vorlon Test Page in a brand new Cordova App to test a cleaner example.

**Comment by csuwildcat** [comment]
I saw the DOM Explorer going slowly on my end, but not crash. Since it
threw a connection error related to CSP it may be a Cordova config that
needs setting to allow the connection. It may be crashing as a result of
the network connection hanging on CSP.

**Comment by Carlos487** [comment]
@csuwildcat @deltakosh  I'm currently creating a Cordova Test App in [https://github.com/Carlos487/VorlonJS-Cordova-Test-App](https://github.com/Carlos487/VorlonJS-Cordova-Test-App) with the contents from Vorlon Test Page, I hope it will be completed during weekend so we can test those scenarios.

**Comment by Carlos487** [comment]
@csuwildcat @deltakosh The [app](https://github.com/Carlos487/VorlonJS-Cordova-Test-Ap) can be tested now, you need to change the URL to the vorlon script on the file
>www/index.html

to build you need to run **cordova build android** and to deploy to a device use  **cordova run android** on the project root folder.

The app keep crashing on start with the messages

```
08-24 16:12:05.666  13584-13617/com.vorlonjs.cordova.testapp D/﹕ HostConnection::get() New Host Connection established 0x874b710, tid 13617
08-24 16:12:06.016  13584-13598/com.vorlonjs.cordova.testapp A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000040 (code=1)
```

It happens when using the file vorlon.js and vorlon.max.js

**Comment by deltakosh** [comment]
Up?

**Comment by deltakosh** [comment]
Up?

**Comment by csuwildcat** [comment]
I'll pull this down and run it today.

**Comment by csuwildcat** [comment]
@Carlos487 Do you have any instructions on getting your test app running? I tried running the Android project located in "platforms", but it threw build errors. cc/ @deltakosh

**Comment by Carlos487** [comment]
Sure @csuwildcat. It is better to do the following steps on a network without a proxy.

You need a few things:

- Android SDK and it's tools installed and added to the PATH the **tools** and **platform-tools** folders
- The SDK **API 22** of Android 5.1.1 
- **Gradle** installed to compile the android project
- Cordova CLI installed (it has a dependency on Node.JS)

Then it is as easy as going to the root folder of the project, and with the emulator open or device connected run:

>cordova run android

Then the app is automatically deployed.

Which error did you get? Because running the project without the cordova cli wouldn't copy and prepare the necessary files.

cc/ @deltakosh

**Comment by deltakosh** [comment]
Some news?

**Comment by csuwildcat** [comment]
I am trying Carlos' updated instructions.

**Comment by Carlos487** [comment]
I had already sent the detailed instructions in the post above





On Tue, Sep 15, 2015 at 8:17 AM -0700, "Daniel Buchner" <notifications@github.com> wrote:
I am trying Carlos' updated instructions.

On Tue, Sep 15, 2015 at 8:07 AM, David Catuhe <notifications@github.com>
wrote:

> Some news?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MicrosoftDX/Vorlonjs/issues/163#issuecomment-140423336>
> .
>


---

**Comment by csuwildcat** [comment]
Yes, I am trying them out :)

**Comment by Carlos487** [comment]
Nice... tell me if you need any advice or if you get any errors

**Comment by csuwildcat** [comment]
Just got it running, your instructions were very helpful. On my end, your Vorlon Cordova test app loads successfully, but did not connect to the Vorlon Dashboard. I ended up changing the script tag source in the app's index.html page to point at my laptop's own local IP address (192.168.1.109:1337 instead of localhost:1337). When I reloaded the app with the Vorlon script coming from my test machine, the entry appeared in the Vorlon dashboard and everything appears to be working.

Let me know if this helps.

**Comment by Carlos487** [comment]
Did you tried with the 4.0 emulator? Are you using the latest stable or a development build of vorlon?





On Tue, Sep 15, 2015 at 8:57 AM -0700, "Daniel Buchner" <notifications@github.com> wrote:
Just got it running, your instructions were very helpful. On my end, your Vorlon Cordova test app loads successfully, but did not connect to the Vorlon Dashboard. I ended up changing the script tag source in the app's index.html page to point at my laptop's own local IP address (192.168.1.109:1337 instead of localhost:1337). When I reloaded the app with the Vorlon script coming from my test machine, the entry appeared in the Vorlon dashboard and everything appears to be working.

Let me know if this helps.

---

**Comment by csuwildcat** [comment]
I have the latest Vorlon (pulled just before testing) and was using SDK API 22, which is only being permitted to run under an Android 5.x configuration - it seems they are bound to one another. When I deleted the Android 5 runtime, it automatically removes the API 22 option, and the project refuses to start under any Android 4.x option:
```
$ cordova run android
Running command: cmd "/s /c "c:\Users\danie\Desktop\repos\vorlon-cordova-bug-test\platforms\android\cordova\run.bat""
ERROR: Error: Please install Android target: "android-22".

Hint: Open the SDK manager by running: C:\Users\danie\AppData\Local\Android\sdk\tools\android.BAT
You will require:
1. "SDK Platform" for android-22
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)
ERROR running one or more of the platforms: Error: cmd: Command failed with exit code 2
You may not have the required environment or OS to run this project
```

**Comment by Carlos487** [comment]
Not exactly, you can compile an Android app with the latest API level or SDK, but that doesn't mean it with only work on that android version. In my case I'm compiling the app with sdk 22 and deploying it in a Android 4.0 emulator.

In the file **VorlonJS-Cordova-Test-App/platforms/android/AndroidManifest.xml** you can define the property `minSdkVersion` that states which is the minimum supported version, which in this case is 10 (Gingerbread-2.3.6)

In that case you should download the SDK for 22 so the android project can compile.  Which error did you get while trying to compile with SDK 22???

**Comment by csuwildcat** [comment]
Hey @Carlos487, just wanted to update you: I am getting some things set travel tomorrow morning and will be at a work week then out for the weekend. I expect to have time for further testing/debugging of this issue starting next week.

**Comment by Carlos487** [comment]
That's nice @csuwildcat, by that time if you have any issue with the android app or if there is anything I can help, let me know.

**Comment by deltakosh** [comment]
Up?

**Comment by deltakosh** [comment]
This issue is opened from a too long period of time. Please reopen it if required

**Comment by csuwildcat** [comment]
For archival sake: I was not able to replicate this with newer versions of
Vorlon.

**Comment by deltakosh** [comment]
Glad to hear!
