### ISSUE TITLE
Can virlonjs support wild-card dns?

### ISSUE THREAD

**Issue by gerdy** [MicrosoftDX/Vorlonjs#165]
the port 80 of my server is used by apache,can it support wild-card dns?then,I can use 80 for vorlon also.

**Comment by meulta** [comment]
pulling @pierlag

**Comment by deltakosh** [comment]
What do you mean by wild-card dns? like starting vorlon on 0.0.0.0:1337?

**Comment by meulta** [comment]
Any info @gerdy ?

**Comment by meulta** [comment]
Closing this one for now, do not hesitate to open it again with more info @gerdy
