### ISSUE TITLE
Set breakpoints

### ISSUE THREAD

**Issue by tifab** [MicrosoftDX/Vorlonjs#166]
It would be great if we could debug the javascript code by setting breakpoints.

Don't know if it's feasible.

**Comment by meulta** [comment]
Hello ! :)

If you talk about REAL TIME javascript debugging, this is not supported yet as there are no standards to do it correctly. 
Our main focus is to delivered features working for all modern browsers :)

**Comment by DarrylD** [comment]
Is this still the case? Pretty critical to be able to make breakpoints, without it, you're stucking creating tons of console.logs and refreshing.

Maybe take the same approach as https://github.com/node-inspector/node-inspector

I know it's more geared towards webkit, but you need to start somewhere before being on all browsers.

**Comment by deltakosh** [comment]
Yep still the case but we have plan to start supporting it :)
