### ISSUE TITLE
website should be more clear

### ISSUE THREAD

**Issue by matthiasg** [MicrosoftDX/Vorlonjs#167]
saying that vorlon helps debugging is overpromising a little i think. especially since the main panels focus is just the DOM tree and javascript it not supported. 

keep up the work but i would refrain from bold statements such as debugging when it implies javascript debugging across machines (which would be awesome!)...

**Comment by cubitouch** [comment]
What do you mean by "javascript it not supported"?
Using the Console plugin at bottom of the screen, you should be able to run scripts from the dashboard.
There are several plugins to help you debug multiple aspects of your web application : http://vorlonjs.com/plugins/

**Comment by meulta** [comment]
Hello,

Thanks for your feedback ! :)

If you talk about REAL TIME javascript debugging, this is not supported yet as there are no standards to do it correctly. 
Our main focus is to delivered features working for all modern browsers :)

**Comment by matthiasg** [comment]
@meulta thanks for the response. I had hoped vorlonjs would go for the webdriver debugger way since I had one read ie11 sorting webdriver (not quite what I would have wanted of course) or establish a bridge to connect to multiple browsers and try to go for a standard later .. Something that would improve the state of art

Btw I do not accept console.log as a debugging method :) though I am known to use it in a pinch of course
