### ISSUE TITLE
Allow to change the path of log files

### ISSUE THREAD

**Issue by matthieuklotz** [MicrosoftDX/Vorlonjs#169]
Currently, the log files are stored in. /Server.
It might be useful to be able to specify the path and the format of the log file name. An example : in the configuration file : logpath : "/logs/vorlon-{process id}-{day}.log"

**Comment by pierlag** [comment]
yes good idea ! you can implement it on dev branch ?

**Comment by matthieuklotz** [comment]
Hi,
If you agree, I can do that in two steps (i.e : two releases) :
- the first one, I will introduce the choice of the log path and verbosity (DEBUG, INFO, etc...)
- In a second step, I can do the log file name format. I'm more a C# developer than a javascript one, so I need to do a some research before doing it with the more extensible and the best way .

**Comment by meulta** [comment]
Go :)

**Comment by meulta** [comment]
Well done
