### ISSUE TITLE
Deploy to azure with SSL

### ISSUE THREAD

**Issue by reikz** [MicrosoftDX/Vorlonjs#171]
Hi,

Im trying to create a vorlonjs server on azure. Im using deploy to azure feature on this page.
On localhost its running fine with npm installation, but on azure i cant make it work with SSL. I can acess the vorlon server url with both http/https.

If i set the include script of vorlon on my application, which is served via https, i get the following error.

Mixed Content: The page at 'url here..' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'vorlon server url/socket.io/?EIO=3&transport=polling&t=1437490149028-5'. This request has been blocked; the content must be served over HTTPS

If i try to set the "useSSL" to true on the json.config nothing changes. And restarting the azure web app stops from running vorlonjs. Trying to acess the port 1337 has no effect with true/false "useSSL" setting.

My bet is that on the link "..azurewebsites.net/vorlon.js/default" the parameter "this.loadingDirectory" is serving my server with http reference instead of a secure one.

Anyone stumbled on the same problem?

**Comment by kanoshin** [comment]
+1

**Comment by pierlag** [comment]
On azure nothing to do. Just used button "Deploy Azure" in Readme and after juste change http to https

**Comment by timdp** [comment]
I tried this and the WebSocket still attempted to connect over regular HTTP.

**Comment by reikz** [comment]
I did everything they recommend. Had to stop using vorlon because of this. Sadly.

**Comment by kanoshin** [comment]
You can use dedicated server to setup vorlon with SSL. This worked for me.

**Comment by timdp** [comment]
I'm now trying to deploy to Elastic Beanstalk. Worked fine, but I ran into the same issue. As a workaround, I thought I'd replace `"http"` with `"https"` in `vorlon.httpconfig.ts`, but there must be a better way.

**Comment by jdrew1303** [comment]
Hey @pierlag 

Just thought that this issue should be reopened. Websockets is still going over http and not working. (Im using this on Autodesk Revit, Google Sheets add-ons and in Microsoft Office Excel Add-ons [ipad, mac, online and windows]). Ive changed the config file and specified that https should be used (and loaded the script over https) but Im getting this: 

![image](https://cloud.githubusercontent.com/assets/2535432/14711202/5e6aac34-07d0-11e6-9905-50dc768fb848.png)

I've followed @timdp hack and Im still getting the same issue. Any ideas? Ive change the config also to no avail.
