### ISSUE TITLE
Client side error - Device Plugin

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#172]
When I start client side part (on http://stackoverflow.com/ for that matter), I get a JS error:
`Uncaught TypeError: Cannot read property 'outerHTML' of null`

![image](https://cloud.githubusercontent.com/assets/7486151/8821403/a4bed598-305d-11e5-959e-ea51f0fdbf0a.png)

I just refreshed my VorlonJS directory from the dev-0.0.16 branch.

I think this happen because the viewport meta tag is not present in the page.

**Comment by meulta** [comment]
Yep thank,
will fix it right away :)

**Comment by meulta** [comment]
Should be good
