### ISSUE TITLE
Unable to connect remotely from other devices + Vorlon

### ISSUE THREAD

**Issue by naresh217** [MicrosoftDX/Vorlonjs#177]
Vorlon dashboard is not showing all connected devices. I have desktop and installed a Vorlon, I am using localhost of this desktop from laptop or ipad its displays webpage but it is not showing devices in vorlon, but it show if i open from the same desktop.

**Comment by naresh217** [comment]
I have tried opening your sample page http://cdn.rawgit.com/MicrosoftDX/Vorlonjs/master/Plugins/samples/index.html

It is showing in Client list if I open above url where vorlon server is running. 
If I run above url from different computer or mobile it is not working

**Comment by meulta** [comment]
Are you trying to reach the server using localhost ? Cause that obviously will not work :)

**Comment by naresh217** [comment]
Nope. I have tried both using IP address and system name.

**Comment by naresh217** [comment]
My bad. Had wrong port number in other machine. It is working now. 
And can we access styles for Native app developed using HTML5 and CSS3 ?

**Comment by meulta** [comment]
Yep, that works :-)

**Comment by naresh217** [comment]
From the documentation i can see this will support for only web browsers. This is excellent so far. 
If we have an option to debug native apps would be great. 

Thanks
