### ISSUE TITLE
Dashboard "welcome page" always display localhost:1337 as hostname for referencing vorlonjs javascript

### ISSUE THREAD

**Issue by matthieuklotz** [MicrosoftDX/Vorlonjs#178]
Hi,

The Uri 'http://localhost:1337/vorlon.js' is currently hard coded in the view "dashbord-plugins".
It could be usefull to display the real hostname in the URI, based on the machine name, or to enable setting the hostname by configuration (in case of an azure website or a docker container).

**Comment by meulta** [comment]
Hello,

Actually, it is "hardcoded" in the view but changed dynamically using the url used to access the dashboard.

Do you still think we need to change something?
