### ISSUE TITLE
Can install VorlonJS due to logger dependency

### ISSUE THREAD

**Issue by ghoullier** [MicrosoftDX/Vorlonjs#179]
Hi!

There as undefined dependency in [package.json](https://github.com/MicrosoftDX/Vorlonjs/blob/master/package.json#L16)
https://www.npmjs.com/package/logger return a 404

It seems the dependency has been deleted.

**Comment by meulta** [comment]
Hello,

It works on my side. Sometimes npm repos goes down for a few minutes.
Can you try back please?

**Comment by ghoullier** [comment]
Have you tried to remove your node_modules folder and relaunch npm install?

**Comment by ghoullier** [comment]
I still reproduced the problem on my side, https://www.npmjs.com/package/logger seems no longer defined.
