### ISSUE TITLE
Proposal: load plugin panels in <object> viewports

### ISSUE THREAD

**Issue by csuwildcat** [MicrosoftDX/Vorlonjs#18]
In playing with the dashboard and thinking about the render of plugins, I would like to submit for consideration the idea of instantiating plugins inside their own light text/html document within an `<object>` element. This would provide the following for plugin authors:

- Encapsulation for styles and script
- Media queries scoped to the size of the panel's container, not the entire parent window
- Would make development and packaging of a plugin even easier

Note: code within a light document inside an `<object>` element still has access to the parent frame and v. v., so we can still do any necessary cross document manipulation without worrying about cross domain issues.

**Comment by csuwildcat** [comment]
I guess this brings up the question of plugin security - is that something we need to account for/care about in Vorlon? The answer could be NO if we don't think it matters for the local machine user flow, but probably should be accounted for if we decide to pursue a hosted version.

**Comment by matthiasg** [comment]
Well css separation is a nice benefit in the absence of web components but do all targeted browsers support this object behavior ?

**Comment by csuwildcat** [comment]
@matthiasg the ability to load a lite document viewport in object elements via a data url source is well supported back to at least IE10 (probably 9 as well, just need to double check). However, @deltakosh informs me that securitization of this type is not something we need to worry about for plugins. As you stated, it would be nice to have the CSS contained so errant styles don't leak from one component to the rest of the app and plugins. Containing plugins this way would require a bit of work, and potentially changes to how plugins are done, which is something we should consider if we ever decided to pursue a change like this.

**Comment by matthiasg** [comment]
It isn't high priority I concur.. There are more interesting things to pursue

**Comment by csuwildcat** [comment]
Closing, wontfix
