### ISSUE TITLE
IOS unable to work

### ISSUE THREAD

**Issue by kanoshin** [MicrosoftDX/Vorlonjs#181]
Have you got any known issues connecting vorlon to Chrome/Safari on IOS?

Vorlon script successfully loads (from https with valid cert), but then communication fails:
![2015-08-07 12-59-16](https://cloud.githubusercontent.com/assets/11817360/9131362/35425ca4-3d04-11e5-8db2-352894f51c5b.png)
![2015-08-07 12-58-54](https://cloud.githubusercontent.com/assets/11817360/9131363/3545eb4e-3d04-11e5-9a5b-8f0996b17a90.png)

Device:
IPad IOS 8.4
Chrome 44.0.2403.67

**Comment by kanoshin** [comment]
Somehow it works when I use http locally. But i can't use http on production site.

**Comment by deltakosh** [comment]
Can you try with xhr plugin turned off?

**Comment by deltakosh** [comment]
Pulling @gleborgne in as I think he is the only one in the team to have an iPad:)

**Comment by gleborgne** [comment]
at work but not at home :p

**Comment by meulta** [comment]
Hey @gleborgne did you manage to test This ?

**Comment by meulta** [comment]
Pulling @alexfrih

**Comment by kanoshin** [comment]
Hi, it seems vorlon works stable after I disabled xhr plugin.

**Comment by deltakosh** [comment]
Interesting :)

**Comment by meulta** [comment]
@alexfrih will work on this starting next week :)

**Comment by alexfrih** [comment]
Hi,
do you still have this problem ? If yes can you send me your exact configuration (maybe with your files/website) to try to force the bug happen again.

Because on iOS 8.4.1 (iPad and iPhone) it works for me (Safari and Chrome).

Thank you.

**Comment by meulta** [comment]
Any more info @alexfrih ? @kanoshin ?

**Comment by kanoshin** [comment]
@meulta @alexfrih I've rechecked again with xhr plugin turned on, and it is working. Not sure what was the problem before. Thanks for you help.

**Comment by meulta** [comment]
Ok perfect, thanks
