### ISSUE TITLE
Chrome page freezes with huge SPA

### ISSUE THREAD

**Issue by stein189** [MicrosoftDX/Vorlonjs#182]
We are using a huge single page application which includes several Javascript libraries such as Backbone, jQuery, Marionette, Underscore and some others.

When I attempt to load the client from the Vorlon dashboard the clients webpage freezes for a couple of minutes before I am able to see the data.

This problem only occurs in Chrome, in Firefox it works like a charm.
I tested it in Chrome V40, V43 and V44 but all these seem to have the exact same problem. 
I tested it local and on our network and both have the same problem.

When I remove the libraries and the other 100+ Javascript files it also works in Chrome.

I am using Linux Mint.

**Comment by deltakosh** [comment]
Do you have by chance a way to share a sample client page?

**Comment by stein189** [comment]
I am not able to share the source and its not online yet but I will try to reproduce it with similar libraries.

**Comment by deltakosh** [comment]
Thank you so much!

**Comment by stein189** [comment]
I couldnt reproduce the problem with a new project as it has to do with the DOM and it takes alot of work to reproduce it, however I managed to put the vorlon dashboard on my server but I don't know if it is usefull for you to look at.

**Comment by stein189** [comment]
When we ran Vorlon on the test server in prod environment it works well in chrome, instead of waiting a couple minutes it just takes a couple of seconds. 

So my conclusion is that if there is a lot data its a little slowly in chrome, but I think that problem has more to do with chrome then Vorlon.

Anyway thank you for your time!
