### ISSUE TITLE
Feature request: inspect elements directly from webpage

### ISSUE THREAD

**Issue by sjoerd222888** [MicrosoftDX/Vorlonjs#183]
With the Chrome Dev tools you can right click on an element in the browser and select "Inspect Element". 

Something similar for vorlon.js would be nice. Though it might be not straight forward to implement this. Create a custom context menu is not always possible and it does also not work on mobile/touch devices. Maybe a special mode can be toggled (in the vorlon.js gui) such that gui elements can be selected. But maybe that is not elegant, applications should be mode-less (as Larry Tesler would put it). Maybe you guys have some ideas.

And I think this feature would be interesting to be in the core rather than have it as plug-in.

**Comment by deltakosh** [comment]
I think this is a good idea but we still need to figure out details. I mark this one as "future version" as we are closing the current 0.0.16

**Comment by deltakosh** [comment]
After discussing with the team, it appears that it is a feature we do not want to implement as we do not want to be too intrusive in the client UI :(

**Comment by sjoerd222888** [comment]
Hmm....
At least it would be interesting to have the possibility to be intrusive if I want it. So if I want to debug my application and can choose to do it with vorlon. It is not the general case but very specefic for this debuging session. What would be nice would be to have an API that I can use so that I could call from my javascript code to call vorlon such that this element is the also selected in the vorlon tree. In this case it would not be intrusive at all. What are your thoughts on this suggestion?

**Comment by deltakosh** [comment]
Definitely a good idea..do you mind opening a new issue?

**Comment by gleborgne** [comment]
One thing I have in mind is to have a picker within Dom explorer like what you have in dev Tools (click on the pick button and then in your ui to select an element). Would that suit your needs ?

**Comment by sjoerd222888** [comment]
Created a new issue: https://github.com/MicrosoftDX/Vorlonjs/issues/190

so lets continue the discussion there.
