### ISSUE TITLE
How to Remote Debug a client build?

### ISSUE THREAD

**Issue by pebanfield** [MicrosoftDX/Vorlonjs#186]
Hi - I've poured over the documentation and have not found how to configure vorlon to work with a remote client build. The documentation instructs adding the following script tag to the client build; 

```<script src="http://localhost:1337/vorlon.js"></script>```

This works fine when the client build is hosted on my development machine. So far so good. However, when I try to change the host to point at a network ip or domain so that I can debug a LAN device (in this case a smart tv) it does not work. 

For example - 
```<script src="http://my.local.dev.server:1337/vorlon.js"></script>```

Looking a little closer at the rendered vorlon.js I see the following line of code - 

this.loadingDirectory="http://localhost:3000/vorlon/plugins"

If this code is intended to be executed on my target device - I fail to see how this would ever work for remote debugging outside of the context of running the client on the same machine that is hosting the vorlon server? Is there some configuration option I am missing? Have you tested this use case? The vorlon documentation seems to explain this as a primary use case so I am somewhat confused. 

Thanks!

Peter

**Comment by pebanfield** [comment]
Ok so I noticed that the vorlon client script queries the window.location.host to derive the host so that makes sense now. Otherwise, I might just be partly not fully understanding the sockets design. My current guess is that the websockets implementation expects to be running on the same host. Perhaps this is configurable or perhaps this limitation is by design for security reasons?

**Comment by deltakosh** [comment]
Hey!

Client and server can be on different computers as long as the client can reach the server. 

once deployed, you just need your server url and then use it as script source in your client like you mentioned before ( <script src="http://my.local.dev.server:1337/vorlon.js"></script> )

The only constraint here is to make sure that the client can reach the server (check firewall and so on)

**Comment by pebanfield** [comment]
I've tried various configurations, but I'm still unable to achieve this. I think the problem may be due to security restrictions on the device.

**Comment by deltakosh** [comment]
Arg :( I assume you do not see any connection in your dashboard then?

**Comment by pebanfield** [comment]
So I did finally manage to get it working. It was related to cross domain restrictions on the device. My solution was to use a client direct to load my hosted site where vorlon was running on another port. I'm not sure if this is a requirement or just specific to my set up. I'm running a dns proxy, etc. 

Unfortunately, I'm now running into perf issues on the device. Thanks for the help though.

**Comment by deltakosh** [comment]
Please keep us posted of any progress
