### ISSUE TITLE
Developping plugins accross multiple files

### ISSUE THREAD

**Issue by TheFrenchieCake** [MicrosoftDX/Vorlonjs#187]
Hello, VorlonJS team,

I'm currently working on a plugin for VorlonJS, and as my development goes on, the number of classes/subclasses and therefore the amount of lines in the vorlon.myPlugin.dashboard.ts and vorlon.myPlugin.client.ts lines becomes too big to handle easily. I tried to split my classes into several files, as so:

- vorlon.myPlugin.interfaces.ts
- vorlon.myPlugin.dashboard.ts
- vorlon.myPlugin.client.ts
- vorlon.myPlugin.DataTreeGenerator.ts
- vorlon.myPlugin.DataGenerator.ts
- vorlon.myPlugin.Query.ts
- vorlon.myPlugin.TreeNodeHTMLElement.ts

Inside of these files you can find, for example:

Inside vorlon.myPlugin.DataTreeGenerator.ts:

    module VORLON {
        export class DataTreeGenerator {
            // members, constructor and functions...
        }

        export class DataTreeGeneratorSubClass extends DataTreeGenerator {
            // members, constructor and functions...
        }
    }

Inside of the dashboard file:

    // reference to the internal module:
    /// <reference path="vorlon.myPlugin.DataTreeGenerator.ts"/>
    module VORLON {
        export class myPluginDashboard extends DashboardPlugin {
            // members, constructor and functions...
        }
    }

But when I try to start my Vorlon server with my custom plugin enabled, it seems that it doesn't compile as it should, meaning it doesn't take my classes files; for example, when I launch the server with `npm start`, the first error throwed by the dashboard side is when it encounters the compiled version of typescript code `this._dataTreeGenerator = new DataTreeGenerator(...);`:

    Uncaught TypeError: VORLON.DataTreeGenerator is not a function

I tried to manipulate the Plugins/gulpfile.js, in attempt to make it compile the files of my classes along with my dashboard TS file, but without success. I'm far from being an expert in Gulp, so it might just be my fault if I didn't get any good result.

Is there any documentation about how to develop a Vorlon plugin accross multiples files? I suppose I could develop in another folder, create a gulp script that compiles my files into the dashboard and client TS files, then move it to the correct folder... But that wouldn't be very practical :-/

**Comment by gleborgne** [comment]
Vorlon expect the plugin to be one file for client and one for Dashboard. You should use gulp to bundle your files into one single javascript file for each

**Comment by TheFrenchieCake** [comment]
That's what I feared... Well, 'guess a nice addition to VorlonJS would be some script + documentation to compile plugins developped accross multiple files into single-page script for client and dashboard ;-) I'll surely work on this ASAP, in order to be able to work on my Vorlon plugin again ;-)

**Comment by deltakosh** [comment]
You can easily copy/paste code from gulpfile.js to merge your files. it is a matter of less than 10 lines of code:)

**Comment by TheFrenchieCake** [comment]
I've banged my head against the walls and gulp for three days straight, and the gulp compilation, even with pre-bundle work of the different files, doesn't work. It may be my fault, may be not, but in every case I couldn't advance further on my plugin. So, I had no choice but to come back to a single-file format for my dashboard and client files.

There is an other problem, now, though. I implemented an enum in my vorlon.myPlugin.interfaces.ts file, but when I run the VorlonJS server on my computer and try to run it on my browser (Chrome, if that matters), it throws errors on my face, saying my enum is undefined. I cloned a clean version of VorlonJS, without my manipulation/attempts to make things work with different files, and implemented my plugin (with a version which was already one-file formatted). Tried to run it, and now it doesn't work anymore, saying my enum is undefined.

I suspected that, like for dashboard and client files, Vorlon expects for one plugin a single file named vorlon.myPlugin.interfaces.ts, but maybe am I wrong? What would be the correct syntax for an "interfaces" file which contains several enum/interface that are needed both by the client and the dashboard side?

**Comment by deltakosh** [comment]
Let's keep things in order :)
First of all, can you share your gulp task and files? We will find a way to help you merge everything in one single file

Then, about the plugin: as long as the server and the client are both generated using this enum, you must find it inside both file (server.js and client.js)

But as I mentioned before, let's fix your multiple files issues first :) I suggest that you should create a GitHub repo with your .ts and the gulp file and we could then be able to help you fixing it

**Comment by gleborgne** [comment]
You could also make a fork of Vorlon, add your plugin and send us the github url for your fork. We may be able to have a look in context

**Comment by Temechon** [comment]
Hello, 
I work with @TheFrenchieCake on this plugin. You can find our fork here: https://github.com/Temechon/Vorlonjs

As you can see, I add to update the [plugin gulpfile](https://github.com/Temechon/Vorlonjs/blob/master/Plugins/gulpfile.js) to concat client.js with interfaces.js (same for dashboard).

Can you help us please ?

**Comment by deltakosh** [comment]
Hello what are you expecting from us? I see that your concat code is already working so do you still need help? :)

**Comment by Temechon** [comment]
Our questions were more about the 'best practices', but if it's validated from Vorlon dev team, we can create a PR :)

**Comment by deltakosh** [comment]
My only ask would be to create a separate tasks for plugins who need extra works like yours
