### ISSUE TITLE
Vorlon Perf Requirements?

### ISSUE THREAD

**Issue by pebanfield** [MicrosoftDX/Vorlonjs#188]
Hi - My smart tv app is crashing when I run it with vorlon. It appears that the embedded webkit browser is simply running out of memory. My guess is that all the dom inspection going on is just too much overhead. Is there a way to turn off some of the features to confirm this? Thanks. 

Peter

**Comment by deltakosh** [comment]
Sure there is :) just go to https://github.com/MicrosoftDX/Vorlonjs/blob/master/Server/config.json and disable what you don't need

**Comment by pebanfield** [comment]
Hay cool thanks. I will try that.
