### ISSUE TITLE
Question : How to use Vorlon on an "online" page ?

### ISSUE THREAD

**Issue by mh-nichts** [MicrosoftDX/Vorlonjs#189]
First of all, thanks for the work !

I'm sorry if my question might sound a bit stupid, but from what I understand, I can only use Vorlon to debug a local website (with a local dashboard) ?
It seems logical to me that an online website can't have access to my localhost, so how can I use it in this context ?

I would say that I have to install the Vorlon script and dashboard on the website server : for the javascript I can well see how to put it on the website server, but I don't find in the documentation any hint on how to have an "online" dashboard.
(I guess it's possible, as I've seen the demo at the KiwiParty)

Thanks in advance for your explanations !

**Comment by deltakosh** [comment]
Hello:)
You can deploy the server to any azure subscription by using the deploy to Azure button that you can find in the readme.md

But if you have any web server which can handle node.js, just deploy the /Server folder and run node on server.js

From your client page, you just have to reference http://myserver.com:1337/vorlon.js and you're done :)

**Comment by mh-nichts** [comment]
Thank you for the quick answer !
I will see what I can do with these 2 possibilities.

**Comment by meulta** [comment]
Did you manage do what you want ? :)

**Comment by meulta** [comment]
I am closing this for now, do not hesitate to open it again if needed ! :)

**Comment by nico3333fr** [comment]
Hi,

I would like to know how you deploy to Azure, do you have a simple tutorial for this ?

See ya,
Nico

**Comment by deltakosh** [comment]
Here is it:) http://blogs.msdn.com/b/emargraff/archive/2015/09/17/how-to-deploy-an-online-vorlon-js-server-with-authentication.aspx

**Comment by nico3333fr** [comment]
![bisou](https://cloud.githubusercontent.com/assets/2578321/10543751/fa9046b8-741f-11e5-97cb-136c22e92d59.gif)

Thanks, I will test it this week-end :)

**Comment by nico3333fr** [comment]
I got an error 403 : Error 403 - This web app is stopped. (I tried to log in with a @live.fr account)

Any idea ?
