### ISSUE TITLE
Feature request: Support plug-ins  without rebuilding vorlon

### ISSUE THREAD

**Issue by sjoerd222888** [MicrosoftDX/Vorlonjs#193]
Currently plug-ins have to be tightly built into vorlon. It would be nice if plug-ins can be separate and installed into a vorlon server without rebuilding all of it.

(At the end it would be really nice if there is a gui for this similar to Chrome Applications where you can install additional plug-ins. But let's start with something simple)

**Comment by meulta** [comment]
in which case do you need to rebuild all ?
You just have to copy / paste the plugin js files into the server/public/vorlon/plugins folder.
Tell me if you need help with that.

**Comment by meulta** [comment]
Reopen if you have more info :)
