### ISSUE TITLE
Socket.io polling unstable

### ISSUE THREAD

**Issue by meulta** [MicrosoftDX/Vorlonjs#194]
When socket.io is fallbacking on xhr poll request the server is unstable.

**Comment by meulta** [comment]
Issue happens when socket.io connection are limited
If you are on Azure, you need to change your Web app plan (standard is WebSocket connection unlimited)

**Comment by deltakosh** [comment]
We still need to update the documentation

**Comment by meulta** [comment]
Yep ;)
