### ISSUE TITLE
OSX : Command not found

### ISSUE THREAD

**Issue by isyara** [MicrosoftDX/Vorlonjs#198]
Hi,

I'm under OSX Yosemite (v 10.10.5)  and i'm using iTerm 2.

After **sudo npm i -g vorlon**  and run command **vorlon** , i have :

````
bash: vorlon: command not found
````

An idea ?

**Comment by meulta** [comment]
Hello,

Did you get the install log from the npm command?

**Comment by meulta** [comment]
Hello :) More info ?

**Comment by isyara** [comment]
How get log from vorlon install ?

**Comment by pierlag** [comment]
For exemple : http://localhost:1337/logs

**Comment by meulta** [comment]
Hello isyara
Any new on this ?

**Comment by isyara** [comment]
I re-install and i don't have error :

![screenshot](https://cloud.githubusercontent.com/assets/2648791/10312664/726e78a2-6c4c-11e5-8629-c1c9a8f54dc4.png)

Need more information ?

**Comment by isyara** [comment]
Hi,

I have updated nodejs and npm ,and it works  ;-)
