### ISSUE TITLE
Doc unclear when getting from the repo

### ISSUE THREAD

**Issue by deltakosh** [MicrosoftDX/Vorlonjs#2]
If I get everything from the repo, how should I launch the server? We need as well to provide a better description of the folders structure

**Comment by deltakosh** [comment]
As a web developer using Vorlon.js, I have to clone hte repo, go to /server and do npm install, then go to /plugin and do the same.

**Comment by bear** [comment]
@latentflip can work on this now that the repo has a "real" root directory.

will we be able to push changes to this repo soon?

**Comment by latentflip** [comment]
If you just run npm install, npm start from root it works, you don't have to do anything else. I can clarify that though yes.

**Comment by latentflip** [comment]
I think someone from Microsoft should explain the folder structure though as they are more familiar with it than me.

**Comment by deltakosh** [comment]
You can push to this repo already
I'll do the folder structure desc.

**Comment by deltakosh** [comment]
Just let me know where to put the description

**Comment by latentflip** [comment]
@deltakosh here's a section where you can expand the description of the structure here https://github.com/MicrosoftDX/Vorlonjs/tree/master#developing-on-vorlonjs
