### ISSUE TITLE
Port flag

### ISSUE THREAD

**Issue by Auine** [MicrosoftDX/Vorlonjs#21]
Why i can run it only on 1337? lol really why? How i can to start it on any other port?

**Comment by Auine** [comment]
Ok, 
sudo PORT=[port] vorlon

**Comment by deltakosh** [comment]
Actually you can change it:
https://github.com/MicrosoftDX/Vorlonjs/blob/master/Server/Scripts/vorlon.webServer.ts#L53

**Comment by engincancan** [comment]
Yes, We [can](http://stackoverflow.com/a/13333312/2007333) with;
unix shell:
```sh
$ PORT=1234
```

More permanently:
```shell
$ export PORT=1234
```
In Windows:
```shell
set PORT=1234
```

In Windows PowerShell:
```shell
$ env:PORT=1234
```
However it will be great if there is an optional parameter to vorlon like,
```shell
$ vorlon --port=1234
```

**Comment by Auine** [comment]
Yes, parameter will be great
