### ISSUE TITLE
Update documentation for plugins writers

### ISSUE THREAD

**Issue by deltakosh** [MicrosoftDX/Vorlonjs#210]

**Comment by gleborgne** [comment]
documentation should insist on being very carefull with plugin startup and bootstrap on the clientside, especially for plugins related to specific tools (angular, babylon, qunit). 
I Get many errors from those plugins, mostly because targeted lib is not present in the client.

**Comment by deltakosh** [comment]
Agree.. do you mind point out some of them? Or even better trying to fix them?

**Comment by gleborgne** [comment]
We stabilize web proxy and will fix them on the fly

**Comment by deltakosh** [comment]
Thanks I appreciate!

**Comment by deltakosh** [comment]
Clsoing this as it will never happen
