### ISSUE TITLE
WebSocket connection to 'ws://./' failed

### ISSUE THREAD

**Issue by Auine** [MicrosoftDX/Vorlonjs#22]
WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

**Comment by Auine** [comment]
all in style of ms devs, bugs, laggs, and all made through ass. I spend half an hour to just test it, and it's doesn't even work

**Comment by pierlag** [comment]
What is your dev environement ? Server side (php, nodejs, ?) and client side (Angular, IE, Chrome, Firefox) ?
Thanks

**Comment by Auine** [comment]
ubuntu, nodejs(volonjs) 
chrome, simple test page that was provided at website. I just changed port 1337 to 91.
 Somehow ws is pending, but nothing are logging to server, and modernizr throws that error

**Comment by pierlag** [comment]
If you change the port you need to change the script reference web site side like : http://localhost:91/vorlon.js

**Comment by Auine** [comment]
of course, i did

**Comment by pierlag** [comment]
all run on the same machine ?

**Comment by Auine** [comment]
are you trolling me?) Yes, the same

**Comment by pierlag** [comment]
I'm trying to understand why the connection between client and server not working. Vorlon.js based on socket.io so they are nothing specific. You give not enough information to help you to debug sorry
