### ISSUE TITLE
Integrate vorlon into an application test suite

### ISSUE THREAD

**Issue by achaussier** [MicrosoftDX/Vorlonjs#224]
Hello,
Thanks for this amazing project, it's very interesting and opens many use cases.

I think it should be useful to have an API or another system to integrate vorlon into an application test suite.
With this system, we can get more informations when a test fail for example.

**Comment by gleborgne** [comment]
Could you expand on what you would like a little bit ?

**Comment by achaussier** [comment]
I'll write a use case to explain my thoughts.

  1. At the beginning of end to end test suite, link the app to vorlon
  2. If a test fail It should be useful to have some vorlon api actions which can be launched :
  - Dump the dom,
  - Execute console command,
  - Dump the console output,
  - ...

But to do this, we need to interact with vorlon with an api to do actions, get session identifier, ... from the test manager.

And it should be a good thing to reset only a session, not the entire dashboard (between each test perhaps).

Is it more clear ?

**Comment by gleborgne** [comment]
For your use-case, your end to end runner (selenium/webdriver ?) probably already do what you're asking.

Adding an API for that is possible in Vorlon but a little more complicated than that (you also need to identify your client, not just the session, manage authentication in the api, ...)

We will discuss it with the team

**Comment by deltakosh** [comment]
Hello starting with 0.2, vorlon.js is now requirable and can be used within for instance a node.js project.
Regarding your ask, we do not plan to support dashboard-less approach :(
