### ISSUE TITLE
"ActivateAuth" not Working

### ISSUE THREAD

**Issue by maxklock** [MicrosoftDX/Vorlonjs#225]
I have installed VorlonJs with Docker on my Ubuntu-Server and tried to protect it with "activateAuth" but it doesn't work. Here my config.json

{
    "includeSocketIO": true,
    "useSSL": false,
    "SSLkey": "cert/server.key",
    "SSLcert": "cert/server.crt",
    "activateAuth": true,
    "username": "vorlon",
    "password": "vorlon",
    "plugins": [
        { "id": "CONSOLE", "name": "Interactive Console", "panel": "bottom", "foldername" : "interactiveConsole", "enabled": true},
        { "id": "DOM", "name": "Dom Explorer", "panel": "top", "foldername" : "domExplorer", "enabled": true },
        { "id": "MODERNIZR", "name": "Modernizr","panel": "bottom", "foldername" : "modernizrReport", "enabled": true },
        { "id" : "OBJEXPLORER", "name" : "Obj. Explorer","panel": "top", "foldername" : "objectExplorer", "enabled": true },
        { "id" : "XHRPANEL", "name" : "XHR","panel": "top", "foldername" : "xhrPanel", "enabled": true  },
        { "id" : "NGINSPECTOR", "name" : "ngInspector","panel": "top", "foldername" : "ngInspector", "enabled": false  }
    ]
}

**Comment by matthieuklotz** [comment]
Did you make your own container based on the development-0.0.16 branch, or do you use [the existing container on the docker hub](https://hub.docker.com/r/matthieuklotz/vorlonjs/).
The container that I have released on the docker hub is based on the latest stable release on npm (0.0.15) that does not support authentication.

**Comment by maxklock** [comment]
I created my own Container:

FROM ubuntu:14.04
RUN apt-get update && apt-get install -y curl
RUN curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash -
RUN apt-get install -y build-essential nodejs python make
RUN npm i -g socket.io
RUN npm i -g vorlon

[...]

Where I have to change to the development-0.0.16 branch?

**Comment by meulta** [comment]
Hello,

If i understand it well, you are getting the npm package. This will give you the 0.0.15 version which does not contain authentication (and many other features).

The 0.0.16 will be out soon in NPM.

To get the 0.0.16 (dev) branch you can run :
git clone https://github.com/microsoftdx/vorlonjs
(go in the vorlonjs repository)
git checkout development-0.0.16
npm install
npm run

Tell me if that was helpful :)

**Comment by matthieuklotz** [comment]
Hi @maxklock ,

Sorry for my late reply. @meulta describes you the only way to do a docker container with the dev branch. After the "npm install" command, you should make a dockerfile that will copy all your local content to your container (you could remove all .d.ts or .ts files).
It's currently what I do for testing VorlonJS 0.0.16 on my docker container :)

**Comment by maxklock** [comment]
Thank you! I've tried it with git clone and checkout, but there was always an error because of npm dependencies. But i didn't now, there is an "npm install"! Now it's working fine!
The Dockerfile:

FROM ubuntu:14.04
RUN apt-get update && apt-get install -y curl
RUN curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash -
RUN apt-get install -y build-essential nodejs python make
RUN apt-get install -y git
RUN npm i -g socket.io
RUN git clone https://github.com/MicrosoftDX/Vorlonjs.git /usr/lib/node_modules/Vorlonjs
WORKDIR /usr/lib/node_modules/Vorlonjs
RUN git checkout development-0.0.16
RUN npm install
RUN npm run build
[... Expose, Copy, Cmd ...]

**Comment by meulta** [comment]
Great news!
