### ISSUE TITLE
Search in object explorer generates an error

### ISSUE THREAD

**Issue by meulta** [MicrosoftDX/Vorlonjs#229]
"not found"

**Comment by lahloumehdi** [comment]
I am not able to reproduce this issue. Can you @meulta give me a sample or steps to reproduce it with the vorlon sample :) ?

**Comment by meulta** [comment]
It is when I am searching something that does not exist in the DOM.

**Comment by lahloumehdi** [comment]
Obviously :) , I'll fix that. Thanks
Le 7 oct. 2015 18:50, "Etienne Margraff" <notifications@github.com> a
écrit :

**Comment by meulta** [comment]
Hey I still have the issue here :)
Can you test on your side?
