### ISSUE TITLE
Multi-tennancy

### ISSUE THREAD

**Issue by ggoodman** [MicrosoftDX/Vorlonjs#23]
Hello, awesome project.

I built and run Plunker (http://plnkr.co/edit/) and think that giving users the ability to automatically inject Vorlon into running previews would be very compelling.

To require each user to be running their own Vorlon server would go against the idea of frictionless creation in Plunker.

Can Vorlon be configured for mutli-tennancy (this might be the wrong term)?

Cheers,

Geoff

**Comment by pierlag** [comment]
Vorlon.js (dashboard) is mono-tennancy but you can used "session" to have multi-session on the same server:
- client side : <script src="http://localhost:1337/vorlon.js/session2"></script>
- dashboard : http://localhost:1337/dashboard/session2
