### ISSUE TITLE
Add missing CSS to babylon plugin

### ISSUE THREAD

**Issue by meulta** [MicrosoftDX/Vorlonjs#231]
pulling @temechon

**Comment by meulta** [comment]
Any new @Temechon ? I think you just forgot to commit your css file ;)

**Comment by Temechon** [comment]
I can't for the life of me find where css files are ignored in .gitignore. I tried to update the main gitignore to commit the css file but failed pathetically.
Css in now inlined in the HTML file. PR done on dev branch.

**Comment by housemeow** [comment]
after npm install vorlon, run server and see no css style
Am I facing the same problem?
http://imgur.com/On7kkjC

**Comment by meulta** [comment]
@housemeow did you install it via npm on mac ?
if so you need to run it using **sudo vorlon**

**Comment by meulta** [comment]
fixed

**Comment by housemeow** [comment]
thanks! when i add sudo then it's works!
