### ISSUE TITLE
Inject into BABYLON.Engine constructor prototype rather than asking for a global object

### ISSUE THREAD

**Issue by davrous** [MicrosoftDX/Vorlonjs#233]
@Temechon

In current BABYLON.JS plugin, the doc says you need to assign the engine to the global window.engine object.

It would be MUCH better to rather inject your code into the BABYLON.Engine constructor to avoid doing that. You could do the same thing also when a scene is created to notify the dashboard rather than statically scanning the scenes on startup.

**Comment by Temechon** [comment]
Indeed :) I'll update it with your advices.

**Comment by davrous** [comment]
Hi @Temechon , did you manage to find time to review this architecture change?

**Comment by deltakosh** [comment]
Hello @Temechon, some news?

**Comment by meulta** [comment]
Moved
