### ISSUE TITLE
Doesn't work for 4.2.2 Android webview

### ISSUE THREAD

**Issue by 20cents** [MicrosoftDX/Vorlonjs#236]
It doesn't work for 4.2.2 Android webview but it works in the browser.
The test was made in a Cordova app.
The app crash about 15s after launch.
An alert display something like: Unsuccessful server connection

It works on Android 5

**Comment by meulta** [comment]
Hey,

Can you provide us the app code ?
Or do you have a simple way to reproduce that ?
Is it happenning on an emulator ? A physical device?

Thanks

**Comment by 20cents** [comment]
Hello,

A way to reproduce that: (simple if you have the Android SDK yet installed!)
$ npm install -g cordova
$ cordova create MyApp
$ cd MyApp
$ cordova platform add android
Plug an Android 4.2.2 on your computer
$ cordova run android

A very simple app will display an Apache Cordova screen with a "device ready" message.
Every thing works good.

Open www/index.html
Add the vorlon script.
Replace the meta tag "Content-Security-Policy" by this one:
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' * ">
$ cordova run android
Wait 10 or 20 seconds. The app crash.

Many thank's for investigate a little !
