### ISSUE TITLE
Can't get SSL to work on Azure

### ISSUE THREAD

**Issue by BrandonLive** [MicrosoftDX/Vorlonjs#237]
I've set up the dev-0.16 branch on Azure. I'm able to see the dashboard working with the initial set up, and if I enable authentication, I see the login prompt. In fact, if I then enable SSL bindings on Azure, I'm able to connect to my custom host and see the dashboard/login over SSL.

But if I enable the useSSL option (with my key and cert in place), the server fails to start.

Via failed request tracing I see this just before it decides to return a 500 error for the ms-deploy request:

```
194. NOTIFY_MODULE_COMPLETION ModuleName="ManagedPipelineHandler", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotificationEvent="false", CompletionBytes="4", ErrorCode="The operation completed successfully.
 (0x0)" 20:36:18.263 
195. GENERAL_READ_ENTITY_START  20:36:18.263 
196. GENERAL_READ_ENTITY_END BytesReceived="4", ErrorCode="The operation completed successfully.
 (0x0)" 20:36:18.357 
197. GENERAL_REQUEST_ENTITY Buffer="%FF%FF%FF%FF" 20:36:18.357 
198. NOTIFY_MODULE_START ModuleName="WebSocketMonitoringModule", Notification="READ_ENTITY", fIsPostNotification="false" 20:36:18.357 
199. NOTIFY_MODULE_END ModuleName="WebSocketMonitoringModule", Notification="READ_ENTITY", fIsPostNotificationEvent="false", NotificationStatus="NOTIFICATION_CONTINUE" 20:36:18.357 
200. NOTIFY_MODULE_COMPLETION ModuleName="ManagedPipelineHandler", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotificationEvent="false", CompletionBytes="4", ErrorCode="The operation completed successfully.
 (0x0)" 20:36:18.357 
201. GENERAL_READ_ENTITY_START  20:36:18.357 
202. GENERAL_READ_ENTITY_END BytesReceived="0", ErrorCode="Reached the end of the file.
 (0x80070026)" 20:36:18.357 
203. NOTIFY_MODULE_START ModuleName="WebSocketMonitoringModule", Notification="READ_ENTITY", fIsPostNotification="false" 20:36:18.357 
204. NOTIFY_MODULE_END ModuleName="WebSocketMonitoringModule", Notification="READ_ENTITY", fIsPostNotificationEvent="false", NotificationStatus="NOTIFICATION_CONTINUE" 20:36:18.357 
205. AspNetPipelineEnter Data1="System.Web.ImplicitAsyncPreloadModule" 20:36:18.357 
206. AspNetPipelineLeave Data1="System.Web.ImplicitAsyncPreloadModule" 20:36:18.357 
207. AspNetHttpHandlerEnter  20:36:18.357 
208. AspNetHttpHandlerLeave  20:36:18.357 
209. MODULE_SET_RESPONSE_ERROR_STATUS
Warning
 ModuleName="ManagedPipelineHandler", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="500", HttpReason="InternalServerError", HttpSubStatus="0", ErrorCode="The operation completed successfully.
 (0x0)", ConfigExceptionInfo="" 20:36:18.357 
```

The application log doesn't have much. Just a MemoryStore warning and this:
```
Vorlon.js proxy started on port 5050
Vorlon.js with SSL listening on port \\.\pipe\d6fa750d-9d06-41f5-9b44-6082d7fdf43d
```

Any known issues with SSL support in this branch? Or any particular configuration step I missed?

**Comment by meulta** [comment]
Hey :)

Are you trying to use with a custom certificate or the azure dev one ?

Pulling @pierlag on this one

**Comment by BrandonLive** [comment]
It's a custom cert.

**Comment by BrandonLive** [comment]
BTW, I found this in the IIS log:

```
Module
   iisnode 

Notification
   ExecuteRequestHandler 

Handler
   iisnode 

Error Code
   0x00000002 

Requested URL
   https://zeal-vorlon-dbg:80/server.js 

Physical Path
   D:\home\site\wwwroot\Server\server.js 

Logon Method
   Anonymous 

Logon User
   Anonymous 
```

Is the use of port 80 for an HTTPS request the problem here?

**Comment by meulta** [comment]
Hm, this file should not be requested through a web request

**Comment by meulta** [comment]
I will investigate this with @pierlag and get back to you

**Comment by BrandonLive** [comment]
Could the problem be that it's trying to make a web socket connection using the wrong domain? (i.e. the azurewebsites one, and not the one the cert is valid for?)

I tried various ways of using the baseUrl property to set that, but it seemed to have no effect.

**Comment by meulta** [comment]
Don't think so. Did you set all the domain name information on the configure part of the azure web app?

**Comment by BrandonLive** [comment]
Yes, the domain resolves correctly, and works fine if I disable SSL. Also as I said above, I can access the dashboard via HTTPS and the custom domain if I disable useSSL in the config file. But enabling that always causes the app to hang/abort on startup (and all requests to the site just hang indefinitely). I've also tried with auth disabled, and doing the same thing on a separate deployment of the master branch. Same result in all cases.

**Comment by meulta** [comment]
Did you uploaded your SSLKey and SSLCert and update the config.json to point to these files?

**Comment by BrandonLive** [comment]
Yup.

**Comment by meulta** [comment]
Hm. Ok thanks

**Comment by deltakosh** [comment]
Are you sure this is not a problem to point to a different domain?

**Comment by pierlag** [comment]
You can use https directly (without SSL activation on config.json) on azure deployment URL like : https://myvorlon.azurewebsites.net/dashboard
I will check this issue with a custom domain

**Comment by BrandonLive** [comment]
Doing that loads the dashboard correctly, and serves the client JS just fine, but then the client can't connect to the web socket (and I got a giant red error message at the top of the page). It appeared that this was because it was trying to connect over http which the browser won't allow.

**Comment by meulta** [comment]
Hello @BrandonLive 
I don't understand, did you manage to get your way into making it work ?

**Comment by BrandonLive** [comment]
No, someone told me an issue was identified and they were looking into it. Haven't heard anything since?

What part of my last post wasn't clear? Enabling HTTPS on Azure lets you load the dashboard and serve the JS file over HTTPS, but the client can't connect to the server because it's trying to use regular HTTP.
