### ISSUE TITLE
Running from source & vorlon command

### ISSUE THREAD

**Issue by pebanfield** [MicrosoftDX/Vorlonjs#241]
Hi - I've run into some issues running vorlon on an ubuntu based network VM. To resolve the issue I would like to turn on and off some plugins via configuration. 

In the documentation it is recommended that I run from source. Also, the vorlon command is currently not working in my install. How should the vorlon command actually work? Is it simply an alias for a bash script? If so, what is the script? Also, can I simply run vorlon as a node app? -  'node server.js' or something similar? Thanks!

Peter

**Comment by meulta** [comment]
What you can do is go on an empty folder and run :

git clone https://github.com/MicrosoftDX/Vorlonjs/tree/development-0.0.16
cd vorlonjs
npm install
npm start

Can you tell me if this worked?

**Comment by pebanfield** [comment]
Well so vorlon seems to be running when I run npm start although there are a lot of errors. Here is my output 

user@ubuntu:/opt/node/Vorlonjs$ sudo npm start
[sudo] password for user:

> vorlon@0.0.15 start /opt/node/Vorlonjs
> npm run prepublish && node ./Server/server.js


> vorlon@0.0.15 prepublish /opt/node/Vorlonjs
> npm run build


> vorlon@0.0.15 build /opt/node/Vorlonjs
> npm run build-server && npm run build-client


> vorlon@0.0.15 build-server /opt/node/Vorlonjs
> gulp --gulpfile=./Server/gulpfile.js --cwd=./Server

[11:08:25] Working directory changed to /opt/node/Vorlonjs/Server
[11:08:25] Using gulpfile /opt/node/Vorlonjs/Server/gulpfile.js
[11:08:25] Starting 'default'...
[11:08:25] Starting 'typescript-to-js'...
[11:08:25] Finished 'default' after 6.68 ms
Scripts/vorlon.server.ts(33,17): error TS2345: Argument of type '{ levels: { info: number; warn: number; error: number; verbose: number; api: number; dashboard: n...' is not assignable to parameter of type 'LoggerOptions'.
  Object literal may only specify known properties, and 'levels' does not exist in type 'LoggerOptions'.
Scripts/vorlon.server.ts(46,25): error TS2345: Argument of type '{ level: string; handleExceptions: boolean; json: boolean; timestamp: boolean; colorize: boolean; }' is not assignable to parameter of type 'TransportOptions'.
  Object literal may only specify known properties, and 'json' does not exist in type 'TransportOptions'.
Scripts/vorlon.server.ts(50,51): error TS2345: Argument of type '{ filename: string; }' is not assignable to parameter of type 'TransportOptions'.
  Object literal may only specify known properties, and 'filename' does not exist in type 'TransportOptions'.
Scripts/vorlon.server.ts(53,51): error TS2345: Argument of type '{ filename: string; timestamp: boolean; maxsize: number; }' is not assignable to parameter of type 'TransportOptions'.
  Object literal may only specify known properties, and 'filename' does not exist in type 'TransportOptions'.
[11:08:28] TypeScript: 4 semantic errors
[11:08:28] TypeScript: emit succeeded (with errors)
[11:08:28] Finished 'typescript-to-js' after 2.34 s

> vorlon@0.0.15 build-client /opt/node/Vorlonjs
> gulp --gulpfile=./Plugins/gulpfile.js --cwd=./Plugins

[11:08:28] Working directory changed to /opt/node/Vorlonjs/Plugins
[11:08:29] Using gulpfile /opt/node/Vorlonjs/Plugins/gulpfile.js
[11:08:29] Starting 'typescript-to-js'...
[11:08:29] Starting 'less-to-css'...
[11:08:29] Finished 'less-to-css' after 336 ms
Vorlon/plugins/babylonInspector/libs/babylon.2.1.d.ts(294,5): error TS2300: Duplicate identifier 'URL'.
Vorlon/plugins/babylonInspector/libs/babylon.2.1.d.ts(314,5): error TS2300: Duplicate identifier 'webkitIsFullScreen'.
Vorlon/plugins/babylonInspector/libs/babylon.2.1.d.ts(321,5): error TS2300: Duplicate identifier 'pointerLockElement'.
Vorlon/plugins/babylonInspector/libs/babylon.2.1.d.ts(362,5): error TS2300: Duplicate identifier 'movementX'.
Vorlon/plugins/babylonInspector/libs/babylon.2.1.d.ts(363,5): error TS2300: Duplicate identifier 'movementY'.
Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.client.ts(168,32): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.client.ts(170,48): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.client.ts(178,32): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.client.ts(180,48): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.client.ts(189,48): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.client.ts(198,48): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.client.ts(207,48): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.client.ts(216,48): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.client.ts(240,27): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/interactiveConsole/vorlon.interactiveConsole.dashboard.ts(327,17): error TS2322: Type 'string | number' is not assignable to type 'string'.
  Type 'number' is not assignable to type 'string'.
Vorlon/plugins/xhrPanel/vorlon.xhrPanel.client.ts(67,35): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/xhrPanel/vorlon.xhrPanel.client.ts(68,32): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/xhrPanel/vorlon.xhrPanel.client.ts(72,43): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/xhrPanel/vorlon.xhrPanel.client.ts(73,50): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/xhrPanel/vorlon.xhrPanel.client.ts(78,32): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/xhrPanel/vorlon.xhrPanel.client.ts(79,33): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
Vorlon/plugins/xhrPanel/vorlon.xhrPanel.client.ts(82,62): error TS2496: The 'arguments' object cannot be referenced in an arrow function in ES3 and ES5. Consider using a standard function expression.
__lib.d.ts(6061,5): error TS2300: Duplicate identifier 'pointerLockElement'.
__lib.d.ts(6095,5): error TS2300: Duplicate identifier 'webkitIsFullScreen'.
__lib.d.ts(11802,5): error TS2300: Duplicate identifier 'movementX'.
__lib.d.ts(11803,5): error TS2300: Duplicate identifier 'movementY'.
__lib.d.ts(16032,5): error TS2300: Duplicate identifier 'URL'.
[11:08:31] TypeScript: 27 semantic errors
[11:08:31] TypeScript: emit succeeded (with errors)
[11:08:31] Finished 'typescript-to-js' after 2.62 s
[11:08:31] Starting 'scripts'...
[11:08:31] Starting 'scripts-specific-plugins'...
[11:08:31] Finished 'scripts-specific-plugins' after 6.27 ms
[11:08:31] Starting 'scripts-noplugin'...
[11:08:32] Finished 'scripts-noplugin' after 723 ms
[11:08:32] Finished 'scripts' after 738 ms
[11:08:32] Starting 'default'...
[11:08:32] Starting 'copy'...
[11:08:32] Finished 'copy' after 705 μs
[11:08:32] Starting 'copyPlugins'...
[11:08:32] Finished 'copyPlugins' after 885 μs
[11:08:32] Starting 'copyDTS'...
[11:08:32] Finished 'copyDTS' after 3.56 ms
[11:08:32] Finished 'default' after 6.19 ms
express-session deprecated req.secret; provide secret option Server/Scripts/vorlon.webServer.js:48:26
Vorlon listening on port 1337

**Comment by meulta** [comment]
Hi,

There is this error in the master branch right now because they was a typescript change and we did not reflect this in the master. We will fix lib versions in the master branch as soon as the 0.0.16 is stabilize (really soon ! :))

Please reopen this if you need more info

**Comment by pebanfield** [comment]
Ok thanks. Seems to be working fine so I will double back to update later. Cheers. 

Peter

**Comment by meulta** [comment]
nice to hear :)
