### ISSUE TITLE
Path must be a string

### ISSUE THREAD

**Issue by naresh217** [MicrosoftDX/Vorlonjs#247]
Hi I am trying to use vorlon over https

changed Boolean useSSL to true. 
Placed certificate in cert directory under npm/node_modules/vorlon/server/cert

When i run vorlon its throwing an error "TypeError: path must be a string"

C:\Users\NareshC>vorlon
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at new HttpConfig (C:\Users\NareshC\AppData\Roaming\npm\node_modules\vorlon\Server\config\vorlon.httpconfig.js:17:29)
    at new WebServer (C:\Users\NareshC\AppData\Roaming\npm\node_modules\vorlon\Server\Scripts\vorlon.webServer.js:18:25)
    at Object.<anonymous> (C:\Users\NareshC\AppData\Roaming\npm\node_modules\vorlon\Server\server.js:5:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by naresh217** [comment]
here is my config.json if that helps
i dont have any SSL key. So i have just removed that line

{
    "useSSL": true,
   
    "SSLcert": "cert/mycert.cer",
    "includeSocketIO": true,
    "plugins": [
        { "id": "CONSOLE", "name": "Interactive Console", "panel": "bottom", "foldername": "interactiveConsole", "enabled": true },
        { "id": "DOM", "name": "Dom Explorer", "panel": "top", "foldername": "domExplorer", "enabled": true },
        { "id": "MODERNIZR", "name": "Modernizr", "panel": "bottom", "foldername": "modernizrReport", "enabled": true },
        { "id": "OBJEXPLORER", "name": "Obj. Explorer", "panel": "top", "foldername": "objectExplorer", "enabled": true },
        { "id": "XHRPANEL", "name": "XHR", "panel": "top", "foldername": "xhrPanel", "enabled": true },
        { "id": "NGINSPECTOR", "name": "Ng. Inspector", "panel": "top", "foldername": "ngInspector", "enabled": false },
        { "id": "NETWORK", "name": "Network Monitor", "panel": "top", "foldername": "networkMonitor", "enabled": true },
        { "id": "RESOURCES", "name": "Resources Explorer", "panel": "top", "foldername": "resourcesExplorer", "enabled": true }
    ]
}

**Comment by pierlag** [comment]
hi need SSL key if you want use https :)

**Comment by naresh217** [comment]
Opened certificate and used copied public key as SSL Key. It is looking for in some other directly like 
C:Users/NareshC/cert. 
I have copied both certficate and SSLkey files here but i see below error


C:\Users\NareshC>vorlon
express-session deprecated req.secret; provide secret option AppData\Roaming\npm\node_modules\vorlon\Server\Scripts\vorlon.webServer.js:48:26
2015-10-22T17:40:09.603Z - error: uncaughtException: error:0906D06C:PEM routines:PEM_read_bio:no start line date=Thu Oct 22 2015 13:40:09 GMT-0400 (Eastern Daylight Time), pid=10124, uid=null, gid=null, cwd=C:\Users\NareshC, execPath=C:\Program Files\nodejs\node.exe, version=v0.12.6, argv=[node, C:\
Users\NareshC\AppData\Roaming\npm\node_modules\vorlon\bin\vorlon], rss=79921152, heapTotal=66926080, heapUsed=39195336, loadavg=[0, 0, 0], uptime=17782.4705161, trace=[column=null, file=null, function=Error, line=null, method=null, native=true, column=19, file=_tls_common.js, function=Object.createS
ecureContext, line=108, method=createSecureContext, native=false, column=25, file=_tls_wrap.js, function=Server, line=598, method=null, native=false, column=14, file=https.js, function=new Server, line=36, method=null, native=false, column=10, file=https.js, function=Object.exports.createServer, lin
e=56, method=exports.createServer, native=false, column=61, file=C:\Users\NareshC\AppData\Roaming\npm\node_modules\vorlon\Server\Scripts\vorlon.webServer.js, function=WebServer.start, line=69, method=start, native=false, column=11, file=C:\Users\NareshC\AppData\Roaming\npm\node_modules\vorlon\Server
\server.js, function=, line=12, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js
, function=Module.load, line=355, method=load, native=false], stack=[Error: error:0906D06C:PEM routines:PEM_read_bio:no start line,     at Error (native),     at Object.createSecureContext (_tls_common.js:108:19),     at Server (_tls_wrap.js:598:25),     at new Server (https.js:36:14),     at Object
.exports.createServer (https.js:56:10),     at WebServer.start (C:\Users\NareshC\AppData\Roaming\npm\node_modules\vorlon\Server\Scripts\vorlon.webServer.js:69:61),     at Object.<anonymous> (C:\Users\NareshC\AppData\Roaming\npm\node_modules\vorlon\Server\server.js:12:11),     at Module._compile (mod
ule.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32)]

**Comment by pierlag** [comment]
If you activate SSL nodejs need 2 files to start webserver. On Vorlonjs\Server\cert by default. Files must be access from root server directory
If you just activate SSL it's working on localhost ?

**Comment by naresh217** [comment]
Thanks. Instead of using provided certificate and key. I am using my server certificate and key. 
But still instated of looking certificates under npm/node_modules/vorlon/server/cert it is looking in c:user/<username>/cert.
I have copied cert folder to here and it worked like charm

**Comment by meulta** [comment]
Great !
