### ISSUE TITLE
Request Aborted

### ISSUE THREAD

**Issue by naresh217** [MicrosoftDX/Vorlonjs#253]
Hi, 
I am using vorlon on my https. 
I have changed config to use SSL and every thing works fine. 
But in network it says Status as "Aborted". When we right click and open in new tab and "Add to Exception" it works. 

But the issue is how can i do this or avoid getting this error in ipad.
Note: I am using this in native App. (Uses HTML5)

**Comment by meulta** [comment]
Hello,

Can you give me more information about the error you get? When you say in "network" is it on F12? On Vorlon? What is the "Add to Exception" you are talking about? 

Thanks

**Comment by naresh217** [comment]
Its on F12.  Attached screen shot.
![capture](https://cloud.githubusercontent.com/assets/5828286/10829265/599752b2-7e4f-11e5-9db0-ed04635ccca1.PNG)

**Comment by meulta** [comment]
That seems to be an error related to your certificate.
Is it still valid ? is it a dev one ?

**Comment by meulta** [comment]
I close this as I suppose you have resolved it :)
Reopen it if needed

**Comment by naresh217** [comment]
I still have above error when running over SSL and using system name/ip address instead of localhost
