### ISSUE TITLE
How could i make it work fine with requirejs?

### ISSUE THREAD

**Issue by phyer** [MicrosoftDX/Vorlonjs#255]
if i reference vorlon in index.html head before requirejs, then run project.
I got the error in firebug:
>Error: Mismatched anonymous define() module: function () {
>		return QUnit;
>	}
>http://requirejs.org/docs/errors.html#mismatch
>var error = new previousError(message);

	

how to resolve?

**Comment by phyer** [comment]
Sorry, it's my issue, I could not use firebug  but use web inspector buildin

**Comment by meulta** [comment]
I understand you fixed this :)
Closing the issue
