### ISSUE TITLE
[ngInspector] Error display nothing because "vorlon.ngInspector.interfaces.js" did not include. 

### ISSUE THREAD

**Issue by manudss** [MicrosoftDX/Vorlonjs#257]
To Sebastien Olivier, 

With Vorlon 0.1.0 when I activate the plugin ngInspector, it display nothing. When I go to the console, I see this error : 
```javascript
Uncaught TypeError: Cannot read property 'Controller' of undefinedNgInspectorClient._cleanScope @ VM945 default:3222NgInspectorClient._findRootScopes @ VM945 default:3144NgInspectorClient._packageAndSendScopes @ VM945 default:3136NgInspectorClient.refresh @ VM945 default:3110(anonymous function) @ VM945 default:3115
modernizr.js:4 'webkitAudioContext' is deprecated. Please use 'AudioContext' instead.
```

After reshearch, I have found that is because, the file vorlon.ngInspector.interfaces.js was not included in all the vorlon js files. For that, all object was not known. By addind all code from vorlon.ngInspector.interfaces.js into the file client like this : 
https://gist.github.com/manudss/fe3c8c0b35f5c2de73f8

It's working. You must do it also for the dashboard file : 
https://gist.github.com/manudss/0c4c143ab8a3f7b5af6f

I think there is a better way to include it, but I didn't know how. Could you look at it, please  ?

Many thanks. Feel free to ask me mores questions. 

Emmanuel

**Comment by meulta** [comment]
Hello, this was an error in the javascript files referencing on the dashboard and the client, not directly linked to ng plugin :)

It is fixed in the "dev" branch now: https://github.com/Microsoftdx/vorlonjs/tree/dev
You can get it from there or wait for merge in the master / npm package
