### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by CoachRDeveloper** [MicrosoftDX/Vorlonjs#258]
I performed "npm i -g vorlon" but got all kinds of errors (cannot attach a .log or .txt file). When I then tried to run "vorlon" I got the following error: 
module.js:339
    throw err;
    ^

Error: Cannot find module 'C:\Users\xxx\AppData\Roaming\npm\node_modules\vorlo
n\bin\vorlon'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

The errors during the installation of vorlon that were displayed on the screen:
C:\Users\xxx>npm i -g vorlon
C:\Users\xxx\AppData\Roaming\npm\vorlon -> C:\Users\xxx\AppData\Roaming\npm\
node_modules\vorlon\bin\vorlon

> bufferutil@1.1.0 install C:\Users\xxx\AppData\Roaming\npm\node_modules\vorlo
n\node_modules\bufferutil
> node-gyp rebuild

C:\Users\xxx\AppData\Roaming\npm\node_modules\vorlon\node_modules\bufferutil>i
f not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\np
m\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else
 (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\xxx\AppData\Roaming\npm\node_modules\vorlon\node_modules
\bufferutil
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "vorlon"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xxx\npm-debug.log

**Comment by meulta** [comment]
Hello,

Can you give me more information about your env? Are you on mac, linux, windows? :)

There is an issue we are currently working on for mac :)

**Comment by CoachRDeveloper** [comment]
I'm currently on Windows 7, with NodeJS 5.0.0.

**Comment by meulta** [comment]
I think it might be related to your nodejs version, I will check that

**Comment by MorisatoK** [comment]
I ran into the same problem after upgrading to nodejs v5. Also on Windows 7 (Enterprise if that matters).

Error message (including the Python error that can be ignored) and npm-debug.log can be found [here](https://gist.github.com/MorisatoK/15dde71c061737f2b598)

**Comment by meulta** [comment]
Yep I think we have a pb with npm that comes with this version.
Installing it when cloning from https://github.com/MicrosoftDX/Vorlonjs/tree/dev 
and running "npm install" like here : http://www.vorlonjs.io/

Can you try ?

**Comment by MorisatoK** [comment]
Not sure if I understood you correctly, but `npm i -g git+https://github.com/MicrosoftDX/Vorlonjs#dev`  results in the same error.

**Comment by meulta** [comment]
Do you mean you cloned the repo quand you still got an issue ?
The python one is "normal" but there should be a fallback quand vorlon should still work

**Comment by MorisatoK** [comment]
I now did clone the repo and just did `npm install` inside of it. This seems to build fine from either the master or the dev branch and I can start it from inside the bin directory. However `npm install -g` from inside the repo fails with the bufferutil error again.

**Comment by meulta** [comment]
Yep we are working on this :)
Is it blocking for you ?

**Comment by MorisatoK** [comment]
Thanks for the reply!

At least for me it isn't blocking. I poked the global vorlon shortcuts (from the failed installation) to point to the bin in the git repo. Works for me :)

**Comment by meulta** [comment]
ok perfect, I will keep you updated

**Comment by fr34kyn01535** [comment]
The reason is bufferutil 1.1.0 is not working on current version of node, the repos have a version of vorlon using bufferutil 1.1.0, see https://github.com/websockets/bufferutil/issues/22 for more about this.

**Comment by deltakosh** [comment]
Should be fixed by https://github.com/MicrosoftDX/Vorlonjs/commit/0558f1d020cd427f2fdfa3d4e2202b5ce9202003

**Comment by deltakosh** [comment]
Other option: just run  npm install --no-optional
