### ISSUE TITLE
[ngInspector] Error on first action in dashboard

### ISSUE THREAD

**Issue by kirkone** [MicrosoftDX/Vorlonjs#265]
I have deployed the "dev" branch to azure and enabled "NGINSPECTOR" in the config file.
Now when I run my Angular SPA in Visual Studio the site starts up and in the Moment when I click in Dashboard on the client I get an error in "ClientMessenger.sendRealtimeMessage()".
The error Shows up here:
"var strmessage = JSON.stringify(message);"
and says:
"Circular reference in value argument not supported".

Is there anything I can do to get this working?

best regards,
KirK

A note on the side:
When I disable ngInspector I did not get any error and all works like expected.

**Comment by meulta** [comment]
Hello,

Can you try a very simple Angular app (with a light scope and only one variable in it) and try it the same way ?

Can you paste me the content of the message variable if not to long ?

**Comment by kirkone** [comment]
hi, thanks for the Reply, I will do some tests next Weekend.
I will give an update when I have some new informations.
Greetings, KirK

**Comment by meulta** [comment]
Thanks

**Comment by meulta** [comment]
Hello,

Any news?

**Comment by deltakosh** [comment]
Up?

**Comment by meulta** [comment]
re open if still there
