### ISSUE TITLE
Add a bookmarklet on the documentation

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#268]
Hi guys!

I used VorlonJS yesterday to debug a mobile (iPhone) issue on a HTTP public website. I had to deploy in order to have the "vorlon.js" script included. I think it would be nice to have a bookmarklet to reduce this (temporary) deployment time and effort.

If this interest anyone, I can make a PR. If so, where should I put it (I didn't found it on the repos neither on dev and website projects)?

**Comment by meulta** [comment]
Hello,

You can also se the http proxy which is available in the last version and send the url to your phone to debug it.
Do you think that'll do it?

**Comment by cubitouch** [comment]
Not sure of what you are talking about.
The idea about the bookmarklet was to prompt the "ip:port" of the VorlonJS server to be generic.

**Comment by meulta** [comment]
I am talking about this : http://www.vorlonjs.io/documentation/#vorlon-proxy

How would prompting the ip:port will help to reduce the deployment part?

**Comment by gleborgne** [comment]
What I've thought about for simplyfiying the proxy is an url shortener mecanism, but for hosted scenarios, it means storing those parameters somewhere (just like session based config)

**Comment by cubitouch** [comment]
Sorry, I didn't read all of this about the Proxy. It seems to fit my needs but I cannot make it work at the moment:
![image](https://cloud.githubusercontent.com/assets/7486151/11179991/96b5ff48-8c57-11e5-9767-6f097212ac95.png)

I'm sure this works anyway, I just not have the time right now to have a look at this (I may not be up to date).

My idea was to register a bookmarklet on the client, an iPhone in my case, and use it to add the script directly "from" the client (without deploying it on a public production target website, not reducing the VorlonJS deployment part of course but the target one). I think it can be a good alternative to the proxy.

**Comment by meulta** [comment]
Hm, did you try to go to the http://localhost:1337/httpproxy url ?
Not sure why you get a "false" here.

**Comment by cubitouch** [comment]
Yes, I followed the steps on the proxy page, but got not response of the proxy after entering my URL (HTTP browser error). I pasted what I had in the npm console.

**Comment by meulta** [comment]
I fixed something in the new build process yesterday night.
Can you pull and try again ? :)

**Comment by cubitouch** [comment]
I just pulled. I use the HTTP Proxy page:
![image](https://cloud.githubusercontent.com/assets/7486151/11241277/cb0588f6-8df9-11e5-85b3-3ac5891fdcea.png)

But I receive an empty response error:
![image](https://cloud.githubusercontent.com/assets/7486151/11241275/c2462842-8df9-11e5-8be8-dd8ec9bb5cf8.png)

I got this in the npm console:
![image](https://cloud.githubusercontent.com/assets/7486151/11241376/940091e2-8dfa-11e5-98c1-9f14082ff5ba.png)

**Comment by gleborgne** [comment]
Looks like a bug in managing the redirection, try entering url without "www"

**Comment by cubitouch** [comment]
Right! Seems working, great :)
Thank you.

**Comment by gleborgne** [comment]
I Will look why the redirection did not work though

**Comment by meulta** [comment]
Good ! Thanks 
Do you still think you need the bookmarklet @cubitouch  ?

**Comment by cubitouch** [comment]
Nop, I think the proxy would be easier to use from a mobile. :)

**Comment by meulta** [comment]
Great, i'm closing this one :)
