### ISSUE TITLE
Identify client

### ISSUE THREAD

**Issue by gleborgne** [MicrosoftDX/Vorlonjs#269]
For now, client can be identified by clicking in the Dashboard and it display client number on all clients.

If you consider identifying clients in production, you could not click on identify all (every users will get it). We should have an API client-side to provide an identity for the client.

**Comment by meulta** [comment]
Good idea

**Comment by gleborgne** [comment]
If it's ok, I will start working on it

**Comment by meulta** [comment]
Not yet, we may change stuff on the server part and I would like and it might have an impact on this :)

**Comment by gleborgne** [comment]
Pending pull request with feature implemented :-)

**Comment by meulta** [comment]
Yep works perfectly thanks
