### ISSUE TITLE
Vorlon proxy : don't use localhost hardcoded

### ISSUE THREAD

**Issue by agoeurysky** [MicrosoftDX/Vorlonjs#273]
Hello,

I'm hosting a vorlon server on myserver.com:1337. When I try to use the vorlon proxy (/httpproxy) to debug a website in production, it does not seem to work because I am redirected to **localhost:5050** automatically instead of **myserver.com:5050**.

Do you know this issue ? Is there a way to don't use localhost but the relative url to solve this ?

Thank you.

**Comment by meulta** [comment]
Hello,

You can configure that on the server/config.json file.
There is a vorlonproxyurl

**Comment by meulta** [comment]
Did it help ? :)

**Comment by agoeurysky** [comment]
Yes, thank you :)
