### ISSUE TITLE
Unable to view the plugin data when remote debugging Chrome on an iPad 

### ISSUE THREAD

**Issue by essentialskills** [MicrosoftDX/Vorlonjs#275]
I am struggling to get vorlonjs to view the console, resources, network etc.. when trying to remote debug Chrome (ver 46) on an iPad 4 (iOS ver 9.1).  I can get the DOM stuff working and there are no vorlonjs server errors.  Its just doesn't show any data at all for the other plugins.  Including no data for My Device.  But hovering over the DOM elements does highlight the correct parts on my iPad.   I tested the same site on Window 10 using Chrome and all plugins work fine.  I have the volronjs server running in an Ubuntu ver 14.04.03 Amazon EC2 setup.

I was able to solve my issue using tons of Alerts on a staging server instead of using vorlonjs so its not a rush fix for me. 

Thanks

**Comment by meulta** [comment]
Hello,

How did you get your vorlon instance ?
Are you running vorlon with admin privileges ?

It is weird that the DOM Ex. works but not the other ones...

**Comment by essentialskills** [comment]
> How did you get your vorlon instance ?

I followed your instructions

npm i -g vorlon

> Are you running vorlon with admin privileges ?

I ran it by using “sudo vorlon” at the prompt.

> It is weird that the DOM Ex. works but not the other ones...
That’s what I thought.  Does it work for you guys?  (debugging Chrome on iPad)
I can get Safari on iPad working but not Chrome

**Comment by deltakosh** [comment]
Hello!
can you try with the dev branch version?

**Comment by meulta** [comment]
@essentialskills any news using dev branch ?
Thanks

**Comment by essentialskills** [comment]
Sorry for not getting back to you.  I have not worked on that project since December.  But I am sure you guys fixed it!

**Comment by henryyp** [comment]
I am having similar issue with iOS 9.3.1 on iphone6 chrome 50.0.2661.95

The interactive console just not showing any logs at all.  I can refresh the browser from the dashboard and see the interactive highlight of the dom element on the mobile however just not getting the console.logs.
