### ISSUE TITLE
can't install with node 5.1.0 and npm 3.5.0

### ISSUE THREAD

**Issue by yohaia** [MicrosoftDX/Vorlonjs#277]
Try to install with:
1. **npm i -g vorlon** - failed.
2. clone the repo, run **npm start** - failed

I am on windows 8.1 

Any suggestions?

**Comment by meulta** [comment]
Hello,

We have an issue with this npm version when getting from the NPM repo.
When you cloned the repo, did you run **npm install** before **npm start*** ?

**Comment by yohaia** [comment]
Yes. try this. did not work.

**Comment by meulta** [comment]
@deltakosh is on this one :-)

**Comment by deltakosh** [comment]
Yep..working on it..I keep you posted but expect some delay as this may be only resolvable on node side

**Comment by deltakosh** [comment]
In the meantime, I suggest using node 4
