### ISSUE TITLE
Working with electron

### ISSUE THREAD

**Issue by yohaia** [MicrosoftDX/Vorlonjs#278]
I am using **electron-v0.35.1-win32-x64**,
and having a hard time running it with vorlon.

any idea's what i need to do?

**Comment by gleborgne** [comment]
You first need to build vorlon before trying to run the desktop version (by running npm install and npm start in the root folder). After that, you must make a npm install in the desktop folder.

**Comment by yohaia** [comment]
Thanks, working :+1:
