### ISSUE TITLE
XMLHttpRequest... required Cross Origin Resource Sharing  / WebSocket connection to 'ws://./' failed

### ISSUE THREAD

**Issue by RobbieLePommie** [MicrosoftDX/Vorlonjs#28]
(Previously reported, but issue closed without resolution)

# Debug tools fail to start with error

> SEC7118: XMLHttpRequest for http://localhost:1337/socket.io/?EIO=3&transport=polling&t=1430700342685-0 required Cross Origin Resource Sharing (CORS).
File: 2

or

> "WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED"   [Chrome]

(IE Message, Chrome message respectfully) 

# Notes on deployment

 - All on same machine, straight install, default settings, first test.
 - Added the script line to the top of an existing HTML file in HEAD, before modernizr (with all other JS loaded through require.js in BODY)
 - Windows 8.1

# Notes on debugging
 - Commented out my own modernizr (no difference)
 - Tried running vorlon "console" in both IE and Chrom (no difference)
 - Tried using IP address and "localhost" (no difference).

# Full reports:

> DOM711: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: 2
> HTML1300: Navigation occurred.
File: 2
Started
> SEC7118: XMLHttpRequest for http://localhost:1337/socket.io/?EIO=3&transport=polling&t=1430700955790-0 required Cross Origin Resource Sharing (CORS).
File: 2
> SEC7118: XMLHttpRequest for http://localhost:1337/socket.io/?EIO=3&transport=polling&t=1430700955791-1 required Cross Origin Resource Sharing (CORS).
File: 2
> Start client
> SCRIPT5022: SecurityError
File: vorlon.js, Line: 3, Column: 5164
> SCRIPT5022: SecurityError
File: vorlon.js, Line: 3, Column: 5164
> app started

[IE]

> Started
> Start client
> 'webkitAudioContext' is deprecated. Please use 'AudioContext' instead.
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
> 'webkitURL' is deprecated. Please use 'URL' instead.
> WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
> app started
> Uncaught TypeError: Cannot read property 'length' of null

[Chrome]

**Comment by RobbieLePommie** [comment]
Additional info: this is a reported in console (running the Vorlon server)

> Express server listening on port 1337
> error:   PLUGIN : No dashboard for session id :default type=PLUGIN, session=defa
ult
> error:   PLUGIN : No dashboard for session id :default type=PLUGIN, session=defa
ult
> error:   PLUGIN : No dashboard for session id :default type=PLUGIN, session=defa
ult
> error:   PLUGIN : No dashboard for session id :default type=PLUGIN, session=defa
ult
> error:   PLUGIN : No dashboard for session id :default type=PLUGIN, session=defa
ult
> error:   PLUGIN : No dashboard for session id :default type=PLUGIN, session=defa
ult
> info:    PLUGIN : Send Refresh clientlist to dashboard (0)[Mozilla/5.0 (Windows
NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari
/537.36] on sessionid : default socketid = urOZaqko4XJR9s2aAAAE type=PLUGIN, ses
sion=default
> info:    PLUGIN : New client (0)[Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit
/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36] on sessionid : de
fault socketid = urOZaqko4XJR9s2aAAAE type=PLUGIN, session=default
> info:    PLUGIN : Number clients in session : 01 type=PLUGIN, session=default
> info:    PLUGIN : New client (0) wait... type=PLUGIN, session=default

**Comment by deltakosh** [comment]
Do you mind using vorlon.max.js instead? This will give us more info as this is the unminified version

**Comment by bizzy4758** [comment]
thank you for your help  whatever is necessary thank you bizzy4758

**Comment by RobbieLePommie** [comment]
Using vorlon.max.js  (I think there are two bugs / issues here....)

This is where it bombs in IE11:

>             }, {}], 37: [function (_dereq_, module, exports) {
>                var global = function () {
>                    return this;
>                }();
>                var WebSocket = global.WebSocket || global.MozWebSocket;
>                module.exports = WebSocket ? ws : null;
>                function ws(uri, protocols, opts) {
>                    var instance;
>                    if (protocols) {
>                        instance = new WebSocket(uri, protocols);
>                    } else {
>                        instance = new WebSocket(uri);  <<< This line complains of "Security Error"

url = "ws://localhost:1337/socket.io/?EIO=3&transport=websocket&sid=Pv3ThT3atQbHsTmwAAAE"

Call stack:
> ws [Line: 2898, Col: 25], vorlon.max.js
> WS.prototype.doOpen [Line: 1804, Col: 21], vorlon.max.js
> Transport.prototype.open [Line: 1213, Col: 25], vorlon.max.js
> Socket.prototype.probe [Line: 996, Col: 25], vorlon.max.js
> Socket.prototype.onOpen [Line: 1007, Col: 33], vorlon.max.js
> Socket.prototype.onHandshake [Line: 1044, Col: 25], vorlon.max.js
> Socket.prototype.onPacket [Line: 1018, Col: 37], vorlon.max.js
> Anonymous function [Line: 904, Col: 29], vorlon.max.js
> Emitter.prototype.emit [Line: 687, Col: 29], vorlon.max.js
> Transport.prototype.onPacket [Line: 1241, Col: 21], vorlon.max.js
> callback [Line: 1713, Col: 25], vorlon.max.js
> Anonymous function [Line: 2482, Col: 29], vorlon.max.js
> exports.decodePayloadAsBinary [Line: 2481, Col: 25], vorlon.max.js
> exports.decodePayload [Line: 2321, Col: 29], vorlon.max.js
> Polling.prototype.onData [Line: 1715, Col: 21], vorlon.max.js
> Anonymous function [Line: 1471, Col: 29], vorlon.max.js
> Emitter.prototype.emit [Line: 687, Col: 29], vorlon.max.js
> Request.prototype.onData [Line: 1567, Col: 25], vorlon.max.js
> Request.prototype.onLoad [Line: 1615, Col: 29], vorlon.max.js
> xhr.onreadystatechange [Line: 1541, Col: 41], vorlon.max.js
> Request.prototype.create [Line: 1550, Col: 29], vorlon.max.js
> Request [Line: 1496, Col: 25], vorlon.max.js
> XHR.prototype.request [Line: 1454, Col: 25], vorlon.max.js
> XHR.prototype.doPoll [Line: 1468, Col: 25], vorlon.max.js
> Polling.prototype.poll [Line: 1699, Col: 21], vorlon.max.js
> Polling.prototype.doOpen [Line: 1663, Col: 21], vorlon.max.js
> Transport.prototype.open [Line: 1213, Col: 25], vorlon.max.js
> Socket.prototype.open [Line: 890, Col: 25], vorlon.max.js
> Socket [Line: 840, Col: 25], vorlon.max.js
> Socket [Line: 787, Col: 29], vorlon.max.js

****************************************************************************

Where it first bombs in Chrome:

>         DOMExplorer.prototype._getAppliedStyles = function (node) {
>             // Style sheets
>             var styleNode = new Array();
>             var sheets = document.styleSheets;
>             var style;
>             var appliedStyles = new Array();
>             for (var c = 0; c < sheets.length; c++) {
>                 var rules = sheets[c].rules || sheets[c].cssRules;
>                 for (var r = 0; r < rules.length; r++) {

sheets[c].rules = null for a particular URL (where that URL returns an empty body (no rules). [Used for registration on fast-fonts.net, so I can't simply drop the call, even though it's empty.]

**Comment by RobbieLePommie** [comment]
Further update: more info on issue 1 (IE)

Although I'm requested "localhost", Fiddler is showing the calls as coming from my IP address. If I change the include to "http://IPADDRESS:1337/vorlon.max.js" then there are no security warnings and it shows in console.

I then get other warnings. Should I add here, or log all as separate issues for you?

**Comment by deltakosh** [comment]
Hello Robbie and thanks for your appreciated help:)
Can you share the client project you use?

**Comment by deltakosh** [comment]
Chrome issue with websockets should now be fixed by:
https://github.com/MicrosoftDX/Vorlonjs/commit/d6c257f69b5a6c3206fea79ddd8aac7f1b938cb6

**Comment by deltakosh** [comment]
Please let me know if issues are still here

**Comment by RobbieLePommie** [comment]
Very nicely done. Both issues appear to have cleared up. Thanks.
