### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by Rudloff** [MicrosoftDX/Vorlonjs#281]
It seems vorlon can't find the CSS:
```
false
Error: EACCES, open '/usr/local/lib/node_modules/vorlon/Server/public/stylesheets/style.css'
2015-11-2 23:7:37 - warn:    API : No client in session default type=API, session=default
```

(I am using the 0.1.0 release from npm.)

**Comment by Rudloff** [comment]
It works if I run vorlon with `sudo`.

**Comment by meulta** [comment]
Yep, right now you have run it using sudo.
Making it working without this is on the backlog ;-)

**Comment by marcysutton** [comment]
I just ran into this. Maybe you should update the docs?
