### ISSUE TITLE
install on node 5.3.0 errors

### ISSUE THREAD

**Issue by wdiechmann** [MicrosoftDX/Vorlonjs#288]
Hi,

found this repo and was really looking forward to using Vorlon (sounds so promising)! But is it only for Windows env? On OSX 10.10.5 with node 5.3.0 and npm 3.5.2 an install like ´´´npm install -g vorlon´´´ turns out like this: https://gist.github.com/wdiechmann/d85b6485316084934803

any thoughts?

**Comment by deltakosh** [comment]
Hello, can you try with node 4?

**Comment by wdiechmann** [comment]
which branch would that be?

  origin/v4.0.0-rc
  origin/v4.2.2-proposal
  origin/v4.2.4-proposal
  origin/v4.x
  origin/v4.x-staging

**Comment by gleborgne** [comment]
You could install any release of node 4.x
For now, Node js 5.x is an "unstable" version

**Comment by wdiechmann** [comment]
did that - and the result is here:
https://gist.github.com/wdiechmann/703666a9feea00bdb7a9

(and my node installation is now 4.2.4 - obviously - which if I understand you correctly, is a good thing, as v5.x is still mostly wet dreams ;)

**Comment by meulta** [comment]
Hey!
This last error you have is "normal" and is due to socket.io and buffer util compilation failing. The npm install should have fall back on a precompiled version and everything should work ok.

Can you try and give me an update?

**Comment by wdiechmann** [comment]
took vorlon for a spin this morning - and it runs very well ! 
thank you very much!!

strange that a node update will install an unstable version of node, hmmmm

anyways - once again, thnx!
