### ISSUE TITLE
best practices false negative on "define platform icons"

### ISSUE THREAD

**Issue by wdiechmann** [MicrosoftDX/Vorlonjs#289]
when you run the best practices on a website - vorlon will report 'define platform icons' and add this text:

```add Apple - iOS icons by adding link tags like <link rel="apple-touch-icon-precomposed" href="youricon" sizes="57x57" />```

I believe [as per Apple Developer](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html) the correct text to be:

```add Apple - iOS icons by adding link tags like <link rel="apple-touch-icon" href="youricon" sizes="57x57" />```

**Comment by deltakosh** [comment]
Ok sounds good! I'll fix it
