### ISSUE TITLE
WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by arnochauveau** [MicrosoftDX/Vorlonjs#29]
I get this error in the chrome console when trying to use vorlon: `modernizr.js:4 WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED `

it also shows `Uncaught TypeError: Cannot read property 'length' of null  default:797`

when i place a breakpoint on that line, I can see that the rules object is in fact not null but what one would expect... 

![image](https://cloud.githubusercontent.com/assets/4454851/7452712/78045378-f261-11e4-896e-3ff4e9507584.png)

i'm using chrome on a windows 8.1 device.
hosting my application on a WAMP server on `<my-ip>:80`
I have the vorlon server running on the default port. 

I placed the script tag just before i close the body tag( I used max.js for debugging purposes)..

![image](https://cloud.githubusercontent.com/assets/4454851/7452754/ffa9b840-f261-11e4-8a59-67a78267cd85.png)

I'm accessing the vorlon dashboard via `http://<my-ip>:1337`

the vorlon dashboard doesn't show anything in the DOM explorer, the Modernizr plugin only shows the titles and the Console shows `start client` and seems to do it's job.

Any ideas what the problem might be?

**Comment by seb0zz** [comment]
I have exactly the same issue.

**Comment by deltakosh** [comment]
Hey.   and thanks for the feedback:)
Can you share the client page that you are using?

**Comment by seb0zz** [comment]
Just set up a heroku app for debugging purposes. And here is a simple HTML file for reproducing the problem:

```
<html>
    <head>
        <script type="text/javascript" src="http://vorlonjs.herokuapp.com/vorlon.js"></script>
    </head>
    <body>
        <h1>VorlonJS Test</h1>
        <h2>VorlonJS is loaded from <a href="http://vorlonjs.herokuapp.com">http://vorlonjs.herokuapp.com</a></h2>
    </body>
</html>
```

**Comment by deltakosh** [comment]
Lovely!

**Comment by arnochauveau** [comment]
https://gist.github.com/413a1b929cb7106945c3.git  here's my page

**Comment by deltakosh** [comment]
It was basically due to a test done by modernize
