### ISSUE TITLE
Dashboard plugin container is overflowing on scroll

### ISSUE THREAD

**Issue by SkyPol0** [MicrosoftDX/Vorlonjs#299]
There is a (minimal) CSS issue encountered on Edge and Chrome (others not tested) : 
The pane known as "dashboard-plugins-container" is overflowing over the menu during a right scroll.

![animation](https://cloud.githubusercontent.com/assets/1634645/12436584/e3d52e60-bf16-11e5-9309-7d3de2149a96.gif)

**Comment by deltakosh** [comment]
Hello! this should be fixed in dev branch. BTW we plan to ship 0.2 this week :)
