### ISSUE TITLE
Debugging on mobile device

### ISSUE THREAD

**Issue by chekit** [MicrosoftDX/Vorlonjs#303]
Sorry, but I didn't find FAQ, so I'll ask you here.

I have installed vorlonjs, then implement script tag, than start `vorlon`. But if I try to open up the page with vorlon script tag on a mobile device,I'll got nothing  inside dashboard, but if I open up the page in browser on a desktop where vorlon is runnig, I'll see only that page on desktop. So how can install or set up vorlon to get an opportunity to debug my mobile version of the page?

**Comment by deltakosh** [comment]
Hello Chekit!

this should work directly on mobile. Which mobile are you using?

**Comment by gleborgne** [comment]
Are you sure that your mobile can access the host and port where Vorlon is running ?

**Comment by chekit** [comment]
I have tested on `Google Nexus 5` and `iPhone 5C`.

First time the phone wasn't in the same network with desktop.

The second time the phone and notebook are share the same network and again if I open webpage with script tag on the cell phone vorlon doesn't recognize a client, but If I'm opens the page in the browser on my notebook (where vorlon is started) the dashboard shows me the client.

Maybe I'm doing something wrong?

**Comment by deltakosh** [comment]
can you double check you are not using localhost to reference vorlon.js server?

**Comment by chekit** [comment]
I'm installed vorlonjs via npm and added to the web page as follows: `<script src="http://localhost:1337/vorlon.js"></script>`

I'm testing here: http://artwonder.ru/

**Comment by deltakosh** [comment]
you have to remove localhost if you want to reach your PC from your mobile and instead use IP address

**Comment by chekit** [comment]
Great! Thank you alot for the help!
