### ISSUE TITLE
SecurityError: The operation is insecure

### ISSUE THREAD

**Issue by polikin** [MicrosoftDX/Vorlonjs#31]
`SecurityError: The operation is insecure.`
`...),t.refresh()})},r.prototype._getElementByInternalId=function(e,t){if(t.__intern...`
`vorlon.js (line 4)`

http://recordit.co/nL4QzAOy4j

**Comment by deltakosh** [comment]
Hello Polikin, can you give me more info on your config? How do you use it? Is there any firewall between server and devices?

**Comment by polikin** [comment]
This is what I did. http://recordit.co/oX6xO2wjAF

This is the console log error.
![vorlon](https://cloud.githubusercontent.com/assets/3017112/7472922/2d497eb8-f305-11e4-93a2-7a927b9c46ef.png)

**Comment by deltakosh** [comment]
Adding @pierlag :)

**Comment by polikin** [comment]
Let me know when the update will be done, because I reinstalled vorlon and I had the same error.

**Comment by meulta** [comment]
Not sure it made it into the 0.0.12. Let me have a look :)

**Comment by meulta** [comment]
The fix seems to be in the 0.0.12 on npm. 
The other thing which is weird is that you have "undefined" in the console on the dashboard.
Is this also an error or did you expect that ?

**Comment by polikin** [comment]
it's an error.

**Comment by polikin** [comment]
This is the step I did: http://recordit.co/7cqutrezlT

**Comment by polikin** [comment]
The problem seem to be with Visual Studio or my solution, because I tried with a simple html file and it's work.

**Comment by meulta** [comment]
What javascript lib do you reference? Can you try referencing vorlon.js in the client html file before all other javascript file?

**Comment by polikin** [comment]
I'm using RequiredJS

**Comment by meulta** [comment]
Can you give me a sample were your issue can be reproduce ?
Or your code if shareable?

Thanks

**Comment by pierlag** [comment]
perhaps http vs https ?

**Comment by polikin** [comment]
I tried Vorlon with my localhost.

**Comment by deltakosh** [comment]
is it still the case with latest version ?

**Comment by polikin** [comment]
I reinstalled Vorlon.. same error.

**Comment by pierlag** [comment]
link to RequiredJS probably fix in 0.0.15
