### ISSUE TITLE
Best Practices Plg : Rules's tags are not escaped

### ISSUE THREAD

**Issue by SkyPol0** [MicrosoftDX/Vorlonjs#312]
![untitled](https://cloud.githubusercontent.com/assets/1634645/12736070/6f7cae80-c94d-11e5-9e47-7e8bd619723b.png)

**Comment by meulta** [comment]
Thx, want to work on this? :)

**Comment by SkyPol0** [comment]
Yeah ! I'm in.

**Comment by SkyPol0** [comment]
Oh, issue fixed with #323 by the way !
