### ISSUE TITLE
Connecting to Azure Deployed Instance doesn't work

### ISSUE THREAD

**Issue by LezaMax** [MicrosoftDX/Vorlonjs#313]
I was able to successfully deploy Vorlon to my azure website (from master branch) but no clients can connect to it. Any clues as to how to debug things? It simply never appears on the left sidebar

**Comment by meulta** [comment]
can you share the <script> tag you added yo the website you want to debug? :)

**Comment by LezaMax** [comment]
<script src="http://lezamaxvorlon.azurewebsites.net/vorlon.js"></script>

**Comment by cbotsikas** [comment]
@LezaMax your instance is missing a javascript (vorlon.dashboardManager.js) required for the dashboard. It's fixed on latest master as of https://github.com/MicrosoftDX/Vorlonjs/commit/ccda9c744089b9b5e946365c3d2c0de2aa9a4a18 
You can update your azure deployment and it should work for you too.
Open Azure Portal, locate your VoltronJS Web App Settings and click Publishing->Continuous deployment->Sync

**Comment by meulta** [comment]
Yep sorry about that its my fault ;)
