### ISSUE TITLE
Using system name instead of localhost

### ISSUE THREAD

**Issue by naresh217** [MicrosoftDX/Vorlonjs#314]
I am trying to use my system name to be debugged from another machine. But I am getting "Your connection is not private".
Attached Screen shot for your reference.

But this works perfect if i use localhost instead. 

I am using my application using SSL. 
 

![image](https://cloud.githubusercontent.com/assets/5828286/12831164/d93752ca-cb60-11e5-95a4-6d8ebacfeb64.png)

**Comment by pierlag** [comment]
certificat SSL is link with the URL "name". The sample SSL in source code can only apply to "localhost" name if you need to use a other "name" you must generate a other certificat.
