### ISSUE TITLE
Interactive Console output order is in reverse?

### ISSUE THREAD

**Issue by Mehuge** [MicrosoftDX/Vorlonjs#324]
The newest log entries are at the top, oldest at the bottom.

User Agent dashboard is running in:-

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"

**Comment by meulta** [comment]
Done in dev branch with automatic scroll to element :)
