### ISSUE TITLE
Exception on WIndows 10

### ISSUE THREAD

**Issue by lakichemole** [MicrosoftDX/Vorlonjs#330]
Hi,

I just installed Vorlon desktop on my Laptop, I was able to launch it once (dashboard ...) but then second time I keep having exception
![vorlon_ex](https://cloud.githubusercontent.com/assets/11866119/13313315/fd74a516-dbd7-11e5-9481-83b2ee73b286.png)
![vorlon_ex2](https://cloud.githubusercontent.com/assets/11866119/13313316/fd83553e-dbd7-11e5-8ddd-f2e9140d4f9a.png)

**Comment by meulta** [comment]
Pulling @gleborgne  :)

**Comment by gleborgne** [comment]
Which version did you try ? you download setup from Vorlon website or try from sources ?
This bug should be fixed in the dev branch.

**Comment by lakichemole** [comment]
Yes the setup download, I will try with the dev branch, but its quite big it should be pushed to release :)

**Comment by lakichemole** [comment]
I get the dev version, didn't find an easy way to generate the desktop app, then just used the normal webserver. So I'm working on UWP apps and Xbox One Apps (WinJS) and its working except that Windows dev doesn't allow to execute external script :
 - On Xbox One (ADK Windows 8 apps) --> I needed to import localy vorlon.js and other dependencies directly in the app package
 - On UWP (w10) I used a workaround to load vorlon.js and overridden your LoadScriptAsync function with the same workaround 

But especially for Xbox One development its quite great since its allow us to debug an apps in "real" production condition.

Romain
