### ISSUE TITLE
Troubles on getting Vorlon work with SSL certificate

### ISSUE THREAD

**Issue by tbalouet** [MicrosoftDX/Vorlonjs#331]
So our project just switched to a secure authentification protocol (SSL). I was working with Vorlon for debugging on smartphones before, and it was doing marvels.
I tried making it switch to SSL, following those steps (http://vorlonjs.com/documentation/#ssl-support) and setting our app's certificates, but I get the following bug:
http://i.imgur.com/qRitPRZ.png
Did anyone had this problem before? Is there something more to do? Thanks!

**Comment by Mimetis** [comment]
Hi tbalouet, 
Actually there is an issue with the Vorlon Certificate. It has been corrected in the dev branch.
Can you please try to checkout a local dev branch and test again with the SSL (and provide us feedback) ?

Seb

**Comment by tbalouet** [comment]
I switched to the dev branch, there was an EONENT error on the relative path of the certificates, so I changed them to absolute paths, the server starts normally but I can't reach the service through the 1337 port or the 5050 either.
If I change the certificates to ours I get the same error shown above

**Comment by naresh217** [comment]
I do have an issue while trying over SSL. This never worked.

**Comment by meulta** [comment]
@Mimetis do you have any idea on this ?

**Comment by meulta** [comment]
Hey, I have fixed SSL in the dev branch.
We had an issue, thanks for pointing it out :)

Reopen if still present

**Comment by naresh217** [comment]
How to use this dev branch.
I usually use npm i -g vorlon to get vorlon installed.
