### ISSUE TITLE
Vorlon Accessibility Stuff (the rest)

### ISSUE THREAD

**Issue by marcysutton** [MicrosoftDX/Vorlonjs#333]
Following #332, there are a few more accessibility issues with the Vorlon.js interface. When I ran an aXe audit on it, I found a number of issues needing to be addressed. These include:

- 31 color contrast warnings
- Vorlon.js loading graphic missing alt attribute
- 3 inputs missing labels

The aXe Chrome or Firefox extension can help you find the problematic nodes and suggest fixes. If you need any clarification on these things, let me know!

**Comment by meulta** [comment]
Hello,
Just heading back from an event rush last week.

You are totally right ! We will fix these asap

**Comment by meulta** [comment]
Fixed in dev branch
