### ISSUE TITLE
Allow to pass configuration file to CLI script

### ISSUE THREAD

**Issue by njam** [MicrosoftDX/Vorlonjs#335]
It would be great if one could pass the path of the configuration file to the *vorlon* binary.
```sh
vorlon --config <config-file>
```

Since the configuration is project-specific we could then commit a vorlon configuration file to each web project.
What do you think?

**Comment by msandt3** [comment]
+1

**Comment by msandt3** [comment]
#375

**Comment by meulta** [comment]
thanks @msandt3
