### ISSUE TITLE
Wrong Content-Type for vorlon.js

### ISSUE THREAD

**Issue by senthilp** [MicrosoftDX/Vorlonjs#34]
We set up vorlon in one of our cloud machines. When hitting the JS URL (http://machine-name:1337/vorlon.js) for `vorlon.js`, the `Content-Type` in the response header is `text/html; charset=utf-8` instead of `application/javascript`. We followed these simple [steps](http://www.vorlonjs.com/#getting-started), is there any other setting to change? The full response header is below

**Content-Length:** 123007
**Content-Type:** text/html; charset=utf-8
**Date:** Mon, 04 May 2015 18:27:42 GMT
**ETag:** W/"MGVQ06MpwAGPgBGP2fyzkg=="
**X-Powered-By:** Express

**Comment by deltakosh** [comment]
Adding @meulta for this one

**Comment by meulta** [comment]
Thanls for the feedback, I will have a look
