### ISSUE TITLE
Can't set SSL with desktop app

### ISSUE THREAD

**Issue by stevebeauge** [MicrosoftDX/Vorlonjs#341]
The documentation is a bit unclear. It mentions `Server/config.json`, but I can't find it neither under the desktop app install directory nor the %APPDATA%\vorlon folder (I'm on windows).

When installing a local copy of vorlon using npm install vorlon, I can find the file under the node_modules, but I don't think it's a good practice.

How should I set up ssl with the desktop app ?

thx

**Comment by gleborgne** [comment]
Hi Steve,

Ssl is not supported in the desktop app. I don't see any benefit of having https for the dashboard on the desktop app. Could you explain why you want it ?

If you really need it, you could generate a version of the desktop app using your certificate.

Guillaume

**Comment by stevebeauge** [comment]
Actually, I was trying to simplify debugging of a Word Addin, which requires https

**Comment by meulta** [comment]
Did yo follow this : https://blogs.msdn.microsoft.com/mim/2016/02/18/vorlonjs-plugin-for-debugging-office-addin/ blog post? :)

**Comment by stevebeauge** [comment]
Thanks @meulta; this does not answer my direct question, but will help to reach my goal.

As a suggestion, I'd propose to clarify where the config of the desktop app resides in, and what can or can't be set.
