### ISSUE TITLE
innerText use borks client list entry text

### ISSUE THREAD

**Issue by csuwildcat** [MicrosoftDX/Vorlonjs#35]
`innerText` is an old, proprietary DOM property that is not supported by most modern browsers. We should be using `textContent` instead, but is it a problem if it is only compatible down to IE9? The added benefit of `textContent` is that it does not cause a style recalc like `innerText` does, which is better for perf.

@deltakosh I have a commit to switch these properties that works and makes the client list text appear again in Firefox, etc., but I need to know about our compat targets before pushing it out to DX master.

**Comment by csuwildcat** [comment]
Here is the offending line for review: https://github.com/MicrosoftDX/Vorlonjs/blob/master/Server/public/vorlon.dashboardManager.ts#L127

**Comment by deltakosh** [comment]
Dashboard side is intended to run on modern browesersw

**Comment by deltakosh** [comment]
So please go ahead and use textContent instead

**Comment by csuwildcat** [comment]
This has been resolved via inline commits.
