### ISSUE TITLE
Not working with Cordova on iOS 9

### ISSUE THREAD

**Issue by DamodarSojka** [MicrosoftDX/Vorlonjs#355]
I am including the vorlon file in index.html:
    <script src="http://172.20.184.223:1337/vorlon.js"></script>
But device is never listed in the dashboard, app also takes ages to launch. I think it might timeout . On Android everything works fine.
I am working on a windows7 machine.

**Comment by meulta** [comment]
Hello,

This might be related to the fact that you have to declare the remote url on ios.
You may also need to activate https.

Where are you hosting the vorlon Dashboard?

**Comment by DamodarSojka** [comment]
Can you please explain the remote url thing?

IOS is also not working when I am trying to connect it to the local server, while Android works.
Connection with 'normal' server works, I am not using https for that.

I am using those tags:
    <meta http-equiv="Content-Security-Policy" content="default-src *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src  'self' 'unsafe-inline' *; connect-src *;img-src 'self' data: 'unsafe-inline' 'unsafe-eval' *;">

and in the config.xml
<access origin="*" />

**Comment by meulta** [comment]
Could you try again ? I think a fix for safari might have fixed your issue.

**Comment by meulta** [comment]
Reopen if needed :)
