### ISSUE TITLE
Deploy to Azure not working

### ISSUE THREAD

**Issue by mistrsoft** [MicrosoftDX/Vorlonjs#357]
Hey guys

I can't deploy to Azure using your "Deploy to Azure" button.
When I review the website in azure portal it fails on the step "Running deployment command..."
here's the log output

> Command: deploy.cmd
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Deleting file: 'hostingstart.html'
Copying file: '.dockerignore'
Copying file: '.gitattributes'
Copying file: '.gitignore'
Copying file: '.npmignore'
Copying file: 'azuredeploy-parameters.json'
Copying file: 'azuredeploy.json'
Copying file: 'build-docker-image.sh'
Copying file: 'CONTRIBUTING.md'
Copying file: 'disclaimer.js'
Copying file: 'Dockerfile'
Copying file: 'gulpfile.js'
Copying file: 'LICENSE'
Copying file: 'package.json'
Copying file: 'README.md'
Copying file: 'whatsnew.md'
Copying file: '.vscode\launch.json'
Copying file: '.vscode\settings.json'
Copying file: '.vscode\tasks.json'
Copying file: 'bin\vorlon'
Copying file: 'client samples\nodejs\app.js'
Copying file: 'client samples\nodejs\package.json'
Copying file: 'client samples\nodejs\.vscode\launch.json'
Copying file: 'client samples\webpage\.gitignore'
Copying file: 'client samples\webpage\bestpractices.css'
Copying file: 'client samples\webpage\bestpractices.html'
Copying file: 'client samples\webpage\browsersync.js'
Copying file: 'client samples\webpage\how-to-use-vorlon-in-production.html'
Copying file: 'client samples\webpage\index.css'
Copying file: 'client samples\webpage\index.html'
Copying file: 'client samples\webpage\package.json'
Copying file: 'client samples\webpage\readme.md'
Copying file: 'client samples\webpage\ship.svg'
Copying file: 'client samples\webpage\unitTestRunner.html'
Copying file: 'DeploymentTools\deployment-template.json'
Copying file: 'DeploymentTools\dev-deployment-template-parameters.json'
Copying file: 'DeploymentTools\post-deployment-template.json'
Copying file: 'DeploymentTools\preprod-deployment-template-parameters.json'
Copying file: 'DeploymentTools\production-deployment-template-parameters.json'
Copying file: 'DeploymentTools\production-deployment-template.json'
Copying file: 'DeploymentTools\production-post-deployment-template.json'
Copying file: 'DeploymentTools\production-preview-slot-deletion.ps1'
Copying file: 'desktop\.editorconfig'
Copying file: 'desktop\.gitattributes'
Copying file: 'desktop\.gitignore'
Copying file: 'desktop\gulpfile.js'
Copying file: 'desktop\main.css'
Copying file: 'desktop\package.json'
Copying file: 'desktop\README.md'
Omitting next output lines...
Start script "./Server/server.js" from package.json is not found.
Missing server.js/app.js files, web.config is not generated
Looking for app.js/server.js under site root.
The package.json file does not specify node.js engine version constraints.
The node.js application will run with the default node.js version 4.2.3.
Selected npm version 3.5.1
npm WARN deprecated jade@1.9.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm ERR! fetch failed https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/jsbn/-/jsbn-0.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/dashdash/-/dashdash-1.13.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/jsbn/-/jsbn-0.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
npm ERR! fetch failed https://registry.npmjs.org/dashdash/-/dashdash-1.13.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect EACCES 103.245.222.162:443 - Local (undefined:undefined)
Command 'starter.cmd deploy.cmd' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\r\nstarter.cmd deploy.cmd
One or more errors occurred.
Command 'starter.cmd deploy.cmd' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\r\nstarter.cmd deploy.cmd

**Comment by meulta** [comment]
Hm, I think we still have this racing condition... 
Can you try multiple time (2 or 3) by clicking on the retry button and get back to me with the result?

Thanks

**Comment by mistrsoft** [comment]
Hey, I tried at least 5 times and also tried to Redeploy button in Azure Portal too. Still doesn't work.

Is there a way how to manually deploy it to Azure?
I also tried this 
http://joeraio.com/how-to-deploy-vorlon-js-to-azure-web-app/
to do the manual deployment but didn't worked for me too.

For me it seems that it fails because of something in package.json. When I removed everything except of name, version, description and main then it deploys from local git repo successfully but then I'm getting forbidden error instead..;(

**Comment by meulta** [comment]
Which branch are you using? :)

**Comment by mistrsoft** [comment]
master I believe..;) should I try other one?

**Comment by meulta** [comment]
Yep can you try dev?
Sorry about this... ;)

**Comment by mistrsoft** [comment]
It worked when I switched to dev. cool, thanks mate.;)

**Comment by meulta** [comment]
You are welcome, will be fixed in next release :)
