### ISSUE TITLE
Console plugin - Does not show anything?

### ISSUE THREAD

**Issue by jonasrk** [MicrosoftDX/Vorlonjs#362]
Hi and thanks for this great stuff.

I set up vorlon and it detects my client. My only problem is that the console does not show my anything, e.g. console.log("foo"); in interactive mode creates no output.

I can however use the console to manipulate the HTML on my website.

Not sure how to debug this.

**Comment by meulta** [comment]
Hello,

Could you tell us which browsers you are using?

thx

**Comment by jonasrk** [comment]
I tested on Chrome Version 51.0.2704.103 (64-bit) and Safari Version 9.1.1 (11601.6.17)

**Comment by PaulFasola** [comment]
**Tested on Chrome 51.0.2704.103 64 bits**  Hi @jonasrk ! Just tested, it's working fine for console.log("yourcaption") and just "your caption" (with quotes) ...

Be sure to write your commands in the right textbox (i'm often doing the error to write in the filter textbox, see the pic).

![sans titre](https://cloud.githubusercontent.com/assets/1634645/16304961/0f0a05b8-3958-11e6-92e6-7f8a18aafe6f.png)


--
Else:
Are you working on a fresh and updated dev branch ? 
Do you have any javascript error in your browser's console ? (check the F12 tool or equivalent)

**Comment by jonasrk** [comment]
Hi! Yes, I am in the right text box.

updated dev branch: check.

no js errors.


![jun-23-2016 17-48-45](https://cloud.githubusercontent.com/assets/2970342/16309934/c797185c-396a-11e6-888c-f49e24410b94.gif)

**Comment by vzaidman** [comment]
+1 (same browsers)
also added
`    setInterval(function(){console.log('hi')}, 1000);
`
at the beginning of my code but there is no output. currently running from the outlook application

**Comment by vzaidman** [comment]
+1 (same browsers)
also added
`setInterval(function(){console.log('hi')}, 1000); `
at the beginning of my code but there is no output.
Currently running from the outlook application. tried enable and disable the office plugin.
Opening the add in from the browser instead of from outlook2016 works fine.

**Comment by jonasrk** [comment]
Okay, I thought I had tried opening the plugin in the browser, too. But apparently I have not. If I start it in the Browser Vorlon works fine for me, too.

It's only if I have it in Excel that it's not printing anything.

**Comment by andrewliang** [comment]
I have this same issue as well while trying to debug an Outlook 2016 add-in on Mac

**Comment by meulta** [comment]
@andrewliang what version of vorlon are you using (if from github, which branch?)
@jonasrk what are you debugging (a web site ? if yes on which Platform/browser, an office addin ? if yes on which Platform?) it is the web runtime where you are debugging your code which matters here :)

@vzaidman are you running Outlook on a mac?

Thank a lot to you all to help us getting rid of these bugs ;)

**Comment by vzaidman** [comment]
yes. im running outlook on a mac

**Comment by meulta** [comment]
ok @vzaidman we are working on this one this is a known issue. Should be fixed quickly :)

**Comment by meulta** [comment]
Can you all try to go into configuration, deactivate Best Practices and Network Monitor plugins, try again and tell me if console works? (currently working on the issue on my side ;))

**Comment by jonasrk** [comment]
Hurray, it works! \o/ Thank you.

To answer your question: Excel Add-In, Microsoft Excel for Mac Version 15.23.2 (160624)

**Comment by meulta** [comment]
Fixed in dev branch (soon released) https://github.com/MicrosoftDX/Vorlonjs/tree/dev

**Comment by andrewliang** [comment]
@meulta: Sorry for the late reply. I got vorlon through npm so I assume I got vorlon on the master branch?
