### ISSUE TITLE
Expired certificate

### ISSUE THREAD

**Issue by JohnGoldsmith** [MicrosoftDX/Vorlonjs#367]
Hi,  Have been try to run the dev branch against an Excel addin, as per Sebastien Pertus' post here:

https://blogs.msdn.microsoft.com/mim/2016/02/18/vorlonjs-plugin-for-debugging-office-addin/

...but I'm not able to see the addin in the client list.  

I notice that the certificate (under dev / Server / Cert) has expired.  Would this result in the problem I'm seeing or should I look elsewhere?

**Comment by meulta** [comment]
pulling @Mimetis :)

That might be it.
How did you reference the vorlon.js script in your addin? Can you share this part of your code ?
thanks

**Comment by JohnGoldsmith** [comment]
Hi, Thanks for the reply.  Using the following as the last entry in the head:

`<script src="https://localhost:1337/vorlon.js"></script>`

Chrome shows a warning dialog with this error message `NET::ERR_CERT_DATE_INVALID`

And if you click on 'Proceed to localhost (unsafe)' then Vorlon is displayed but the Client List is empty (even after reset dashboard).

(running the server via npm start, shows the server listening on port 1337)

**Comment by meulta** [comment]
Yep I think that might be certificates.
@Mimetis should be able to fix that

**Comment by JohnGoldsmith** [comment]
Ok, great.  Will stand by - thanks

**Comment by pierlag** [comment]
Fix in dev can you try again

**Comment by JohnGoldsmith** [comment]
Hi, Still no joy I'm afraid.  I now get the following error message:

>localhost:1337 uses an invalid security certificate.
> 
> The certificate is not trusted because it is self-signed.
> 
> Error code: SEC_ERROR_UNKNOWN_ISSUER

I added an exception as before but the still nothing appears in the client list.  Although the Vorlon appears to be working otherwise (v 0.3.0)

I'm also now having a problem displaying a web page in the Excel task pane so I'm not sure if this has messed up my IIS Express cert (or at least finding it)?

**Comment by pierlag** [comment]
This certificat is a Self-signed certificat only for dev environement and localhost. You need to force your navigator to continue with this error message

**Comment by JohnGoldsmith** [comment]
Great, thanks Pierre.  I deleted two older certificates and reinstalled the new one as per Sebastien's post and can confirm that Vorlon can now see the desktop Excel addin including the Office plugin.  Thanks for your help.
