### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by npenin** [MicrosoftDX/Vorlonjs#374]
I am referencing vorlon-node-wrapper which seems to rely on an vulnerable module. Could you please upgrade to the latest ?

https://www.bithound.io/github/domojs/domojs-debug/master/dependencies/npm/vorlon-node-wrapper#security-advisories

**Comment by meulta** [comment]
Hello,
It seems that the vulnerability that you point out comes from Socket.io ?

**Comment by npenin** [comment]
Hi,

Indeed, but from an old version of socket.io. A simple update should do the trick.

**Comment by meulta** [comment]
Hey sorry for the delay I moved on another country so was a bit unavailable.
Should be fixed now!
Can you update the ref and check again ?
Thanks
