### ISSUE TITLE
IE 11 not appearing in console: how to debug ?

### ISSUE THREAD

**Issue by warpdesign** [MicrosoftDX/Vorlonjs#378]
I'm trying to debug a local site on IE11 using Vorlonjs. I have installed and started the server, I can see the dashboard.

But inserting the Vorlonjs script into my website does nothing: the client does not appear on the dashboard. How can I debug it ? Does Vorlonjs support IE11 ?

Note that the same page works just fine with Chrome: the client appears in the dashboard as it should.

**Comment by warpdesign** [comment]
I just noticed that a "security error" from vorlon.js is thrown into the IE11 console. No idea what it is since it points to the minified file.

**Comment by meulta** [comment]
Hello!
Sorry for the delay :)

Can you share with me more information about your configuration ? and what you have in your html code?

**Comment by meulta** [comment]
Up ?

**Comment by warpdesign** [comment]
Sorry for the delay too :)

The problem was from my side: I had two different domain names (pointing to the same IP) but the page & the vorlonjs file didn't use the same domain.

After using the same domain for both it worked.

Thanks for the support.

**Comment by synth** [comment]
I can't get Vorlon to work in IE either. I get SecurityError but no further information. I have installed on our staging server and serving locally, but shouldn't this just work? I tried copying the vorlon.js to the staging server but still serving app locally but seemed to get more errors. It works great in Chrome.
