### ISSUE TITLE
Uncaught ReferenceError: io is not defined

### ISSUE THREAD

**Issue by seb0zz** [MicrosoftDX/Vorlonjs#38]
I only get this error if I add the vorlonjs script tag to the DOM dynamically via JavaScript. Everything works fine if the script tag is in the page head block from the beginning on.

**Comment by deltakosh** [comment]
Humm...this **should** work:)
Will check asap!

**Comment by csuwildcat** [comment]
I am not able to reproduce this on Firefox Beta or Chrome Beta, which browser are you seeing this in?

**Comment by seb0zz** [comment]
Mhhh I am also using Chrome... Let me check if I can setup a small sample project for reproducing the problem.

**Comment by seb0zz** [comment]
Turned out that this is a problem with RequireJS and Socket.io - sorry for the circumstances!

**Comment by atondelier** [comment]
As VorlonJS depends on Socket IO with its ability to detect CommonJS or AMD, it may also do this same detection, thus enabling VorlonJS to be used even if AMD is in use (e.g. RequireJS).

2 temporary solutions: 
 * nullify `define.amd`. ...I even suggest this to be the solution, not to make VorlonJS proper code to implement AMD. (then restore it just after socket.io is loaded)
 * let guys load socket io on their own, preventing socket io to be loaded twice (once in the use app and once with vorlon)

**Comment by meulta** [comment]
Thanks atondelier, I will have a look at this :)
