### ISSUE TITLE
Debugging devices trough vorlon proxy does not work on any iOS older than iOS 10

### ISSUE THREAD

**Issue by damy90** [MicrosoftDX/Vorlonjs#390]
Debugging devices trough vorlon proxy does not work on any iOS older than iOS 10

Steps to reproduce:
1. Setup vorlon and the proxy for debugging trough a local network on your desktop. In config.json:
  "vorlonServerURL": "http://192.168.17.144:1337",
  "vorlonProxyURL": "http://192.168.17.144:5050",
Use your own IP.
2. Run vorlon in cmd
3. Open the vorlon dashboard on your device and go to VORLON PROXY.
4. Open any site (for instance https://github.com/) trough the proxy. Make sure popups are enabled in iOS settings for Safari.

Expected:
A new tab with the dashboard should open in a new tab, followed by the page being debugged, and the device should appear on the dashboard

Result
A new tab with the dashboard opens in a new tab, followed by the page being debugged, but the device **does not** appear on the dashboard

Affected platforms:
iOS 9 and below, vorlon 0.4.0. 

Tested on iOS 8, 9 and 10, and Android Chrome

Aditional info:
 - on iOS 9.3.5 I get the following console error: "Unexpected use of reserved word 'let' in strict mode" in githubcom line 10491.
 - on iOS 8.4.1 I get the following console error: "Unexpected token '('. Ecpected a ':' following the property name 'considerLoggingReccords'" in githubcom line 10387.

Debugging will work if the script is added manually to a site that you can edit the source code of, instead of using the proxy.

**Comment by meulta** [comment]
Will have a look :)

**Comment by damy90** [comment]
Looks like it's fixed in the latest version. Thanks!
