### ISSUE TITLE
Gulp is not install with npm install

### ISSUE THREAD

**Issue by deltakosh** [MicrosoftDX/Vorlonjs#4]

**Comment by latentflip** [comment]
Gulp isn't installed, it's just not installed globally, as a dependency of an npm package cannot be installed globally.

This means that gulp is available to npm scripts (look at the build scripts in package.json) but you cannot just type gulp at the command line without installing it yourself.

I'm going to add a section to the docs today that will explain that if you want to run gulp commands directly you will need to install it globally.

**Comment by latentflip** [comment]
Expanded the docs about gulp, this is probably closeable now.
