### ISSUE TITLE
No text in DOM inspector

### ISSUE THREAD

**Issue by operatino** [MicrosoftDX/Vorlonjs#40]
I connected to test page provided http://cdn.rawgit.com/MicrosoftDX/Vorlonjs/master/Plugins/samples/index.html, and vorlon interface does not expose text in the DOM.

My env: OSx 10.10.2, Nodejs - v0.10.33, Browser Chrome 42/Safari.

![image](http://d.pr/i/1fbKQ+)

Is the tool only optimized for Windows + IE?

**Comment by meulta** [comment]
Hello, 

I can see the dom elements in the screenshot you provide. What docyou expect to see here?

**Comment by operatino** [comment]
I expect to see DOM together with text inside the nodes. Like it's working in any other DOM inspector (Chrome, Safari, Firefox).

**Comment by meulta** [comment]
Ping @deltakosh :-)

**Comment by operatino** [comment]
I mean like this:

![image](http://d.pr/i/11lwJ+)

You may also notice, that `onclick` attribute is also stripped out.

**Comment by deltakosh** [comment]
Hey Operatino!
The support for textnode is part of our next update:)

Events support could be great as well though:)

**Comment by deltakosh** [comment]
Validated
