### ISSUE TITLE
Allow to reference VorlonJS without automatically starting the traces (Core.Start)

### ISSUE THREAD

**Issue by dvoituron** [MicrosoftDX/Vorlonjs#43]
How to start the client VorlonJS only when the user want. For example, first referencing the vorlon.js file, and later execute "VORLON.Core.Start" when the user clicks on a button in this web page?

**Comment by meulta** [comment]
Hello,

You can already do that by including in your project the vorlon.max.js or vorlon.js file that you can get from the github project. We only add the call to Start on the fly when requesting it from the server.

After referencing it on your html page, you can call VORLON.Core.Start whenever you want.

That should do the trick for now and I will add a http://yourdomain/vorlon.nostart.js served by the server asap.

**Comment by dvoituron** [comment]
Thanks.

**Comment by meulta** [comment]
Done here : https://github.com/MicrosoftDX/Vorlonjs/commit/72522eceea90c58fa22efecb00bf47a7e224b9ab

I am updating the npm package also.

You can now reference the client script using 

<script src="http://localhost:1337/vorlon.autostartdisabled.js">/<script>

or

<script src="http://localhost:1337/vorlon.max.autostartdisabled.js">/<script>

Then you just have to call VORLON.Core.Start(...) :)

**Comment by meulta** [comment]
And... done ! ;-)
