### ISSUE TITLE
Osx 10.9.5 vorlon: command not found 

### ISSUE THREAD

**Issue by mikyweb** [MicrosoftDX/Vorlonjs#44]
Hello, i have installed Vorlon width "npm i -g vorlon" command but when i start the server width "vorlon" command i have the message "vorlon: command not found"

Can you help me ?

Thanks

**Comment by meulta** [comment]
I am going to check that :)

**Comment by mikyweb** [comment]
Thanks

**Comment by meulta** [comment]
I just did a test on a OSX with the same version (10.9.5) and I cannot reproduce your issue.
Did you run npm install -g vorlon using sudo ?

**Comment by meulta** [comment]
Any more info on that one mikyweb? :)

Will be happy to help !

**Comment by mikyweb** [comment]
Sorry, I was on vacation.
I have run npm install -g vorlon using sudo but, the command vorlon not function for me.
Thanks
