### ISSUE TITLE
Workers support

### ISSUE THREAD

**Issue by arcturus** [MicrosoftDX/Vorlonjs#45]
It will be really nice to have support for worker.

Despite that the original plugins like dom inspector or modernizr won't make sense, other plugins could be created to interact and debug workers.

Right now I tried by myself with the sample plugin, but it crash againts a dependency with 'document' that in workers is not meet.

**Comment by drcrook1** [comment]
This is sort of like what I'm looking for.  I have a series of IoT robotics devices that run on node.js and I would like to debug them.  I'm trying to figure out how to get remote debugging to work.  There is no dom.  The current debugging tools are un-reliable and continue to fail: https://github.com/Microsoft/nodejstools/wiki/Remote-Debugging-Node.js-running-on-Linux I'm looking at Vorlon as a potential replacement.

**Comment by deltakosh** [comment]
Interesting. We are working on a version where you can define which plugins to use

**Comment by drcrook1** [comment]
Which plugin should I be looking at?  I just started looking at this as an alternative today.  I got the dashboard up and running and was trying to figure out how to get debugging to work on my device, however I can't find instructions or a file that looks like a likely culprit.  I would be more than happy to write up an article if I can get it to work.  http://indiedevspot.com/

**Comment by arcturus** [comment]
I tried to modified the sample plugin, and it's pretty easy, but there is a dependency with the `document` object always.

I'm sure the context can be detected and provide different communication/logging mechanisms.

**Comment by deltakosh** [comment]
Can you point out where the document dependency is?
