### ISSUE TITLE
Add a refresh button on domExplorer

### ISSUE THREAD

**Issue by deltakosh** [MicrosoftDX/Vorlonjs#49]
Like the one in objectExplorer

**Comment by csuwildcat** [comment]
@deltakosh I'd really like to introduce a 'standard' controls bar that can be used across the project. This is but one type of control, and three panels are already using horizontal control/input bars that I believe should be normalized into something all plugin authors can leverage.

I propose the creation of a `<x-control-bar>` custom element that can house action buttons, inputs, and other control elements. This would enable an author to simply include the `x-control-bar` element where they choose, and put whatever controls in it they need.

I already have a couple components that would do nicely for this, in the end it would look like this in markup, with no need for custom JS inside the plugin:

```html
<x-control-bar>
  <x-action event="refresh">Refresh</x-action>
</x-control-bar>
```

The `<x-action>` element is automatically bound with a click event that will emit an event by the name you pass into its `event=""` attribute. This means plugin authors can simply code their refresh logic into the plugin script and not have to worry about linkage or event relay.

I already have this exact element completed here: https://github.com/x-tag/action

What do you think? If we want this in the product by tomorrow, I can hard-code something for a stop gap, then transition to this more maintainable solution afterward.

**Comment by deltakosh** [comment]
Like it..go this way

**Comment by davrous** [comment]
Would be cool also to still monitor dom changes on client side just to tell to the Dashboard that the DOMExplorer is not synchronized with the client device anymore.

**Comment by csuwildcat** [comment]
@deltakosh @davrous dirty checking button/refresh is in for the DOM Explorer, and I just finished swapping out the bespoke control headers in DOM Explorer and Object Explorer with the new `<x-controlbar>` element. All of this is in the components branch. We should all take a look before I do the final push into master.

**Comment by csuwildcat** [comment]
This issue has been resolved in latest commit on master.
