### ISSUE TITLE
CSS Properties Panel

### ISSUE THREAD

**Issue by skmolugu** [MicrosoftDX/Vorlonjs#53]
In Dashboard the newly added CSS properties are not persistent to the session,Click of the same element not showing the newly added properties always its showing the computed styles.

**Comment by deltakosh** [comment]
You're right, we need to fix it!

**Comment by skmolugu** [comment]
I have fixed this but not able to commit showing access denied.

**Comment by deltakosh** [comment]
Can you create a pull request?

**Comment by garora** [comment]
@skmolugu - It will be nice to have this into master. I would like to make it try at my end :+1:
