### ISSUE TITLE
Plugin panel hide/show management is buggy

### ISSUE THREAD

**Issue by csuwildcat** [MicrosoftDX/Vorlonjs#59]
The code that regulates the hide/show of plugin panels is buggy, it allows the user to tab focus elements in panels that are supposed to be hidden. This bumps the visible panel out of view and causes a strange partial view of both panels.

Steps to reproduce:

- load dashboard
- select remote source
- click on the last tag in the DOM Explorer
- tab through past the last tag

You will see the input in the Object Explorer selected, and it will push the top of the DOM Explorer off the screen.

**Comment by meulta** [comment]
Yep I saw that already, I will have a look :)

**Comment by deltakosh** [comment]
Some news? :)

**Comment by meulta** [comment]
Yep this is not exactly what I thought. Need a bit more time to fix it ! :)

**Comment by meulta** [comment]
Fixed.
You can now no more use tab in plugins.

**Comment by csuwildcat** [comment]
I'm going to reopen this to attempt a more targeted fix that blocks the display issue described.

**Comment by csuwildcat** [comment]
@meulta can you roll that commit back? (was it ever pushed into master)

**Comment by csuwildcat** [comment]
@meulta it looks like this bug can be prevented if we ensure the other plugin panels are all set to `display: none;` when not the active tab. I see the Object Explorer is still displayed even though it is not the selected plugin. I tried to search across the project and find the code that manages plugin hide/show, but couldn't find where that code resides. Can you point me there so I can take a look at what it is currently doing?

**Comment by meulta** [comment]
@csuwildcat Thanks, you are right it is a way better way to fix this.
Just rolled back and pushed a version according to that.
