### ISSUE TITLE
CSS Panel missing most content

### ISSUE THREAD

**Issue by evandavis** [MicrosoftDX/Vorlonjs#60]
I'm using Vorlon to inspect a page running in an app webview on Android. The app is running locally in Genymotion. When I select a node, I don't see anything except these strange border styles listed in the CSS panel; sometimes it doesn't show anything at all.

The same behavior occurs if I load up a page in Chrome on the emulator. I can select nodes, console works as expected, but no styles are visible.

Adding new styles in the panel works as expected.

![screenshot 2015-05-13 17 13 03](https://cloud.githubusercontent.com/assets/971616/7621270/82fb0144-f993-11e4-96e5-ce6c130f657a.png)

**Comment by deltakosh** [comment]
Can you share the project you're using?

**Comment by deltakosh** [comment]
Up?

**Comment by evandavis** [comment]
I don't understand the question...?

**Comment by deltakosh** [comment]
Can you share the source code of your app? Or a simpler repro case?

**Comment by evandavis** [comment]
Unfortunately I can't share our source. In attempting to create a simpler repro, it appears that the issue is with our HTML document; loading up the Vorlon testpage in our webview works as expected. I'll open a new ticket if I can isolate the issue, otherwise closing for now.
