### ISSUE TITLE
Not recognizes Android Stock Browser

### ISSUE THREAD

**Issue by haroldSanchezb** [MicrosoftDX/Vorlonjs#61]
I get this message: 

warn:    API : No client in session default type=API, session=default
info:    DASHBOARD : New Dashboard with session id : default type=DASHBOARD, session=default
info:    DASHBOARD : No client selected for this dashboad on this session : default type=DASHBOARD, session=default
info:    DASHBOARD : Received identify for sessionid : default type=DASHBOARD, session=default
error:   DASHBOARD : No client for sessionid : default type=DASHBOARD, session=default

**Comment by patrickkettner** [comment]
what device, what version of android?

**Comment by haroldSanchezb** [comment]
Samsung Galaxy S4, and I get this message with Iphone emulator: 
ReferenceError: Can't find variable: io

**Comment by deltakosh** [comment]
What do you mean by "not recognized" ?

**Comment by haroldSanchezb** [comment]
Not inspect, none client appears

**Comment by deltakosh** [comment]
Ok sounds like a issue with socket.IO
How do you reference vorlon.js? using the single line? Do you use require.js? do you use socket.io on your side?

Pulling in @meulta for help:)

**Comment by haroldSanchezb** [comment]
I use RequireJS, and yes I using the single line

**Comment by deltakosh** [comment]
Ok sounds like a issue with socket.IO
How do you reference vorlon.js? using the single line? Do you use require.js? do you use socket.io on your side?

Pulling in @meulta for help:)

**Comment by haroldSanchezb** [comment]
Ok, I put the line from vorlonjs before requirejs, and when I try to connect nothing appear only the messages from terminal, and when I inspect with forefoxdevedition, I saw the ReferenceError: Can't find variable: io message,

**Comment by deltakosh** [comment]
Ok so this is a known issue with have with socket.io. @meulta is working on a fix:)

**Comment by haroldSanchezb** [comment]
ah Cool, so i'll waiting :)

**Comment by deltakosh** [comment]
This won't be long:)

**Comment by meulta** [comment]
hey @haroldSanchezb :)

Just to be sure, are you loading socket.io with requirejs in your code?
That would help be reproduce the problem
Thanks

**Comment by meulta** [comment]
Also, it would be even better if you could share your files or a substract of it tht reproduce the error.
Thanks

**Comment by meulta** [comment]
Any news on the repro case @haroldSanchezb  ? :)
Thanks a lot

**Comment by haroldSanchezb** [comment]
Hi, is necessary load socket.io in requirejs? I don't use in my project and I load the script before run requirejs, greetings!

**Comment by drazik** [comment]
I also have an issue with android browser. I don't know if it's related. I load VorlonJS using `<script src="http://x.x.x.x:1337/vorlon.js"></script>`  before my `</body>`. When I load my page on android browser, the browser crashes when the page has finished loading.

Here are the logs : 

```
{"type":"API","session":"default","level":"warn","message":"   API : No client in session default","timestamp":"2015-05-21T08:18:53.139Z"}
{"type":"DASHBOARD","session":"default","level":"info","message":"   DASHBOARD : New Dashboard with session id : default","timestamp":"2015-05-21T08:18:53.818Z"}
{"type":"DASHBOARD","session":"default","level":"info","message":"   DASHBOARD : No client selected for this dashboad on this session : default","timestamp":"2015-05-21T08:18:53.819Z"}
{"type":"PLUGIN","session":"default","level":"info","message":"   PLUGIN : Send Refresh clientlist to dashboard (0)[Mozilla/5.0 (Linux; U; Android 4.2.2; fr-fr; SM-T110 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30] on sessionid : default socketid = oh4xzKaLhUjmK8seAAAE","timestamp":"2015-05-21T08:19:14.651Z"}
{"type":"PLUGIN","session":"default","level":"info","message":"   PLUGIN : New client (0)[Mozilla/5.0 (Linux; U; Android 4.2.2; fr-fr; SM-T110 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30] on sessionid : default socketid = oh4xzKaLhUjmK8seAAAE","timestamp":"2015-05-21T08:19:14.658Z"}
{"type":"PLUGIN","session":"default","level":"info","message":"   PLUGIN : Number clients in session : 01","timestamp":"2015-05-21T08:19:14.659Z"}
{"type":"PLUGIN","session":"default","level":"info","message":"   PLUGIN : New client (0) wait...","timestamp":"2015-05-21T08:19:14.659Z"}
{"type":"API","session":"default","level":"info","message":"   API : GetClients nb client 1 in session default","timestamp":"2015-05-21T08:19:14.672Z"}
{"type":"PLUGIN","session":"default","level":"info","message":"   PLUGIN : Delete client socket oh4xzKaLhUjmK8seAAAE for session default(default) ","timestamp":"2015-05-21T08:19:23.362Z"}
```

Do you think I should open another issue or it is related to the current one ?

**Comment by meulta** [comment]
hey,
@haroldSanchezb I am going to prepare you a version doing that.

@drazik can you create another issue with more infor about the android version ? are you testing that on an emulator? which one?

Thanks

**Comment by meulta** [comment]
To keep you updated, we are doing so tests and dev and the version with socket.io optionnal will be available :)

**Comment by haroldSanchezb** [comment]
Good!

**Comment by meulta** [comment]
Hello,

You know have a new parameter in the catalog.json file under server/public (documented here : http://vorlonjs.io/documentation/#vorlonjs-server-advanced-topics) that you can use to choose weither you want to get socket.io from vorlon or not.

The client part is waiting that socket.io is loaded before doing anything so you can load it how you want.

It is available on the github repo code right now (not on npm) can you test it and tell us if it works better?

Thanks
