### ISSUE TITLE
Add HTTPS Support

### ISSUE THREAD

**Issue by samanime** [MicrosoftDX/Vorlonjs#68]
Currently, there doesn't seem to be a way to use this properly with a site in HTTPS. This greatly limits Vorlon.JS' usefulness, as many sites have migrated to using HTTPS everywhere.

Adding HTTPS support would be huge.

**Comment by meulta** [comment]
Hello,

Can you give us more information about the configuration you want to enable here?

Do you mean that the dashboard will be hosted on a website with https?
Do you mean that your website will be available through https?
Will all of the components hosted on the same site?

Thanks a lot !

**Comment by samanime** [comment]
All of the above. =)

In particular, I think the most useful variant would be to be able to launch it over localhost over HTTPS, so you can then add the script to an HTTPS site.

For example, the use-case I was planning to try is:

- Have Vorlon running via localhost
- Load remote HTTPS site (like https://example.com)
- Add script tag via jQuery: $('<script src="https://localhost:1337/vorlon.js"></script>').appendTo('body')
- Visit dashboard

That'd be my ideal scenario. Even if that one isn't possible, having them run off of the same domain would be nice as well.

**Comment by mxmlbernard** [comment]
Hi,

Monitoring a remote HTTPS website while Vorlon is running on localhost would be ideal for me as well.

**Comment by meulta** [comment]
Hello,

@pierlag is going to have a look at this ! :)

**Comment by seanpoulter** [comment]
+1. I'm interested in using this with the same use case.

**Comment by alexnlayer** [comment]
+1. I'm interested in testing my https sites with vorlon :)
Have you been some progress?

**Comment by seanpoulter** [comment]
While we have your attention @pierlag, can I help?

**Comment by deltakosh** [comment]
Hey Sean, Pierre is working on a lot of stuff so if you want to update the server to support HTTPS: Please do :D

**Comment by seanpoulter** [comment]
I'm willing to have a go at it which comes with the warning it's my first venture into TS and the Node/Express server. Would either of you, @deltakosh or @pierlag, be willing to touch base briefly on how you'd want to setup the switch between http/https, where to store the [https options](https://nodejs.org/api/https.html#https_class_https_server)? Not sure what you've got in mind for the interface.

**Comment by alexnlayer** [comment]
I developed some modifications to support https but require some improvements, will finish to try and change that I send to be analyzed :)

**Comment by seanpoulter** [comment]
That'd be great @alexnlayer. You willing to push to your own branch soon?

**Comment by pierlag** [comment]
Thanks @alexnlayer can you make a pull request to add https in the next milestone

**Comment by alexnlayer** [comment]
oks @pierlag, thank you very much, I'm working on it.
Whenever I get finished changes will make a push for review :)

**Comment by alexnlayer** [comment]
@pierlag I finished the changes and have tested on the local server. but I think that this development should work fine in remote server

**Comment by alexnlayer** [comment]
@pierlag  Now I'm getting better development for the SSL option is loaded in the JSON file

**Comment by alexnlayer** [comment]
I published changes to support SSL on a branch.
I have yet the task of documenting those changes and then make a pull request.
If anyone wants to test it can be downloaded from this branch https://github.com/alexnlayer/Vorlonjs/tree/SSL

**Comment by pierlag** [comment]
@alexnlayer can you add vorlon.key and vorlon.crt file in project for developer mode (localhost) ?

**Comment by alexnlayer** [comment]
@pierlag no problem, I start now working on it :)

**Comment by alexnlayer** [comment]
I've already added certificate files for localhost... Sorry for the delay :)

**Comment by pierlag** [comment]
ok for me you can make a pull request :)

**Comment by pierlag** [comment]
Thanks @alexnlayer

**Comment by seanpoulter** [comment]
Thanks @alexnlayer!
