### ISSUE TITLE
Freeze on Chrome Dev 

### ISSUE THREAD

**Issue by kud** [MicrosoftDX/Vorlonjs#74]
When I add Vorlon.js on my webpage, when everything is loaded, Google Chrome freezes and I can't do anything. I can't even refresh the webpage. I have to close and create another tab.

- Android 4.3
- Chrome Dev 44.0.2403.7

**Comment by davrous** [comment]
Hi,

 Can you please share what's in your page? Please list the JS library loaded and if you're doing specifics with the DOM. Would be great if you could share the page somewhere. 

 Does it freeze also using Firefox, IE or Edge?

Thanks!

**Comment by kud** [comment]
I've never used Edge so I don't know. I do not have IE either. I'll try with Firefox to see what happens.

Hard to list the lib we use because they're many.

I will try to make a test webpage.

**Comment by deltakosh** [comment]
I'm pretty sure this is linked to the DOM explorer trying to dump the DOM. @csuwildcat is working on a new way of updating the DOM without relying on DOMContentAdded and DOMContentRemoved

**Comment by csuwildcat** [comment]
I'll try to have this wrapped up by tomorrow afternoon.

**Comment by kud** [comment]
It could help me a lot because I've got some troubles today to make my mobile work with WebIDE or Chrome Canary and vorlon.js/weinre is a solution I think.

Unified debugger everywhere.

**Comment by kud** [comment]
+1 about `DOM explorer` because it's this panel who doesn't load/display anything when I go to the admin.

**Comment by deltakosh** [comment]
Yep, the problem here is that extracting the DOM from clients can take time. So the idea would be to have a button to extract it ONLY on demand

**Comment by deltakosh** [comment]
Fixed by latest commit
