### ISSUE TITLE
Android browser crashing at the end of page loading

### ISSUE THREAD

**Issue by drazik** [MicrosoftDX/Vorlonjs#77]
I have an issue with android browser. I load VorlonJS using `<script src="http://x.x.x.x:1337/vorlon.js"></script>`  before my `</body>`. When I load my page on android browser, the browser crashes when the page has finished loading.

Here are the logs : 

```
{"type":"API","session":"default","level":"warn","message":"   API : No client in session default","timestamp":"2015-05-21T08:18:53.139Z"}
{"type":"DASHBOARD","session":"default","level":"info","message":"   DASHBOARD : New Dashboard with session id : default","timestamp":"2015-05-21T08:18:53.818Z"}
{"type":"DASHBOARD","session":"default","level":"info","message":"   DASHBOARD : No client selected for this dashboad on this session : default","timestamp":"2015-05-21T08:18:53.819Z"}
{"type":"PLUGIN","session":"default","level":"info","message":"   PLUGIN : Send Refresh clientlist to dashboard (0)[Mozilla/5.0 (Linux; U; Android 4.2.2; fr-fr; SM-T110 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30] on sessionid : default socketid = oh4xzKaLhUjmK8seAAAE","timestamp":"2015-05-21T08:19:14.651Z"}
{"type":"PLUGIN","session":"default","level":"info","message":"   PLUGIN : New client (0)[Mozilla/5.0 (Linux; U; Android 4.2.2; fr-fr; SM-T110 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30] on sessionid : default socketid = oh4xzKaLhUjmK8seAAAE","timestamp":"2015-05-21T08:19:14.658Z"}
{"type":"PLUGIN","session":"default","level":"info","message":"   PLUGIN : Number clients in session : 01","timestamp":"2015-05-21T08:19:14.659Z"}
{"type":"PLUGIN","session":"default","level":"info","message":"   PLUGIN : New client (0) wait...","timestamp":"2015-05-21T08:19:14.659Z"}
{"type":"API","session":"default","level":"info","message":"   API : GetClients nb client 1 in session default","timestamp":"2015-05-21T08:19:14.672Z"}
{"type":"PLUGIN","session":"default","level":"info","message":"   PLUGIN : Delete client socket oh4xzKaLhUjmK8seAAAE for session default(default) ","timestamp":"2015-05-21T08:19:23.362Z"}
```

Android version is 4.2.2, running on a Samsung Galaxy Tab 3 Lite. I don't know how to find Android Browser version.

**Comment by meulta** [comment]
Hello,

Does it also fail on the emulator?
Did you try with a simple page?
Can you share your code to help me reproduce this?

Thanks

**Comment by drazik** [comment]
Hi,

I don't know if it fails on the emulator, I don't have it installed. Have to be honest, I don't have so much time to install it and do the test :$

My test was on a very simple page, here is the code : 

```html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>Vorlon</title>
        <link rel="stylesheet" href="global.css" />
    </head>
    <body>
        <p id="test">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>

        <script src="http://10.10.81.109:1337/vorlon.js"></script>
        <script src="global.js"></script>
    </body>
</html>
```

global.css :
```css
body {
    color: #333;
    background-color: #f0f0f0;
}
```

global.js
```javascript
console.log('Hello world !');
```

**Comment by meulta** [comment]
Hello,

Just to keep you informed I did not manage to reproduce the problem.
I will try it using a device at my office but I am in a trip right now and not able to access this device.

I will get back to you soon :)

**Comment by csuwildcat** [comment]
@drazik after testing on both Android's old stock webkit browser and Chrome mobile, I cannot reproduce this bug. Can you please test with the latest versions of Vorlon? We removed some code that was probably causing the issues described.

**Comment by drazik** [comment]
@csuwildcat Ok thanks. I will test today or tommorow and let you know asap.

**Comment by drazik** [comment]
@csuwildcat I still have the same problem after updating to 0.0.15-alpha5.

**Comment by deltakosh** [comment]
I think that csuwildcat mentioned the version on the repo not the one on npm

**Comment by deltakosh** [comment]
Up?

**Comment by csuwildcat** [comment]
@deltakosh will try again to reproduce today, report back this afternoon.

**Comment by csuwildcat** [comment]
@deltakosh @meulta I just tested one of my personal apps that is extremely dynamic and keeps a large number of nodes in the DOM tree for frequent modification. I am not experiencing any crashes on Android's old stock browser or Chrome Mobile using the latest build on master.

**Comment by deltakosh** [comment]
Lovely!! Thank you so much
