### ISSUE TITLE
Plugin functions are uncallable in response to events

### ISSUE THREAD

**Issue by csuwildcat** [MicrosoftDX/Vorlonjs#81]
I have everything in place to switch from the Mutation events that are causing performance issues and crashes as a result of their DOM recomputation in DOM Explorer, but it appears all calls to Plugin functions are blocked from being called inside event listeners via some kind of pseudo-CSP. 

Here's what I am doing: I created a refresh event that bubbles from within a Plugin's UI and is handled at the top level of the Plugin via a listener on the top-most Plugin element. This raises a SecurityError in the console, and reports "The operation is insecure".

Is there something being done to the base Plugin class that prevents calls to functions like `refresh`? If so, I can't figure out why, because there are valid cases where you want to call Plugin functions in response to Plugin-originating events.

@deltakosh @davrous If you have any guidance on this issue let me know, right now I am blocked from fixing issues https://github.com/MicrosoftDX/Vorlonjs/issues/49, https://github.com/MicrosoftDX/Vorlonjs/issues/41, and https://github.com/MicrosoftDX/Vorlonjs/issues/74.

**Comment by deltakosh** [comment]
I will definitely need more info to help.Can you commit your code in a temporary branch?

**Comment by csuwildcat** [comment]
@deltakosh I just pushed it to the components branch

**Comment by csuwildcat** [comment]
Here is the line that throws: https://github.com/MicrosoftDX/Vorlonjs/blob/components/Plugins/Vorlon/plugins/domExplorer/vorlon.domExplorer.ts#L220

**Comment by csuwildcat** [comment]
@deltakosh I am adding a listener to handle `refresh` events thrown from within the DOM Explorer's DOM tree panel. It appears that something is taking issue with a Plugin's function being invoked from inside an event handler.

Is there some form of custom, object-checking/locking CSP that the project or TypeScript employs to prevent this?

**Comment by deltakosh** [comment]
Not to my knowledge:(

**Comment by deltakosh** [comment]
Warning there is a misunderstanding here: the refresh function does not exist dashboard side. You have to send a refresh message to the client side of the plugin.

**Comment by deltakosh** [comment]
Like this: 
Core.Messenger.sendRealtimeMessage(this.getID(), { type: "refresh" }, RuntimeSide.Dashboard); 

And then you have to update this function:
https://github.com/MicrosoftDX/Vorlonjs/blob/components/Plugins/Vorlon/plugins/domExplorer/vorlon.domExplorer.ts#L188

in order to add a "refresh" case

Does it make sense?

**Comment by csuwildcat** [comment]
@deltakosh this event is not coming from the client, it is coming from the dashboard's own UI/elements. If you log `this.refresh` in the scope of that event handler it clearly exists.

Why would a Plugin be charged with creating its own dashboard UI and have no access to its own public/private functions? I don't understand that aspect, can you clarify?

**Comment by csuwildcat** [comment]
@deltakosh you said this in the comment above: "Warning there is a misunderstanding here: the refresh function does not exist dashboard side", but then how come I can log the function and execute it? A security warning makes me thing the object is protected in some way. If the function didn't exist, wouldn't that handler immediately throw undefined when binding/calling it?

**Comment by deltakosh** [comment]
Actually it exists as the same code is executed on the client and on the dashboard. But the dashboard is not executed on the device, so there is no reason to execute refresh() function dashboard side. Right?

You need to use the messenger as I shown before to send a message to the client part of the plugin in order to execute refresh on the device

**Comment by deltakosh** [comment]
I mean: the click will happen on the dashboard, the dashboard is gonna use the messenger to send a message to the client, the client will receive the message, process it and resend the result back to the dashboard

**Comment by csuwildcat** [comment]
@deltakosh hmm, ok, I thought `refresh()` was the function that performed that flow (sending a message to the client and grabbing latest). I will take another look.

**Comment by deltakosh** [comment]
Ok I understand so :)

**Comment by csuwildcat** [comment]
@deltakosh got it working, thanks for the clarification :)

**Comment by deltakosh** [comment]
My pleasure my friend
