### ISSUE TITLE
console.dir()

### ISSUE THREAD

**Issue by torreslucas13** [MicrosoftDX/Vorlonjs#83]
We could have the ```console.dir ()``` function to describe a variable and its attributes . For example:
```javascript
var xyz = {
  x: "Some value",
  y: "Value Some",
  z: "Value Value"
};
console.dir (xyz)
````

And the result on the console would be:
x -> "Some value",
y -> "Value Some",
z: -> "Value Value"

**Comment by meulta** [comment]
I love this !
Pulling @deltakosh for milestone update

**Comment by torreslucas13** [comment]
Thanks, Any predictions for improvement ? : D: D : D: D: D ( sorry for the "pressure" )

**Comment by deltakosh** [comment]
Soooooooon:)

**Comment by deltakosh** [comment]
Done by #104
