### ISSUE TITLE
Inline styles, Path and name attribute not shown in DOM Explorer

### ISSUE THREAD

**Issue by pli88** [MicrosoftDX/Vorlonjs#85]
I have this code

```
<img style="-webkit-transform: rotateY(270deg) translateX(165px);" src="images/img4.jpg" id="Face4" name="Face4" width="768px" height="928px"alt="">
```

Explorer shows just this

```
<img id="Face4">
</img>
```

Is there a way to tweak it to shows all

**Comment by deltakosh** [comment]
This should work with the version on the repo (not on NPM though)

**Comment by pli88** [comment]
I installed the module from repo. But vorlon is not available to my project directory. Do i need to install i locally?

I used  ``` npm link``` from the module directory

**Comment by deltakosh** [comment]
When launched from the repo, you have to 'npm install' in the repo folder and then execute 'vorlon'

**Comment by csuwildcat** [comment]
@pli88 I added full attribute support to master a couple weeks ago. When you get master up, let me know, should work! :)
