### ISSUE TITLE
Style editor doesn't remember modified values

### ISSUE THREAD

**Issue by cvuorinen** [MicrosoftDX/Vorlonjs#87]
When I change an elements styles using the CSS pane in DOM Explorer, the styles get applied correctly. But if I change to another element and then back again, the style editor shows the original styles instead of the modified styles.

The modified styles do persist on the actual element. But if I come back to a changed element and click inside a value I modified before and don't change it but just press enter, then the original value will be applied to the element again.

**Comment by csuwildcat** [comment]
@cvuorinen as soon as the dust settles from the work going on in DOM Explorer, I will attack this issue. We have a team that is doing major refactoring of that plugin, and I don't want to hinder their progress.

**Comment by deltakosh** [comment]
Fixed.
