### ISSUE TITLE
Network Monitor Plugin

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#88]
Hi there,

Have you any plan for a Network monitoring plugin ?

I think I can have a try using this : https://developer.chrome.com/devtools/docs/network
Which seems pretty well supported these days : http://caniuse.com/#search=performance

Regards,
Hugo

**Comment by deltakosh** [comment]
Hello Hugo, we are currently working on xhr analyzers but I do find that your idea is excellent as well. I'll add it to our backlog

**Comment by cubitouch** [comment]
If I have a look at [this](http://getfirebug.com/network), I understand that you are working on a "XMLHttpRequest monitoring" feature, and mine is more concerning a "Watch the timeline unfold" one.

I got you right ?

If it's not a dupplicate, I will try to work on this :)

**Comment by deltakosh** [comment]
You are right :) I would love to have you working on it :)

**Comment by deltakosh** [comment]
PR under review
