### ISSUE TITLE
session, clientId

### ISSUE THREAD

**Issue by zhaowx** [MicrosoftDX/Vorlonjs#89]
when I  see  the source, I find something like session, clientId,but I cannot thought how to use  them.
I guess, i open two or more tabs to debugger the html, I can see these at  the server. but I donot know how  to make it success

**Comment by meulta** [comment]
Hello Zhaowx,

Can you explain me a little be more what you want to achieve here? 
I will get you on the correct way :)

FYI : 
- Session is the ID which used to identify a dashboard session. It is the string that is after the http://yourdashboardurl/dashboard/[HERE]
- clientID is the unique identifier for a specific client (aka : your website running on a browser connected to the dashboard)

**Comment by meulta** [comment]
Hello zhaowx,

Any news on this? :)

Thanks

**Comment by zhaowx** [comment]
let's say there are 3 people:A,B and C. A and B opens a webpage called a.html seperately, while C debugger a.html on dashboard at server. the question is: how to synchronize the information on dashboard of a.html to A and B?
