### ISSUE TITLE
Plugin creation tutorial

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#92]
Hi,

I tried a lot of things in order to create my own plugin, but with no success.
Could someone write a more detailed documentation about how to build a new plugin, step by step ?

* Which folder to create (like in Plugins/Vorlon/plugins/myPlugin/*)
* Which file to edit (like the catalog.json file)
* ... ?

For example, my client side code doesn't seems to execute at all... I saw that my plugin source code is not concatenated under vorlon.js.

**Comment by cubitouch** [comment]
And also, a development prerequisites list would be great (NodeJS Tools for Visual Studio, Gulp, ...)

**Comment by lstefano71** [comment]
I found this: http://blogs.msdn.com/b/emargraff/archive/2015/06/01/how-to-create-a-vorlon-js-plugin.aspx

**Comment by cubitouch** [comment]
Seems great ! :)
Thanks

**Comment by cubitouch** [comment]
This link helped me a lot.
Maybe it should be integrated into the official documentation (at least the link to the MSDN blog post) ?

**Comment by deltakosh** [comment]
Great idea!

**Comment by meulta** [comment]
Hey cubitouch,

I am happy that my tutorial helped you ! :)
It has been added here : http://vorlonjs.io/documentation/#sample-plugin
